### ISSUE TITLE
zero length query file still requires work

### ISSUE THREAD

**Issue by kortschak** [PacificBiosciences/blasr#100]
I am working on a tool that passes subsets of query data to blasr. It is conceivable that a null set is sent to blasr (this has happened in testing).

I would expect that blasr detects an empty query file early and terminates without further work, but this does not appear to be the case:

excerpt of log:
```
2015/08/14 18:52:18 remapping prolog flanks of reads in "mVERYLONGNAME.in.fa"
[INFO] 2015-08-14T18:52:18 [blasr] started.
[INFO] 2015-08-14T19:59:11 [blasr] ended.
```

```
$ ll mVERYLONGNAME.in.fa
-rw-rw-r--. 1 kortschak kortschak 0 Aug 17 11:17 mVERYLONGNAME.in.fa
```

**Comment by mchaisso** [comment]
A reasonable output on a null input is a null output, thus indicating that
the file was opened and read, rather than a problem upstream.

best,
-mark

**Comment by kortschak** [comment]
blasr is doing an awful lot of work to achieve that end:

```
$ touch empty
$ time blasr empty hg19v37.mfa -out empty.blasr
[INFO] 2015-08-18T05:16:43 [blasr] started.
Could not open FASTA file
3020.10user 16.96system 1:20:48elapsed 62%CPU (0avgtext+0avgdata 121208208maxresident)k
1024inputs+80outputs (7major+789613minor)pagefaults 0swaps
$ ll
total 3083588
-rw-rw-r--. 1 kortschak kortschak          0 Aug 18 05:11 empty
-rw-rw-r--. 1 kortschak kortschak          0 Aug 18 06:37 empty.blasr
-rw-rw-r--. 1 kortschak kortschak 3157591129 Aug 18 07:46 hg19v37.mfa
```

It seems to me that a stat on the inputs prior to (presumably) building the index would save this fruitless effort.

As an aside, it also seems that given that the null work case takes a non-trivial amount of time it indicates that indexing is a significant cost and that it might be worth adding the option of pre-building the index to amortise that cost.

**Comment by mchaisso** [comment]
one can use sawriter to pre-build the suffix array and amortize the cost:

>blasr -h
  Options for blasr
   Basic usage: 'blasr reads.{fasta,bas.h5} genome.fasta [-options]
 option Description (default_value).

 Input Files.
   reads.fasta is a multi-fasta file of reads.  While any fasta file is
valid input,
               it is preferable to use pls.h5 or bas.h5 files because they
contain
               more rich quality value information.

   reads.bas.h5|reads.pls.h5 Is the native output format in Hierarchical
Data Format of
               SMRT reads. This is the preferred input to blasr because
rich quality
               value (insertion,deletion, and substitution quality values)
information is
               maintained.  The extra quality information improves variant
detection and mapping
               speed.

   -sa suffixArrayFile
               Use the suffix array 'sa' for detecting matches
               between the reads and the reference.  The suffix
               array has been prepared by the sawriter program.

**Comment by kortschak** [comment]
>one can use sawriter to pre-build the suffix array and amortize the cost:

Sorry, I missed that. Thank you. The other issue remains.

**Comment by mchaisso** [comment]
One of the forms of input to blasr is a file of file names, where each file
is separately opened and aligned to the reference.  Because of this it is
necessary to continue alignments even if one is empty.

**Comment by kortschak** [comment]
I don't see how that blocks this; if you stat the query file and it is zero size you bail. This could be extended to stating each file in the FoF and bailing when they are all zero size (presumably you can know early that the query is a FoF before indexing or loading an SA). Working for an hour when handed a zero sized query is pretty surprising.

**Comment by mchaisso** [comment]
Those currently maintaining the pacbio blasr code base can weigh in.  I
will not address this in my fork.

**Comment by pb-cdunn** [comment]
I agree 100% with @mchaisso: validation does not belong in the executable. But we could provide a pre-checker or wrapper (maybe in Python) which detects empty files and other degenerate cases.

**Comment by kortschak** [comment]
OK. I breaks the Rule of Least Surprise and The Rule of Repair, placing the burden on users to know that this is the behaviour and expecting them to use another shim to replace int the simplest case which would probably catch the vast majority of cases) a few lines of code to perform a stat and size check, bit it's you code.

**Comment by pb-cdunn** [comment]
Validation complexity will tend to increase. E.g. one user might say that empty inputs are ok. Another might say a warning is ok. And another might say that the program should stop immediately.

I'm not saying you're wrong. I'm saying it doesn't belong in the *executable*. A wrapper should also handle command-line argument processing, configuration-file parsing, automatic translation between file-formats, etc. You can then run the underlying tool through the wrapper.

Would a wrapper suffice for you?

**Comment by mchaisso** [comment]
Also, note pipelines may operate better if a null output file is
generated.  For example, gcc will generate an effectively empty output file
for an empty input file, which make will recognize as complete in
subsequent builds.

**Comment by kortschak** [comment]
>Validation complexity will tend to increase. E.g. one user might say that empty inputs are ok. Another might say a warning is ok. And another might say that the program should stop immediately.

This is what exit returns a for.

>I'm not saying you're wrong. I'm saying it doesn't belong in the executable. A wrapper should also handle command-line argument processing, configuration-file parsing, automatic translation between file-formats, etc. You can then run the underlying tool through the wrapper.

That's doing too much. I agree that should not be in the executable, but a trivial zero size check is at most tens of lines, is easily reasoned about and avoid surprising behaviour.

>Would a wrapper suffice for you?

I'm calling blasr from a wrapper, so it really makes no difference to me. I noticed this behaviour and was surprised by it. This report was intended to improve the behaviour of the tool for others.

>Also, note pipelines may operate better if a null output file is generated. For example, gcc will generate an effectively empty output file for an empty input file, which make will recognize as complete in subsequent builds.

I think you are misreading what I'm suggesting. There is no reason that an early bail should not write a null output, it should just omit fruitless work.

**Comment by mchaisso** [comment]
>
> I think you are misreading what I'm suggesting. There is no reason that an
> early bail should not write a null output, it should just omit fruitless
> work.
>
> I agree, that does make sense in the use case presented.  The push back is
that the program is designed to loop over a file of input files, so the
index is created or more likely specified and read once, and then files are
sequentially processed.  The reason for this design is the output of the RS
is a number of small reads files and it's easier to sequentially read them
than to concatenate before aligning.

**Comment by kortschak** [comment]
Yeah, I understand that. The cost of adding a call to stat and a test for zero size is very low though (both from a developer and a machine perspective). If it's not wanted, it's not wanted, but I think it's the wrong decision. It is however PB code, so my opinion is merely that of an outsider.
