### ISSUE TITLE
Cannot install: Readme is incorrect

### ISSUE THREAD

**Issue by b-brankovics** [PacificBiosciences/blasr#101]
Dear contributors,

I cannot install the program. When I am following the instructions, I get errors.
Most of the code refers to the repositories with incorrect URL: "git://" instead of "https://".
Example:

    $ git clone git://github.com/PacificBiosciences/blasr_libcpp.git
    Cloning into 'blasr_libcpp'...
    fatal: unable to connect to github.com:
    github.com[0: 192.30.252.130]: errno=Connection refused

This error also occurs when running travis.sh

**Comment by armintoepfer** [comment]
Are behind a firewall, similar to these problems?
http://stackoverflow.com/questions/19204333/internal-error-github-com0-192-30-252-130-errno-no-error-fatal-unable-to-c
http://stackoverflow.com/questions/21260689/force-bundle-install-to-use-https-instead-of-git-for-github-based-gems

**Comment by pb-cdunn** [comment]
Thanks, Armin. Updated FAQ.
* https://github.com/PacificBiosciences/blasr/wiki/Blasr-Installation-Qs-&-As#answer-6
