### ISSUE TITLE
A Problem with install

### ISSUE THREAD

**Issue by kkrizanovic** [PacificBiosciences/blasr#102]
I've been trying to install blasr in order to test alchemy simulator.

These are the steps I've taken:
- Cloned a blasr git repository
- Downloaded hdf5 from https://www.hdfgroup.org/ftp/HDF5/releases/hdf5-1.8.12/bin/linux-x86_64-gnu481/hdf5-1.8.12-linux-x86_64-gnu481-shared.tar.gz
- run configure.py with --no-pbbam and HDF5_INCLUDE, HDF5_LIB set
- run make build-submodule, it seemed to complete successfully
- run make (or make blasr), that produces an error giving the following message:

/home/kkrizanovic/src/blasr/deps/hdf5-1.8.12-linux-x86_64-gnu481-shared/lib/libhdf5.a(H5PL.o): In function `H5PL_load':
H5PL.c:(.text+0x43e): warning: Using 'dlopen' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
/home/kkrizanovic/src/blasr/deps/hdf5-1.8.12-linux-x86_64-gnu481-shared/lib/libhdf5.a(H5Z.o): In function `H5Z_init_interface':
H5Z.c:(.text+0x627): undefined reference to `SZ_encoder_enabled'
/home/kkrizanovic/src/blasr/deps/hdf5-1.8.12-linux-x86_64-gnu481-shared/lib/libhdf5.a(H5Zszip.o): In function `H5Z_filter_szip':
H5Zszip.c:(.text+0xf3): undefined reference to `SZ_BufftoBuffDecompress'
H5Zszip.c:(.text+0x187): undefined reference to `SZ_BufftoBuffCompress'
collect2: error: ld returned 1 exit status
make: *** [blasr] Error 1

Can you point me towards what I'm doing wrong, please?

**Comment by pb-cdunn** [comment]
You are missing libsz (szip), since HDF5 was built with szip support. Your issue was fully explained here, (in the 2-year-old comments, not the recent ones, though those might help you too):
* https://github.com/PacificBiosciences/blasr/issues/4

If you have szip, you can pass that to make via LDLIBS/LDFLAGS. Otherwise, rebuild HDF5 without szip support.

**Comment by kkrizanovic** [comment]
Thanks,

I really appreciate quick response.

**Comment by pb-cdunn** [comment]
No idea. I'm sure of the status of pbbam in GitHub. Maybe ask a question in the pbcore repo.

**Comment by kkrizanovic** [comment]
Thanks for the quick reply, and for your time.

                K.K.
