### ISSUE TITLE
installation issue: Library not loaded: libpbihdf.dylib

### ISSUE THREAD

**Issue by nahlgren** [PacificBiosciences/blasr#106]
I've attempted to install blasr on Mac OS X 10.10.4 and have encountered a problem.
After installing hdf5 (either using version 1.8.12 or 1.8.15-patch1) and then following the commands in travis.sh, I get this error when attempting to run blasr:

./blasr -h
dyld: Library not loaded: libpbihdf.dylib
  Referenced from: /Users/me/bioinformatics_software/blasr/blasr_hdf5-1.8.15/blasr/./blasr
  Reason: image not found
Trace/BPT trap: 5

What I've executed in detail:

Installation of hdf5
==============
./configure --prefix=/usr/local/hdf5-1.8.15 --enable-cxx
make
make check
make install
make check-install

Installation of blasr (following commands in travis.sh)
========================================
export HDF5_INCLUDE=/usr/local/hdf5-1.8.15/include
export HDF5_INCLUDE=/usr/local/hdf5-1.8.15/include
export HDF5_LIB=/usr/local/hdf5-1.8.15/lib
./configure.py --shared --sub --no-pbbam HDF5_INC=${HDF5_INC} HDF5_LIB=${HDF5_LIB}
make -j4 init-submodule
make --debug=b -j4 all

Thanks for you help.

**Comment by pb-cdunn** [comment]
On Linux, you need:

    LD_LIBRARY_PATH=libcpp/pbdata:libcpp/hdf:libcpp/alignment

Or, drop `--shared` from configure.py. Unfortunately, static linkage is hard on Mac, so you need

    DYLD_LIBRARY_PATH=libcpp/pbdata:libcpp/hdf:libcpp/alignment

I'll update the README. Actually, I plan to add an install rule too, so you can use just one directory in that PATH.
