### ISSUE TITLE
sam to bam(pb:3.0b7)

### ISSUE THREAD

**Issue by orangeSi** [PacificBiosciences/blasr#107]
Hi,I have my sam file not genereated by  blasr ,and convert sam to bam by samtool.But when I use quiver and that bam file,an error show me that I need a bam 3.0b7 file. SO how to convert general sam to bam3.0b7 ?
Thanks!

**Comment by ylipacbio** [comment]
As far as I know, Quiver does not accept general bam file at this point, the input bam file **has** to conform to PacBio BAM spec 3.0b7. The PacBio pipeline won't be available to public until Nov 2015.

You can still use the SMRTAnalysis 2.3 pipeline to generate cmp.h5 and call Quiver. 

Or if you do want to try the pipeline early,  you may email Tzvetana Kerelska <tkerelska@pacificbiosciences.com>, explain your use cases and request to try SMRTPipe 3.0 beta.

**Comment by orangeSi** [comment]
SMRT2.3 only support input fomat of bax.h5 for generate cmp.h5. But I want use subread.fa to run blasr to generate bam file for quiver.
 So i want to convert general bam to bam3.0b7..

**Comment by orangeSi** [comment]
hi,
 I find the way ! 
         1. First I use samtoh5  to convert sam file(generated by daligner) to cmp.h5. 
          2.Then I use quiver with cmp.h5  ,but an error is happen "Failure: Selected Quiver parameter set is incompatible with this cmp.h5 file due to missing data tracks."
         I just share with you ,and will also ask this question in Quiver github issue.But if you have time for answer me , I will be  appreciated .
Thanks!

**Comment by ylipacbio** [comment]
"But I want use subread.fa to run blasr to generate bam file for quiver."

This is not the right way to call quiver because quiver requires quality values to polish consensus sequences. Even though you can make the pipeline work, quiver won't give you results that you want.

**Comment by orangeSi** [comment]
now I use cmp.h5 for quiver instead of bam,but I meet this error：
     1. First I use samtoh5 to convert sam file(generated by daligner) to cmp.h5. 
      2.Then I use quiver with cmp.h5 ,but an error is happen "Failure: Selected Quiver parameter set is incompatible with this cmp.h5 file due to missing data tracks."
