### ISSUE TITLE
Problem with LD_LIBRARY_PATH export in makefile

### ISSUE THREAD

**Issue by marchoeppner** [PacificBiosciences/blasr#111]
Hi,

apart from the fact, this blasr is a bit of a pain to get running, I found an issue in the current version of the makefile.

Specifically, it overrides the systems LD_LIBRAY_PATH. In my case, this means my custom install of GCC throws an  error and compilation fails. A fix seems to be:

export LD_LIBRARY_PATH := $(LD_LIBRARY_PATH):${HDF5_LIB}:${LIBBLASR_LIB}:${LIBPBIHDF_LIB}:${LIBPBDATA_LIB}

**Comment by pb-cdunn** [comment]
These makefiles have evolved. I think they're at least getting better. Unfortunately, blasr still requires too much configuration. (HDF5? PBBAM?)

LD_LIBRARY_PATH is needed for running when configured with `--shared`. We really need that only for gtest and the cramtests, so I'd like to move that to a separate makefile. But for now I'll just apply your suggestion, in a moment.
