### ISSUE TITLE
blasr compilation error

### ISSUE THREAD

**Issue by kalbflei** [PacificBiosciences/blasr#114]
Hello,

To the best of my knowledge, I have installed hdf5 correctly (configure.py output below)  efforts to make blasr are failing as it cannot seem to `open/find limbic.so.2`.
```
tskalb01@user1$  uname -a
Linux user1 2.6.32-504.30.3.el6.x86_64 #1 SMP Wed Jul 15 10:13:09 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

tskalb01@user1$ ./configure.py 
`uname`
Linux
writing to '/scratch/home/tskalb01/blasr/defines.mk':
"""
LIBPBDATA_LIB        ?= /scratch/home/tskalb01/blasr/libcpp/pbdata
LIBBLASR_LIBFLAGS    ?= -lblasr
HDF5_LIB             ?= /home/tskalb01/hdf5-1.8.15-patch1/hdf5/lib/
DL_LIBFLAGS          ?= -ldl
HDF5_INC             ?= /home/tskalb01/hdf5-1.8.15-patch1/hdf5/include
LIBPBDATA_INC        ?= /scratch/home/tskalb01/blasr/libcpp/pbdata
PBBAM_LIBFLAGS       ?= -lpbbam
LIBPBIHDF_INC        ?= /scratch/home/tskalb01/blasr/libcpp/hdf
HTSLIB_LIBFLAGS      ?= -lhts
LIBBLASR_LIB         ?= /scratch/home/tskalb01/blasr/libcpp/alignment
SHELL                ?= bash
RT_LIBFLAGS          ?= -lrt
HDF5_LIBFLAGS        ?= -lhdf5_cpp -lhdf5
LIBPBDATA_LIBFLAGS   ?= -lpbdata
LIBPBIHDF_LIBFLAGS   ?= -lpbihdf
ZLIB_LIBFLAGS        ?= -lz
LIBBLASR_INC         ?= /scratch/home/tskalb01/blasr/libcpp/alignment
PTHREAD_LIBFLAGS     ?= -lpthread
LIBPBIHDF_LIB        ?= /scratch/home/tskalb01/blasr/libcpp/hdf
LDFLAGS+=-static
"""
```
----
```
tskalb01@user1$ make
make -C utils
make[1]: Entering directory `/scratch/home/tskalb01/blasr/utils'
g++ -std=c++0x -pedantic -Wall -Wuninitialized -Wno-div-by-zero -MMD -MP -w -fpermissive  -I/scratch/home/tskalb01/blasr/libcpp/alignment -I/scratch/home/tskalb01/blasr/libcpp/pbdata -I/scratch/home/tskalb01/blasr/libcpp/hdf -I/home/tskalb01/hdf5-1.8.15-patch1/hdf5/include  -c -o LoadPulses.o LoadPulses.cpp
/scratch/local/gcc/4.8.5/bin/../libexec/gcc/x86_64-unknown-linux-gnu/4.8.5/cc1plus: error while loading shared libraries: libmpc.so.2: cannot open shared object file: No such file or directory
make[1]: *** [LoadPulses.o] Error 1
make[1]: Leaving directory `/scratch/home/tskalb01/blasr/utils'
make: *** [makeutils] Error 2
```
any help you can provide would be greatly appreciated.

Best regards,

Ted

**Comment by pb-cdunn** [comment]
> LDFLAGS+=-static

I don't understand your error message (which apparently refers to a shared library while building the `LoadPulses.o` compilation unit, which should not require linking at all). But I think you should re-run `configure.py` with `--shared`. See the latest [README.INSTALL.md](https://github.com/PacificBiosciences/blasr/blob/master/README.INSTALL.md).

**Comment by kalbflei** [comment]
I started from scratch, configured using --shared, worked my way through to "make blasr" am getting a different error this time.

g++ -O3 -g -std=c++0x -pedantic -Wall -Wuninitialized -Wno-div-by-zero -MMD -MP -w -fpermissive -fno-builtin-malloc -fno-builtin-calloc -fno-builtin-realloc -fno-builtin-free -fno-omit-frame-pointer  -I/scratch/home/tskalb01/blasr/libcpp/alignment -I/scratch/home/tskalb01/blasr/libcpp/pbdata -I/scratch/home/tskalb01/blasr/libcpp/hdf -I/home/tskalb01/hdf5-1.8.15-patch1/hdf5/include  -c -o Blasr.o Blasr.cpp
g++ -o blasr -O3 -g -std=c++0x -pedantic -Wall -Wuninitialized -Wno-div-by-zero -MMD -MP -w -fpermissive -fno-builtin-malloc -fno-builtin-calloc -fno-builtin-realloc -fno-builtin-free -fno-omit-frame-pointer  -I/scratch/home/tskalb01/blasr/libcpp/alignment -I/scratch/home/tskalb01/blasr/libcpp/pbdata -I/scratch/home/tskalb01/blasr/libcpp/hdf -I/home/tskalb01/hdf5-1.8.15-patch1/hdf5/include -MF"blasr.d" Blasr.o -L/scratch/home/tskalb01/blasr/libcpp/alignment -L/scratch/home/tskalb01/blasr/libcpp/pbdata -L/scratch/home/tskalb01/blasr/libcpp/hdf -L/home/tskalb01/hdf5-1.8.15-patch1/hdf5/lib/ -lpbihdf -lblasr -lpbdata -lpbihdf  -lhdf5_cpp -lhdf5   -lz -lrt -lpthread -ldl
/scratch/home/tskalb01/blasr/libcpp/hdf/libpbihdf.so: undefined reference to `H5::H5Location::iterateAttrs(void (*)(H5::H5Location&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, void*), unsigned int*, void*)'
/scratch/home/tskalb01/blasr/libcpp/hdf/libpbihdf.so: undefined reference to `H5::CommonFG::createGroup(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, unsigned long) const'
/scratch/home/tskalb01/blasr/libcpp/hdf/libpbihdf.so: undefined reference to `_ZNK2H58CommonFG15getObjnameByIdxB5cxx11Ey'
/scratch/home/tskalb01/blasr/libcpp/hdf/libpbihdf.so: undefined reference to `H5::Attribute::write(H5::DataType const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const'
/scratch/home/tskalb01/blasr/libcpp/hdf/libpbihdf.so: undefined reference to `H5::Attribute::read(H5::DataType const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) const'
/scratch/home/tskalb01/blasr/libcpp/hdf/libpbihdf.so: undefined reference to `_ZNK2H59Exception12getDetailMsgB5cxx11Ev'
collect2: error: ld returned 1 exit status
make: *** [blasr] Error 1

**Comment by pb-cdunn** [comment]
You need `--sub`, unless you build/install blasr_libcpp some other way. Again, see README.INSTALL.md. Please post the actual command-line to `configure.py`. It is the most important step.

**Comment by pb-cdunn** [comment]
It looks like libpbihdf.so was built against different HDF5 headers. You might need to rebuild the sub-libraries. Try `make cleanall`.

If that doesn't work, your HDF5 headers might not match your HDF5 library.

**Comment by kalbflei** [comment]
tskalb01@user1$ ./configure.py --shared --sub --no-pbbam HDF5_INCLUDE=/home/tskalb01/hdf5-1.8.15-patch1/hdf5/include HDF5_LIB=/home/tskalb01/hdf5-1.8.15-patch1/hdf5/lib 

is what I am using.  I ran "make cleanall", and then reran the configure.py line above, ran "make build-submodule", followed by make, ran through, all of the way but blasr doesn't run.  

tskalb01@user1$ ./blasr 
./blasr: error while loading shared libraries: libpbihdf.so: cannot open shared object file: No such file or directory

**Comment by pb-cdunn** [comment]
Well, that's a different problem entirely. We have LD_LIBRARY_PATH in the makefile for when we run our cramtests. You'll have to set that yourself, or install the shared libraries into your system path.

We could add an "install" target. Would that help you?

**Comment by kalbflei** [comment]
Yes, it would.

**Comment by pb-cdunn** [comment]
Really, these makefiles still need a lot of work. (The sub-directory makefiles will not easily build in an external directory, e.g.) I won't have time for refactoring anytime soon.

But you can script this. It's very simple. Just copy the `*.so` from `libcpp/*/*` into the directory of your choice, and put that directory into your `LD_LIBRARY_PATH` (or `DYLD_LIBRARY_PATH` on macosx). I hope that helps.

**Comment by kalbflei** [comment]
Chris,

I have picked up this project again, and am trying to build blasr fresh from github.  I am unable to make anything.  I’ve included the output of the configure script, as well as the error I get when I endeavor to make build-submodule.  Any help you can provide would be greatly appreciated.

—Ted


tskalb01@user1$ ./configure.py --shared --sub --no-pbbam HDF5_INCLUDE=/home/tskalb01/hdf5/include HDF5_LIB=/home/tskalb01/hdf5/lib

`uname`

Linux

writing to '/scratch/home/tskalb01/blasr/defines.mk':

"""

LIBPBDATA_LIB        ?= /scratch/home/tskalb01/blasr/libcpp/pbdata

LIBBLASR_LIBFLAGS    ?= -lblasr

HDF5_LIB             ?= /home/tskalb01/hdf5/lib

DL_LIBFLAGS          ?= -ldl

HDF5_INC             ?= /home/tskalb01/hdf5/include

LIBPBDATA_INC        ?= /scratch/home/tskalb01/blasr/libcpp/pbdata

LIBPBIHDF_LIBFLAGS   ?= -lpbihdf

LIBPBIHDF_INC        ?= /scratch/home/tskalb01/blasr/libcpp/hdf

LIBBLASR_LIB         ?= /scratch/home/tskalb01/blasr/libcpp/alignment

SHELL                ?= bash

RT_LIBFLAGS          ?= -lrt

HDF5_LIBFLAGS        ?= -lhdf5_cpp -lhdf5

LIBPBDATA_LIBFLAGS   ?= -lpbdata

ZLIB_LIBFLAGS        ?= -lz

LIBBLASR_INC         ?= /scratch/home/tskalb01/blasr/libcpp/alignment

PTHREAD_LIBFLAGS     ?= -lpthread

NOPBBAM              ?= 1

LIBPBIHDF_LIB        ?= /scratch/home/tskalb01/blasr/libcpp/hdf

"""

——


tskalb01@user1$ make build-submodule

make -C libcpp

make[1]: Entering directory `/scratch/home/tskalb01/blasr/libcpp'

make libpbdata

make[2]: Entering directory `/scratch/home/tskalb01/blasr/libcpp'

make -C /scratch/home/tskalb01/blasr/libcpp//pbdata libconfig.h

make[3]: Entering directory `/scratch/home/tskalb01/blasr/libcpp/pbdata'

cp -af  libconfig.h

cp: missing destination file operand after `libconfig.h'

Try `cp --help' for more information.

make[3]: *** [libconfig.h] Error 1

make[3]: Leaving directory `/scratch/home/tskalb01/blasr/libcpp/pbdata'

make[2]: *** [libpbdata] Error 2

make[2]: Leaving directory `/scratch/home/tskalb01/blasr/libcpp'

make[1]: *** [all] Error 2

make[1]: Leaving directory `/scratch/home/tskalb01/blasr/libcpp'

make: *** [build-submodule] Error 2

**Comment by pb-cdunn** [comment]
Ok. Let's start over.
* What is your O/S? As specific as possible.
* What is the commit of blasr?
* What is your exact command-line for configure.py?
* What is the error message?

**Comment by kalbflei** [comment]
tskalb01@user1$ uname -a

Linux user1 2.6.32-504.30.3.el6.x86_64 #1 SMP Wed Jul 15 10:13:09 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux


I did a git pulldown this morning.


tskalb01@user1$ ./configure.py --shared --sub --no-pbbam HDF5_INCLUDE=/home/tskalb01/hdf5/include HDF5_LIB=/home/tskalb01/hdf5/lib


As for the error, looks like a cp command in make isn’t getting all the arguments it needs.


tskalb01@user1$ make build-submodule

make -C libcpp

make[1]: Entering directory `/scratch/home/tskalb01/blasr/libcpp'

make libpbdata

make[2]: Entering directory `/scratch/home/tskalb01/blasr/libcpp'

make -C /scratch/home/tskalb01/blasr/libcpp//pbdata libconfig.h

make[3]: Entering directory `/scratch/home/tskalb01/blasr/libcpp/pbdata'

cp -af  libconfig.h

cp: missing destination file operand after `libconfig.h'

Try `cp --help' for more information.

make[3]: *** [libconfig.h] Error 1

make[3]: Leaving directory `/scratch/home/tskalb01/blasr/libcpp/pbdata'

make[2]: *** [libpbdata] Error 2

make[2]: Leaving directory `/scratch/home/tskalb01/blasr/libcpp'

make[1]: *** [all] Error 2

make[1]: Leaving directory `/scratch/home/tskalb01/blasr/libcpp'

make: *** [build-submodule] Error 2

**Comment by pb-cdunn** [comment]
Is it still the error you mentioned most recently?

> ./blasr: error while loading shared libraries: libpbihdf.so: cannot open shared object file: No such file or directory

**Comment by kalbflei** [comment]
No, or at least I don’t think so.  I could be wrong, but my last go round, I was always able to build the submodules.  Where should libconfig.h be written?

**Comment by pb-cdunn** [comment]
`libconfig.h` would be in `libcpp/`, plus symlinked in subdirs.

I need to see how you run `configure.py`, and the error message when you build.

**Comment by kalbflei** [comment]
Sorry,

I thought I’ve included that before.


./configure.py --shared --sub --no-pbbam HDF5_INCLUDE=/home/tskalb01/hdf5/include HDF5_LIB=/home/tskalb01/hdf5/lib

`uname`

Linux

writing to '/scratch/home/tskalb01/blasr/defines.mk':

"""

LIBPBDATA_LIB        ?= /scratch/home/tskalb01/blasr/libcpp/pbdata

LIBBLASR_LIBFLAGS    ?= -lblasr

HDF5_LIB             ?= /home/tskalb01/hdf5/lib

DL_LIBFLAGS          ?= -ldl

HDF5_INC             ?= /home/tskalb01/hdf5/include

LIBPBDATA_INC        ?= /scratch/home/tskalb01/blasr/libcpp/pbdata

LIBPBIHDF_LIBFLAGS   ?= -lpbihdf

LIBPBIHDF_INC        ?= /scratch/home/tskalb01/blasr/libcpp/hdf

LIBBLASR_LIB         ?= /scratch/home/tskalb01/blasr/libcpp/alignment

SHELL                ?= bash

RT_LIBFLAGS          ?= -lrt

HDF5_LIBFLAGS        ?= -lhdf5_cpp -lhdf5

LIBPBDATA_LIBFLAGS   ?= -lpbdata

ZLIB_LIBFLAGS        ?= -lz

LIBBLASR_INC         ?= /scratch/home/tskalb01/blasr/libcpp/alignment

PTHREAD_LIBFLAGS     ?= -lpthread

NOPBBAM              ?= 1

LIBPBIHDF_LIB        ?= /scratch/home/tskalb01/blasr/libcpp/hdf

"""

I was unable to build the submodules using make build-submodule, however going directly into libcpp, I was able to build using the README.md file within.  Coming back up to the top blasr directory, I tried to run “make blasr”


g++ -O3 -g -std=c++0x -pedantic -Wall -Wuninitialized -Wno-div-by-zero -MMD -MP -w -fpermissive -fno-builtin-malloc -fno-builtin-calloc -fno-builtin-realloc -fno-builtin-free -fno-omit-frame-pointer  -I/scratch/home/tskalb01/blasr//include -I/scratch/home/tskalb01/blasr/libcpp/alignment -I/scratch/home/tskalb01/blasr/libcpp/pbdata -I/scratch/home/tskalb01/blasr/libcpp/hdf -I/home/tskalb01/hdf5/include  -c -o Blasr.o Blasr.cpp

In file included from /scratch/home/tskalb01/blasr/libcpp/hdf/HDFGroup.hpp:9:0,

                 from /scratch/home/tskalb01/blasr/libcpp/hdf/HDFData.hpp:7,

                 from /scratch/home/tskalb01/blasr/libcpp/hdf/HDFArray.hpp:10,

                 from /scratch/home/tskalb01/blasr/libcpp/hdf/HDFBasReader.hpp:17,

                 from /scratch/home/tskalb01/blasr/libcpp/alignment/files/ReaderAgglomerate.hpp:16,

                 from iblasr/BlasrHeaders.h:76,

                 from iblasr/BlasrMiscs.hpp:4,

                 from Blasr.cpp:3:

/scratch/home/tskalb01/blasr/libcpp/hdf/HDFAttributable.hpp:8:33: error: variable or field 'CallStoreAttributeName' declared void

 void CallStoreAttributeName(H5::H5Location &obj, std::string attrName, void *attrListPtr);

                                 ^

/scratch/home/tskalb01/blasr/libcpp/hdf/HDFAttributable.hpp:8:29: error: 'H5Location' is not a member of 'H5'

 void CallStoreAttributeName(H5::H5Location &obj, std::string attrName, void *attrListPtr);

                             ^

/scratch/home/tskalb01/blasr/libcpp/hdf/HDFAttributable.hpp:8:45: error: 'obj' was not declared in this scope


Etc…


Culminating in


/scratch/home/tskalb01/blasr/libcpp/hdf/HDFAtom.hpp:130:1: note: in expansion of macro 'DECLARE_TYPED_CREATE_ATOM'

 DECLARE_TYPED_CREATE_ATOM(uint64_t, H5::PredType::STD_I64LE)

 ^

make: *** [Blasr.o] Error 1


I think my previous error was caused by the fact that the default gcc compiler was incredibly old.  I’ve updated it to a more current version, and have gotten further.  Is it possible that the python, and other dependencies are too old to compile blasr correctly?


—Ted

**Comment by pb-cdunn** [comment]
I you provide a way to contact you, I wouldn't mind chatting sometime. This back-and-forth is slower than talking to Matt Damon on Mars. I'm sure your problem is easy to solve.

**Comment by kalbflei** [comment]
Happily.

I’ll be around all afternoon at the number in the signature line.  Just give me about a five minute heads up so I can get logged in and such.

Best regards,

Ted

Ted Kalbfleisch
Assistant Professor
School of Medicine
University of Louisville
221 F Baxter II
580 South Preston Street
Louisville, KY
40202

ted.kalbfleisch@louisville.edu

502-852-7495

**Comment by pb-cdunn** [comment]
The main problem here turned out to be a missing `--enable-cxx` when configuring hdf5, which had to be re-built and re-installed.

But there was a strange one after that. Static linking was failing with:

    /usr/bin/ld: cannot find -lz

I thought **ld** would use libz.so if libz.a is missing. However, libz.so is missing too. libz.so.1 exists, and that was linked successfully after we switched to dynamic loading.

Anyway, problem(s) solved! Best of luck. I'll definitely try that radio station, FPK.

**Comment by kalbflei** [comment]
Thank you very much. You can stream the radio station at www.wfpk.org<http://www.wfpk.org>.

Sent from my iPhone

On Oct 22, 2015, at 6:22 PM, Christopher Dunn <notifications@github.com<mailto:notifications@github.com>> wrote:


The main problem here turned out to be a missing --enable-cxx when configuring hdf5, which had to be re-built and re-installed.

But there was a strange one after that. Static linking was failing with:

/usr/bin/ld: cannot find -lz


I thought ld would use libz.so if libz.a is missing. However, libz.so is missing too. libz.so.1 exists, and that was linked successfully after we switched to dynamic loading.

Anyway, problem(s) solved! Best of luck. I'll definitely try that radio station, FPK.

**Comment by mjhsieh** [comment]
mj chimes in: ```ln -s libz.so.1 libz.so``` should help.
