### ISSUE TITLE
Failure to compile in virtualenv Ubuntu 14.04

### ISSUE THREAD

**Issue by ramarquezo** [PacificBiosciences/blasr#116]
I have a problem compiling blasr, I'm trying to get it because I need pbalign to use Quiver, but pbalign doesn't run correctly, after a lot of time it generates the following error: 
[ERROR] FilterService returned a non-zero exit status. /bin/sh: samFilter: command not found, then I'm trying to get apart the blasr to solve the problem..... 
  
I used the following to compile:

    (VE-QUIVER)alejo-lgmb@alejolgmb-HP-Z230-Tower-Workstation:~/VE-QUIVER/bin/blasr$ ./configure.py --shared --no-pbbam HDF5_INCLUDE=/usr/local/hdf5/include HDF5_LIB=/usr/local/hdf5/lib
````
(VE-QUIVER)alejo-lgmb@alejolgmb-HP-Z230-Tower-Workstation:~/VE-QUIVER/bin/blasr$ make
g++ -O3 -g -std=c++0x -pedantic -Wall -Wuninitialized -Wno-div-by-zero -MMD -MP -w -fpermissive -fno-builtin-malloc -fno-builtin-calloc -fno-builtin-realloc -fno-builtin-free -fno-omit-frame-pointer  -I/home/alejo-lgmb/VE-QUIVER/bin/blasr/libcpp/alignment -I/home/alejo-lgmb/VE-QUIVER/bin/blasr/libcpp/pbdata -I/home/alejo-lgmb/VE-QUIVER/bin/blasr/libcpp/hdf -I/usr/local/hdf5/include  -c -o Blasr.o Blasr.cpp
In file included from /home/alejo-lgmb/VE-QUIVER/bin/blasr/libcpp/hdf/HDFGroup.hpp:9:0,
                 from /home/alejo-lgmb/VE-QUIVER/bin/blasr/libcpp/hdf/HDFData.hpp:7,
                 from /home/alejo-lgmb/VE-QUIVER/bin/blasr/libcpp/hdf/HDFArray.hpp:10,
                 from /home/alejo-lgmb/VE-QUIVER/bin/blasr/libcpp/hdf/HDFBasReader.hpp:17,
                 from /home/alejo-lgmb/VE-QUIVER/bin/blasr/libcpp/alignment/files/ReaderAgglomerate.hpp:16,
                 from MappingIPC.h:14,
                 from Blasr.cpp:15:
/home/alejo-lgmb/VE-QUIVER/bin/blasr/libcpp/hdf/HDFAttributable.hpp:8:33: error: variable or field ‘CallStoreAttributeName’ declared void
 void CallStoreAttributeName(H5::H5Location &obj, std::string attrName, void *attrListPtr);
                                 ^
/home/alejo-lgmb/VE-QUIVER/bin/blasr/libcpp/hdf/HDFAttributable.hpp:8:29: error: ‘H5Location’ is not a member of ‘H5’
 void CallStoreAttributeName(H5::H5Location &obj, std::string attrName, void *attrListPtr);
                             ^
...
make: *** [Blasr.o] Error 1
```

**Comment by pb-cdunn** [comment]
(I truncated stderr for you.)

What version of HDF5? And was it built with C++ support?

Also, I think you should add `--sub` to `configure.py`. And `make build-submodule`.

**Comment by ramarquezo** [comment]
Hi pb-cdunn, I already installed the last version of HDF5 (1.8.15), it was built with c++, I have tried with --sub and make build-submodule but always happens the same.

**Comment by pb-cdunn** [comment]
Here is where it comes from for me:
```cpp
# 25 ".../hdf5/include/H5Cpp.h" 2
# 1 ".../hdf5/include/H5Location.h" 1
# 20 ".../hdf5/include/H5Location.h"
# 1 ".../hdf5/include/H5Classes.h" 1
# 21 ".../hdf5/include/H5Classes.h"
namespace H5 {

 class Exception;
 class IdComponent;
 class H5Location;
  ...
```
See if you can find those files in your HDF5 include directories. Maybe your version is too *new*!

Try to build Blasr.o with `-E` to see the preprocessor output. Maybe you can debug from that info.

**Comment by ramarquezo** [comment]
Thanks pb-cdunn for your reply, these files are not in my HDF5 include directories, are located in /hdf5-1.8.15-patch1/c++/src directory....

**Comment by ramarquezo** [comment]
sorry my ignorance, I don't understand what do you mean by build Blasr.o with -E ...

**Comment by ramarquezo** [comment]
I ran: 
alejo-lgmb@alejolgmb-HP-Z230-Tower-Workstation:/bin/blasr$ sudo ./configure.py --shared --sub --no-pbbam HDF5_INCLUDE=/hdf5-1.8.15-patch1/c++/src HDF5_LIB=/usr/local/hdf5/lib

And after that I did "make build-submodule", it looks like if there isn't any problem with 'libcpp' libraries, but after that I ran make and I had the following:

g++ -o blasr -O3 -g -std=c++0x -pedantic -Wall -Wuninitialized -Wno-div-by-zero -MMD -MP -w -fpermissive -fno-builtin-malloc -fno-builtin-calloc -fno-builtin-realloc -fno-builtin-free -fno-omit-frame-pointer  -I/bin/blasr/libcpp/alignment -I/bin/blasr/libcpp/pbdata -I/bin/blasr/libcpp/hdf -I/home/alejo-lgmb/Documents/hdf5-1.8.15-patch1/c++/src -MF"blasr.d" Blasr.o -L/bin/blasr/libcpp/alignment -L/bin/blasr/libcpp/pbdata -L/bin/blasr/libcpp/hdf -L/usr/local/hdf5/lib -lpbihdf -lblasr -lpbdata -lpbihdf  -lhdf5_cpp -lhdf5   -lz -lrt -lpthread -ldl
/bin/blasr/libcpp/hdf/libpbihdf.so: undefined reference to `H5::H5Location::getNumAttrs() const'
/bin/blasr/libcpp/hdf/libpbihdf.so: undefined reference to `H5::DataType::DataType(H5::PredType const&)'
/bin/blasr/libcpp/hdf/libpbihdf.so: undefined reference to `H5::H5Location::iterateAttrs(void (*)(H5::H5Location&, std::string, void*), unsigned int*, void*)'
/bin/blasr/libcpp/hdf/libpbihdf.so: undefined reference to `H5::H5Location::createAttribute(char const*, H5::DataType const&, H5::DataSpace const&, H5::PropList const&) const'
/bin/blasr/libcpp/hdf/libpbihdf.so: undefined reference to `H5::H5Location::openAttribute(char const*) const'
collect2: error: ld returned 1 exit status
make: *** [blasr] Error 1

**Comment by pb-cdunn** [comment]
> HDF5_INCLUDE

I thought that disappeared. We use HDF5_INC now. What commit of blasr are you using?

    git rev-parse HEAD

Anyway, at least you're past the compilation problem. You now are missing the library which implements the headers that you compiled against. Maybe someone near you can help you with a proper HDF5 installation? This does not appear to be a blasr issue, and it is difficult for us to debug a problem like. Sorry.
