### ISSUE TITLE
trouble building blasr without internet connection

### ISSUE THREAD

**Issue by ebioman** [PacificBiosciences/blasr#144]
Hello
I have the problem that I am generating rpm packages for distribution and these have to be build in a mock environment without internet access.
Your travis.sh recommendations work with restrictions for me if installed locally - I have to build them static instead but then everything's great.
The problem is that this obviously wont work in a mock environment, so I just tried to follow your installation readme instructions. But then it fails with:

      + cd blasr-master
      + export       'PATH=/software/bin:/software/bin:/usr/lib64/ccache:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/sbin$'
      + PATH='/software/bin:/software/bin:/usr/lib64/ccache:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/sbin$'
      + ./configure.py --sub --no-pbbam HDF5_INC=/software/include/ HDF5_LIB=/software/lib/
      uname
      writing to '/builddir/build/BUILD/blasr-master/defines.mk':
      """
      LIBPBDATA_LIB        ?= /builddir/build/BUILD/blasr-master/libcpp/pbdata
      LIBBLASR_LIBFLAGS    ?= -lblasr
      HDF5_LIB             ?= /software/lib/
      DL_LIBFLAGS          ?= -ldl
      HDF5_INC             ?= /software/include/
      LIBPBDATA_INC        ?= /builddir/build/BUILD/blasr-master/libcpp/pbdata
      LIBPBIHDF_LIBFLAGS   ?= -lpbihdf
      LIBPBIHDF_INC        ?= /builddir/build/BUILD/blasr-master/libcpp/hdf
      LIBBLASR_LIB         ?= /builddir/build/BUILD/blasr-master/libcpp/alignment
      SHELL                ?= bash
      RT_LIBFLAGS          ?= -lrt
      HDF5_LIBFLAGS        ?= -lhdf5_cpp -lhdf5
      LIBPBDATA_LIBFLAGS   ?= -lpbdata
      ZLIB_LIBFLAGS        ?= -lz
      LIBBLASR_INC         ?= /builddir/build/BUILD/blasr-master/libcpp/alignment
      PTHREAD_LIBFLAGS     ?= -lpthread
      LIBPBIHDF_LIB        ?= /builddir/build/BUILD/blasr-master/libcpp/hdf
      LDFLAGS+=-static
      """
      ----
      + make build-submodule
     DON'T use pbbam which is not on github.
      cd libcpp && NOPBBAM=true HDF5_LIB=/software/lib/ HDF5_INC=/software/include/ ./configure.py
      /bin/sh: ./configure.py: No such file or directory
      make: *** [build-submodule] Error 127
      error: Bad exit status from /var/tmp/rpm-tmp.J0elUx (%build)

So, why do you keep that folder actually empty - I guess I would have to execute now `` git submodule update --init``? But this I wont be able to do since I am not having internet access at that instance....
So is there a way to build blasr **just from the master zip** ?

**Comment by pb-cdunn** [comment]
> DON'T use pbbam which is not on github.

What commit are you using? I do not see that string anywhere. We only support the tip of the master branch.

> So is there a way to build blasr just from the master zip?

Download the zipfile for blasr_libcpp also. You can unzip it as `libcpp`. Then
```
make configure-submodule
make build-submodule
make
```
Actually, you don't need to use a *submodule* at all. If you build and install **blasr_libpp** somewhere, then you can configure **blasr** to use it. But note that everyone installs software differently, and we don't want to be in that business. So support will be limited.

**Comment by ebioman** [comment]
Hello 
Thanks this makes sense and I managed to install the blasr_libpp separately as a module.
What is the correct syntax for passing libcpp information in the  blasr compilation ?

**Comment by ebioman** [comment]
Thanks that already helped a lot, to make the libpp separately.
I there actually a better way to pass all these variables than to define each one separately?

    ./configure.py --no-pbbam HDF5_INC=/software/include/ HDF5_LIB=/software/lib64/ LIBPBIHDF_INC=/software/Development/Libraries/PacBio/blasr_libcpp/20151029/hdf LIBPBDATA_INC=/software/Development/Libraries/PacBio/blasr_libcpp/20151029/pbdata LIBPBDATA_LIB=/software/Development/Libraries/PacBio/blasr_libcpp/20151029/pbdata LIBBLASR_INC=/software/Development/Libraries/PacBio/blasr_libcpp/20151029/alignment LIBBLASR_LIB=/software/Development/Libraries/PacBio/blasr_libcpp/20151029/alignment LIBPBIHDF_LIB=/software/Development/Libraries/PacBio/blasr_libcpp/20151029/hdf 

But unfortunately it fails later:

    make --debug=b -j4 all

.......

       File `makeutils' does not exist.
      Must remake target `makeutils'.
    make -C utils
    make: relocation error: /software/lib64/libc.so.6: symbol _dl_starting_up, version GLIBC_PRIVATE not defined in file ld-linux-x86-64.so.2 with link time reference
    make: *** [makeutils] Error 127
    make: *** Waiting for unfinished jobs....
    error: Bad exit status from /var/tmp/rpm-tmp.xfr7ve (%build)
        Bad exit status from /var/tmp/rpm-tmp.xfr7ve (%build)

**Comment by pb-cdunn** [comment]
> GLIBC_PRIVATE

You've got two versions installed on your system of glibc, and maybe of ld. I suggest that you google this. It will be hard to help you remotely... Actually, this might be caused by over-writing your LD_LIBRARY_PATH in `utils/makefile`, as I suspect that your environment controls which version of glibc you use. I thought the latest code (8cc86216aec97142959070db336a015e336d7fb7) addressed that by appending to that env-var instead of over-writing it.

> I there actually a better way to pass all these variables than to define each one separately?

Not yet, though I have something on a private branch which uses a "PREFIX" directory. I suggest putting your "configure" line in a bash script so that you can repeat it if necessary. Or just keep a copy of `defines.mk`, which you are free to edit if that helps.

**Comment by ebioman** [comment]
Thank you very much, indeed removing the LD_LIBRARY_PATH re-definition and building it dynamic fixed the problem. I dont have any issue with the manual definition of all paths as I am generating SPEC files for RPMs. It would be handy though to define all of them together.
I ran now in an interesting problem though, as the compilation succeeded (as well for all utils) as proposed in travis.sh, I have trouble with a libcpp library afterwards.
If I execute e.g. blasr or sawriter it is complaining  :

     blasr
    blasr: error while loading shared libraries: libpbihdf.so: cannot open shared object file: No such file or directory

This is odd as the compilation worked correctly. Is there a way to check again in which path he is looking or any other suggestions ?
cheers

**Comment by pb-cdunn** [comment]
I'm glad you were able to solve that.

I guess you have `LD_RUN_PATH` in your shell, another installation of blasr_libcpp somewhere. Un-defining `LD_RUN_PATH` would work too, I think.

**Comment by ebioman** [comment]
No the problem is that I had to make a rpm for the blasr_libcpp first which then was deployed on the cluster. Next building the blasr package this was done in a mock-environment which saw the library for the building but not afterwards as they were independent. But it worked in the end, the most important thing ;)

**Comment by pb-cdunn** [comment]
If you don't want to specify all the paths (or if they are all really the same path), run `configure.py` without those paths. Then,

    make INCDIRS='path1 path2 ...' LIBDIRS='path1 path2 ...'

See rules.mk. I *think* LDLIBS will be correct already.

blasr_libcpp/config.py has some if-statements based on inputs, so you might have to provide some phony inputs. And we might need to add `override` for some variables. But the basic idea should work.

If you would rather just set `CPPFLAGS` and `LDFLAGS` yourself, that should work too.
