### ISSUE TITLE
make build-submodule error

### ISSUE THREAD

**Issue by alexmsalmeida** [PacificBiosciences/blasr#155]
Hello,

I am trying to install blasr and when I get to the installation of the libcpp libraries with "make build-submodule" it tries to copy the libconfig.h file without a target directory, causing an error.
```
make build-submodule
/Applications/Xcode.app/Contents/Developer/usr/bin/make -C libcpp
/Applications/Xcode.app/Contents/Developer/usr/bin/make libpbdata
/Applications/Xcode.app/Contents/Developer/usr/bin/make -C /Users/alex/Applications/blasr/libcpp//pbdata libconfig.h
cp -af  libconfig.h
usage: cp [-R [-H | -L | -P]] [-fi | -n] [-apvX] source_file target_file
       cp [-R [-H | -L | -P]] [-fi | -n] [-apvX] source_file ... target_directory
make[3]: *** [libconfig.h] Error 64
make[2]: *** [libpbdata] Error 2
make[1]: *** [all] Error 2
make: *** [build-submodule] Error 2
```
I am trying to install blasr on mac osx. My git is version 2.4.9 (Apple Git-60).

If you have any suggestions to solve this issue, I would really appreciate it. Thanks in advance.

Alex

**Comment by pb-cdunn** [comment]
You never ran `make configure-submodule`, which would be run by `make init-submodule`.

The generated file `libcpp/defines.mk` should include a definition for `LIBCONFIG_H`.

I'm told that our README is a bit out-of-date. I'll update that today.
