### ISSUE TITLE
duplicate symbols after make build-module

### ISSUE THREAD

**Issue by alexmsalmeida** [PacificBiosciences/blasr#156]
Hello,

Thanks for helping me solve my previous issue, but now following the updated install guidelines I am getting a duplicate issue in 91 instances:

> ./configure.py --shared --sub --no-pbbam HDF5_INCLUDE=/usr/local/hdf5/include/ HDF5_LIB=/usr/local/hdf5/lib/
> make configure-submodule
> make build-submodule
...
duplicate symbol QualityValueVector<unsigned char>::ToString() in:
    AfgBasWriter.shared.o
    SMRTReadUtils.shared.o
duplicate symbol QualityValueVector<unsigned char>::Length() in:
    AfgBasWriter.shared.o
    SMRTReadUtils.shared.o
ld: 91 duplicate symbols for architecture x86_64

Do you know what might be causing this issue? I am running on OSX 10.10.5, gcc version 4.9.2 and git 2.6.2. Thanks a lot in advance.

Best,
Alex

**Comment by pb-cdunn** [comment]
That's odd. `QualityValueVector` is a template, but your error message does not show it.

This could occur if a template specialization is not marked `inline`, but I see no template specializations for this template.

Try cleaning (`make cleanall` or cd into libcpp and clean) and rebuilding. If that doesn't work, try the latest **blasr_libcpp** (`f43a110`), where a `#include` was removed. Shouldn't make a difference, but maybe.

If this persists, please tell us what SHA1 you have for both **blasr** and **blasr_libcpp**. (Try `git rev-parse HEAD` in each directory.)

**Comment by alexmsalmeida** [comment]
Hello again,

I tried rebuilding and using the newest version of libcpp but the problem still persists.

The SHA1 are:

blasr: b175ece2185516eea329d853f0b78a3f1f66f076
blasr_libcpp: f43a110a47cdced1ba5c763c1db43817a0c9c379

**Comment by pb-cdunn** [comment]
Remove and rebuild these 2 files:
* `AfgBasWriter.shared.o`
* `SMRTReadUtils.shared.o`

But when you rebuild, add `-E`. You'll have the output of the preprocessor. Rename those to something like `*.i` (to avoid problems with vim, etc.) and search for `QualityValueVector`. You might discover the problem yourself.

Then, post the `*.i` into GitHub "gists". (Search the web.) And post links here.

But I'm not sure that we'll have time to help you track this down. (You might need to examine symbols in various compilation units and libraries.) I recommend switching to Clang++, strictly via Xcode. Post `g++ --version`.

**Comment by alexmsalmeida** [comment]
Thanks for the suggestion. You were right, switching back to clang solved the issue. I was able to successfully build everything now.

Thanks again for the help.

Alex

**Comment by pb-cdunn** [comment]
You're welcome. But I'm afraid that another user may encounter this. Possibly a compiler bug.
