### ISSUE TITLE
Blasr failed to make because of the 'H5Cpp.h' errors

### ISSUE THREAD

**Issue by meibinbin** [PacificBiosciences/blasr#157]
I have installed the hdf5 1.8.12,why did it also go wrong when I run 'make blasr'?
wubinbin@Biology:~/ToolKits/blasr$ make blasr
g++ -O3 -g -std=c++0x -pedantic -Wall -Wuninitialized -Wno-div-by-zero -MMD -MP -w -fpermissive -fno-builtin-malloc -fno-builtin-calloc -fno-builtin-realloc -fno-builtin-free -fno-omit-frame-pointer  -I/home/wubinbin/ToolKits/blasr//include -I/home/wubinbin/ToolKits/blasr/libcpp/alignment -I/home/wubinbin/ToolKits/blasr/libcpp/pbdata -I/home/wubinbin/ToolKits/blasr/libcpp/hdf -I/home/wubinbin/ToolKits/hdf5-1.8.12/hdf5/include  -c -o Blasr.o Blasr.cpp
In file included from /home/wubinbin/ToolKits/blasr/libcpp/hdf/HDFBasReader.hpp:17:0,
                 from /home/wubinbin/ToolKits/blasr/libcpp/alignment/files/ReaderAgglomerate.hpp:16,
                 from iblasr/BlasrHeaders.h:76,
                 from iblasr/BlasrMiscs.hpp:4,
                 from Blasr.cpp:3:
/home/wubinbin/ToolKits/blasr/libcpp/hdf/HDFArray.hpp:7:19: fatal error: H5Cpp.h: No such file or directory
compilation terminated.
make: *** [Blasr.o] Error 1

**Comment by pb-cdunn** [comment]
You might need to re-install HDF5 [with `--enable-cxx`](https://github.com/PacificBiosciences/blasr/issues/87#issuecomment-128489603). That's probably why it's missing from `/home/wubinbin/ToolKits/hdf5-1.8.12/hdf5/include`. If that doesn't work, try a [more recent version](https://www.hdfgroup.org/ftp/HDF5/releases/). After that, search the web.
