### ISSUE TITLE
blast installation problem 

### ISSUE THREAD

**Issue by qihualiang** [PacificBiosciences/blasr#166]
I followed the steps of blasr installation on https://github.com/PacificBiosciences/blasr/blob/master/README.INSTALL.md

During the step of "Build", I think I finished "make build-submodule" successfully. But of the command "make blasr", I got the following error message.
collect2: error: ld returned 1 exit status

This error message usually occurs when there are unresolved symbols? How could I fix this?

**Comment by pb-cdunn** [comment]
Not nearly enough information.

**Comment by galaxy001** [comment]
````
blasr/libcpp/hdf/libpbihdf.so: undefined reference to `H5::H5Location::iterateAttrs(void (*)(H5::H5Location&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, void*), unsigned int*, void*)'
````

**Comment by pb-cdunn** [comment]
That is typically a result of lacking C++ when you install HDF5 (or of using a different HDF5 installation than you think you are using). You can search the issue archives or wiki for details. (You can find the string `H5Location`, which is typically the namespace of the first undefined reference.)
