### ISSUE TITLE
Where is libconfig.h?

### ISSUE THREAD

**Issue by billzt** [PacificBiosciences/blasr#172]
When I install blasr, running `make blasr`, it causes error:

`iblasr/BlasrHeaders.h:22:23: warning: libconfig.h: No such file`

And also a large amount of errors.

On CentOS 6, gcc 4.4.

**Comment by pb-cdunn** [comment]
What did you use for `configure.py`?

**Comment by billzt** [comment]
`./configure.py --shared --sub --no-pbbam HDF5_INCLUDE=/public/home/zhutao/bin/hdf5/include/ HDF5_LIB=/public/home/zhutao/bin/hdf5/lib/`

I sware HDF5_INCLUDE and HDF5_LIB are correct

**Comment by pb-cdunn** [comment]
Did you run `make build-submodule`? That should generate `libconfig.h`.

**Comment by billzt** [comment]
If I run `make build-submodule`, It calls error:
`cc1plus: Error: Unrecognized parameter: “-std=c++11”`

In fact, as blasr is used by many software, I eagerly wished a pre-compiled binary of blasr uploaded on the repository.

**Comment by pb-cdunn** [comment]
I guess you don't have `gcc` in your PATH.

**Comment by billzt** [comment]
No, gcc is in my PATH
`/usr/bin/gcc`

**Comment by pb-cdunn** [comment]
What version? It might be just too old. We're using 4.8.2. You need at least ...:
* https://github.com/PacificBiosciences/blasr/wiki/Blasr-Installation-Qs-&-As#what-is-the-minimum-compiler-version

**Comment by billzt** [comment]
OMG！My gcc is 4.4.7!

**Comment by billzt** [comment]
I've used devtoolset-3-toolchain to solve the problem
