### ISSUE TITLE
cannot install blasr

### ISSUE THREAD

**Issue by esrice** [PacificBiosciences/blasr#190]
Installed HDF5 and ran the following commands, as in the README:

`
./configure.py --shared --sub --no-pbbam HDF5_INCLUDE=~/software/hdf5/include/ HDF5_LIB=~/software/hdf5/lib/
make blasr
`

and received the following error:
`
In file included from iblasr/BlasrMiscs.hpp:4:0,
                 from Blasr.cpp:3:
iblasr/BlasrHeaders.h:24:23: fatal error: libconfig.h: No such file or directory
compilation terminated.
`

**Comment by samfux84** [comment]
How did you solve this problem ?
