### ISSUE TITLE
Tried to install Blasr error showing cannot find -lblasr

### ISSUE THREAD

**Issue by athulmenon** [PacificBiosciences/blasr#195]
I tried to install the blasr  as per the instructions.

Still this error pops up after 

`./configure.py --shared --sub --no-pbbam`
`export HDF5_INC=/home/gba4/Documents/programs/hdf5-1.8.12-linux-x86_64-shared/include HDF5_LIB=/home/gba4/Documents/programs/hdf5-1.8.12-linux-x86_64-shared/lib`
`make blasr`

The error is like 

`g++ -o blasr -O3 -g -std=c++0x -pedantic -Wall -Wextra -Wno-div-by-zero -Wno-overloaded-virtual -MMD -MP -fno-builtin-malloc -fno-builtin-calloc -fno-builtin-realloc -fno-builtin-free -fno-omit-frame-pointer  -I/home/gba4/Documents/programs/blasr/libcpp/alignment -I/home/gba4/Documents/programs/blasr/libcpp/hdf -I/home/gba4/Documents/programs/blasr/libcpp/pbdata -isystem/home/gba4/Documents/programs/blasr/libcpp/hdf/hdf5-1.8.12-headers/src -MF"blasr.d" Blasr.o -L/home/gba4/Documents/programs/blasr/libcpp/alignment -L/home/gba4/Documents/programs/blasr/libcpp/hdf -L/home/gba4/Documents/programs/blasr/libcpp/pbdata -L/home/gba4/Documents/programs/hdf5-1.8.12-linux-x86_64-shared/lib -lpbihdf -lblasr -lpbihdf -lpbdata  -lhdf5_cpp -lhdf5   -lz -lrt -lpthread -ldl
/usr/bin/ld: cannot find -lblasr
collect2: error: ld returned 1 exit status
make: *** [blasr] Error 1
`

Am I doing anything wrong. Thanks in advance!

OS : ubuntu 14.04

Athul

**Comment by pb-cdunn** [comment]
make build-submodule
    make blasr

You have to run [*both* those commands](https://github.com/PacificBiosciences/blasr/blob/master/README.INSTALL.md#build).

**Comment by athulmenon** [comment]
Dear pb-cdunn,
Actually I tied that also, I am attaching you the error when i did..

`make build-submodule`

The error was ...

`make -C libcpp
make[1]: Entering directory `/home/gba4/Documents/programs/blasr/libcpp'
make libpbdata
make[2]: Entering directory `/home/gba4/Documents/programs/blasr/libcpp'
make -C /home/gba4/Documents/programs/blasr/libcpp//pbdata libconfig.h
make[3]: Entering directory `/home/gba4/Documents/programs/blasr/libcpp/pbdata'
make[3]: `libconfig.h' is up to date.
make[3]: Leaving directory `/home/gba4/Documents/programs/blasr/libcpp/pbdata'
make -C /home/gba4/Documents/programs/blasr/libcpp//pbdata all
make[3]: Entering directory `/home/gba4/Documents/programs/blasr/libcpp/pbdata'
make[3]: Nothing to be done for `all'.
make[3]: Leaving directory `/home/gba4/Documents/programs/blasr/libcpp/pbdata'
make[2]: Leaving directory `/home/gba4/Documents/programs/blasr/libcpp'
make libpbihdf
make[2]: Entering directory `/home/gba4/Documents/programs/blasr/libcpp'
make -C /home/gba4/Documents/programs/blasr/libcpp//hdf all
make[3]: Entering directory `/home/gba4/Documents/programs/blasr/libcpp/hdf'
make[3]: Nothing to be done for `all'.
make[3]: Leaving directory `/home/gba4/Documents/programs/blasr/libcpp/hdf'
make[2]: Leaving directory `/home/gba4/Documents/programs/blasr/libcpp'
make libblasr
make[2]: Entering directory `/home/gba4/Documents/programs/blasr/libcpp'
make -C /home/gba4/Documents/programs/blasr/libcpp//alignment all
make[3]: Entering directory `/home/gba4/Documents/programs/blasr/libcpp/alignment'
g++ -std=c++11 -pedantic -Wno-long-long -Wall -Wextra -Wno-overloaded-virtual   -isystem /home/gba4/Documents/programs/blasr/libcpp/hdf/hdf5-1.8.12-headers/src -c files/ReaderAgglomerate.cpp -o ReaderAgglomerate.o
In file included from files/../../hdf/HDFData.hpp:7:0,
                 from files/../../hdf/HDFArray.hpp:10,
                 from files/../../hdf/HDFBasReader.hpp:18,
                 from files/ReaderAgglomerate.hpp:14,
                 from files/ReaderAgglomerate.cpp:1:
files/../../hdf/HDFGroup.hpp:9:24: fatal error: H5Location.h: No such file or directory
 #include <H5Location.h>
                        ^
compilation terminated.
make[3]: *** [ReaderAgglomerate.o] Error 1
make[3]: Leaving directory `/home/gba4/Documents/programs/blasr/libcpp/alignment'
make[2]: *** [libblasr] Error 2
make[2]: Leaving directory `/home/gba4/Documents/programs/blasr/libcpp'
make[1]: *** [all] Error 2
make[1]: Leaving directory `/home/gba4/Documents/programs/blasr/libcpp'
make: *** [build-submodule] Error 2`


After that if i try..


`make blasr`


Error comes like this....

`g++ -o blasr -O3 -g -std=c++0x -pedantic -Wall -Wextra -Wno-div-by-zero -Wno-overloaded-virtual -MMD -MP -fno-builtin-malloc -fno-builtin-calloc -fno-builtin-realloc -fno-builtin-free -fno-omit-frame-pointer  -I/home/gba4/Documents/programs/blasr/libcpp/alignment -I/home/gba4/Documents/programs/blasr/libcpp/hdf -I/home/gba4/Documents/programs/blasr/libcpp/pbdata -isystem/home/gba4/Documents/programs/blasr/libcpp/hdf/hdf5-1.8.12-headers/src -MF"blasr.d" Blasr.o -L/home/gba4/Documents/programs/blasr/libcpp/alignment -L/home/gba4/Documents/programs/blasr/libcpp/hdf -L/home/gba4/Documents/programs/blasr/libcpp/pbdata -L/home/gba4/Documents/programs/hdf5-1.8.12-linux-x86_64-shared/lib -lpbihdf -lblasr -lpbihdf -lpbdata  -lhdf5_cpp -lhdf5   -lz -lrt -lpthread -ldl
/usr/bin/ld: cannot find -lblasr
collect2: error: ld returned 1 exit status
make: *** [blasr] Error 1
`


Thank you for your kind reply...

Looking forward..

**Comment by pb-cdunn** [comment]
Gotta run tonight. But you can search the Issues and the wiki for the `H5Location.h` problem.

**Comment by athulmenon** [comment]
Ok I will let you know.

**Comment by vrainish-pacbio** [comment]
Hi Athul ,

It has been nearly a month since the last comment. If your problem still persist,
please follow recently added page on wiki "step by step blasr installation example".

It will ensure you have most updated blasr/libraries and clean hdf5
Perform it in separate directory and see if your blasr is built successfully.
