### ISSUE TITLE
make issue

### ISSUE THREAD

**Issue by rhenley** [PacificBiosciences/blasr#197]
Hello, I'm receiving the following error message when I attempt to make blasr. Any idea what is causing this?

ld: symbol(s) not found for architecture x86_64
collect2: error: ld returned 1 exit status

**Comment by pb-cdunn** [comment]
You need to show a lot more than that. Please include the full command-line for linking, in addition to the exact command you used to run `configure.py`. That's very important. And it would also help to see your `defines.mk`.

**Comment by vrainish-pacbio** [comment]
Please, follow step by step installation example in wiki to ensure you have most recent version of blasr and see if the problem disappeared. If not, please provide more details ( versions of Blasr, gcc, OS )

**Comment by vrainish-pacbio** [comment]
I assume the problem has been solved by cloning/building the most recent version of blasr as described in wiki
If not, please, reopen it with more details : gcc version ("g++ --version" output ) and OS
