### ISSUE TITLE
blasr occupied so much memory

### ISSUE THREAD

**Issue by starfish001** [PacificBiosciences/blasr#206]
Why BLASR occupied more and more memory when running?
The more reads number,the more memory it need.  Is there some memory didn't reclaimed after finish aligning one reads?

**Comment by starfish001** [comment]
version: blasr   1.3.1.142244

**Comment by vrainish-pacbio** [comment]
Hi,

You might be using a very old version of Blasr.
Please, clone and build current version ( follow instructions in README.INSTALL.md , also wiki has a detailed step by step example of blasr from scratch install ).

Then, rerun your job.
If the problem persist or in case of any other issues/difficulties, please let me know, so I can try to help.

Regards, Vladimir

P.S. Don't hesitate to ask any questions

**Comment by vrainish-pacbio** [comment]
Hi ,

You might using an old version of blasr.
Please, clone and build current version ( there is a step by step example of from scratch Blasr install on Blast wikipage in github).

Then, try to rerun your job.

Please, let me know if the memory problem persists or if you have any other issues/difficulties,
so I can try to help.

Regards, Vladimir

________________________________________

**Comment by starfish001** [comment]
Thank you so much. 
You are right. RAM consumption become controllable when I run my job with blasr5.0.
Best wish to you.

**Comment by vrainish-pacbio** [comment]
Hi Starfish001,

Thanks a lot for the confirmation, it's great to know the problem has been solved. 

Blasr is under constant development, so, in case of  any issues in the future, first try to update your environment ( even full cloning/rebuilding from scratch takes less then 15 minutes ).
Based on the version number you've provided, your executable was more then a year old (at least)
