### ISSUE TITLE
Assertion error in running SamtoH5

### ISSUE THREAD

**Issue by sarahbuzz** [PacificBiosciences/blasr#209]
Hello,

I am attempting to run SamtoH5 outside of BLASR on a SAM file; however, I'm encountering the following error:

`samtoh5: SamToCmpH5.cpp:148: int main(int, char**): Assertion 'references.size() == alignmentSet.references.size()' failed.`

What could be going wrong?

Running on CentOS on SMRTAnalysis v2.3. The SMRT pipe jobs seem to be running fine but when we call SamtoH5 manually on a SAM file generated from BLASR, I get the above error.

Thank you for your help!

Sarah

**Comment by vrainish-pacbio** [comment]
Hi Sarah !

Which Blasr version are you using to generate SAM file ?
If you have a stand-alone Blasr installed , please, issue  

./blasr  -version 

to find out 

Vladimir

**Comment by vrainish-pacbio** [comment]
Hi Sarah ,

Can you run the current version of Blasr to generate SAM files and see if problem persist ?
You can follow Blasr wiki 

https://github.com/PacificBiosciences/blasr/wiki/step-by-step-blasr-installation-example

to clone and build Blasr in a separate directory

**Comment by sarahbuzz** [comment]
Hi Vladimir,

Thank you for your recommendation. I successfully installed BLASR
(v5.0.a806190) and ran samtoh5 after running make makeutils. After running
samtoh5 on an existing SAM file (generated on a previous version of BLASR),
I get a segmentation fault. However, I successfully ran samtoh5 with no
errors after I regenerated the alignment with the new BLASR (v5.0.a806190).

I attempted to run the tests (make cramfast) but they fail because the test
files don't exist. I'm not too comfortable running a snapshot, is this
revision as accurate as a stable release?

Thank you for your help,

Sarah

On Tue, Mar 29, 2016 at 12:24 PM, Vladimir Rainish <notifications@github.com

**Comment by vrainish-pacbio** [comment]
Hi Sarah ,

Thanks a lot for your feedback. New features and bug fixes are being constantly added to Blasr
(Blasr you had used might be a few month old)
The current version you've cloned and installed is fine to operate (as you can see your problem got solved using a new version). 

I am going to check the "make cramfast" problem and update the comment.

Regards, Vladimir

**Comment by ylipacbio** [comment]
Closing inactive issues.  

SAMTOH5 should have been deprecated. Please use [PacBio BAM receipts](https://github.com/PacificBiosciences/PacBioFileFormats/wiki/BAM-recipes) for processing both RSII and Sequel data (e.g., resequencing, making alignments, calling consensus and etc).
