### ISSUE TITLE
@RG line missing SM tag

### ISSUE THREAD

**Issue by dyermd** [PacificBiosciences/blasr#212]
This was present in the older version of Blasr, but the new version does not include the SM tag which can cause problems with some downstream tools.

**Comment by vrainish-pacbio** [comment]
From BAM/SAM spec

@RG SM   Sample. Use pool name where a pool is being sequenced

Hi ,

I'll check why it disappeared.
Meanwhile, Do you have more specific info/examples which tolls might be affected and nature of the problems (just warnings or crushes, wrong results etc)

**Comment by dyermd** [comment]
I know picard dies, haven't tested others.

```
Exception in thread "main" htsjdk.samtools.SAMFormatException: Error parsing SAM header. @RG line missing SM tag. Line:
```

**Comment by vrainish-pacbio** [comment]
Thanks for quick reply. 
I'll check and now there is at least one test case.

**Comment by vrainish-pacbio** [comment]
Regarding @RG:SM tag reqs :  It looks like it's not a mandatory one, so that it can be omitted and 
Picard shouldn't die because  its absence. 
(IMHO it shouldn't die exit gracefully even if a manadatory flag is absent)

**Comment by vrainish-pacbio** [comment]
It might be a reasonable thing to file a bug in Picard.
