### ISSUE TITLE
blasr terminate called after throwing an instance of 'H5::PropListIException'

### ISSUE THREAD

**Issue by sarbashis** [PacificBiosciences/blasr#214]
Hi,
     I am facing error while executing blasr. The error is "terminate called after throwing an instance of 'H5::PropListIException'". My installation details are as follow.

system : ubuntu: 14.04
blasr: clone from github
hdf5: hdf5-1.8.16 (compile from source)
          command used for compilation: ./configure --prefix=/usr/local/hdf5 --enable-cxx
          make
           make check
          make install
I also compile libcpp from the github 
blasr compilation: ./configure.py --shared --sub --no-pbbam HDF5_INCLUDE=/usr/local/hdf5/include/ HDF5_LIB=/usr/local/hdf5/lib/

compilation is done successfully. I have used the same g++ version for compilation of hdf5 and blasr .

Any help will be very appreciated.

**Comment by vrainish-pacbio** [comment]
Hi ,

Can you please, run 

blasr -version 

and put output here.

Regards, Vladimir

**Comment by sarbashis** [comment]
Hi,
      Thanks for the quick response. Output is same.
./blasr 
terminate called after throwing an instance of 'H5::PropListIException'
Aborted (core dumped)
Regards
Sarba

**Comment by vrainish-pacbio** [comment]
Hi Sarba ,

You might have problems with installation of blasr and/or hdf5.

Please, follow "step by step blasr install from scratch" on wiki page, including a step which brings HDF5 ( please, do it in a separate directory ). The whole process takes about 10-15 min.

https://github.com/PacificBiosciences/blasr/wiki/step-by-step-blasr-installation-example

That will ensure you have the most recent version of blasr and clean hdf5.

Make sure you can run  

blasr   -version

(it's the last step there to verify that install was successful)

and then try to run your job and and see if the problem you encountered persist

**Comment by sarbashis** [comment]
Thanks. It is working after following the link.

Regards
Sarba

**Comment by vrainish-pacbio** [comment]
Hi Sarba ,

Thanks a lot for the notification, I am happy you probel has been solved.
In the future, in case of running into the problems, please, ensure your clone of blasr is current.
