### ISSUE TITLE
Issue with HDF5 files with mac installation of blasr

### ISSUE THREAD

**Issue by cwarden45** [PacificBiosciences/blasr#217]
Hi,

I am trying to follow the installation instructions provided here:

https://github.com/PacificBiosciences/blasr/wiki/Step-by-step-blasr-installation-example

When I run the following command:

    make build-submodule

I get the following error messages:

    In file included from ./HDFGroup.hpp:9:
    /usr/local/include/H5Location.h:29:16: error: typedef redefinition with
      different types ('void (*)(H5::H5Location &, const std::string, void *)'
      vs 'void (*)(H5::H5Object &, const std::string, void *)')
    typedef void (*attr_operator_t)( H5Location& loc/*in*/,
                   ^
    /opt/blasr_install/hdf5/hdf5-1.8.7-mac-intel-x86_64-shared/include/H5Object.h:34:16: note: 
      previous definition is here
     typedef void (*attr_operator_t)( H5Object& loc/*in*/,
                    ^
     In file included from BufferedHDF2DArray.cpp:1:
     In file included from ./BufferedHDF2DArray.hpp:12:
     In file included from ./HDFData.hpp:7:
     In file included from ./HDFGroup.hpp:9:
     /usr/local/include/H5Location.h:33:7: error: redefinition of 'UserData4Aiterate'
     class UserData4Aiterate { // user data for attribute iteration
           ^
     /opt/blasr_install/hdf5/hdf5-1.8.7-mac-intel-x86_64-shared/include/H5Object.h:38:7: note: 
           previous definition is here
    class UserData4Aiterate { // user data for attribute iteration
          ^
     2 errors generated.

I had to deviate from the provided steps as follows:

1) git clone didn't automatically download the libcpp files, so I downloaded the following files and moved them to the libcpp folder: https://github.com/PacificBiosciences/blasr_libcpp

2) The HDF5 files in the instructions were for Linux, so I downloaded the mac files from this link: https://www.hdfgroup.org/ftp/HDF5/releases/hdf5-1.8.7/obtain5187.html and changed used the following configuration command:

     ./configure.py --shared --sub HDF5_INCLUDE=/opt/blasr_install/hdf5/hdf5-1.8.7-mac-intel-x86_64-shared/include/ HDF5_LIB=/opt/blasr_install/hdf5/hdf5-1.8.7-mac-intel-x86_64-shared/lib

Can you please help me troubleshoot this issue?

Thanks,
Charles

**Comment by pb-cdunn** [comment]
hdf5-1.8.7 is way too old. On a Mac, try `brew install hdf5`.
* http://brew.sh/

I think your **git** is quite old too, so you would need to run `git submodule --init update` as an extra step.

**Comment by cwarden45** [comment]
Thank you very much for your help.

I have updated HDF5 via homebrew to version 1.8.16 and I have updated git to version 2.8.0.  Thus, I am using this command for the configuration step:

     ./configure.py --shared --sub HDF5_INCLUDE=/usr/local/Cellar/hdf5/1.8.16_1/share HDF5_LIB=/usr/local/Cellar/hdf5/1.8.16_1/lib

If the blasr_libcpp workaround isn't sufficient, here is the error message I get when I try to run git clone https://github.com/PacificBiosciences/blasr.git --recursive

     Cloning into 'libcpp'...
     fatal: unable to connect to github.com:
     github.com[0: 192.30.252.128]: errno=Connection refused

     fatal: clone of 'git://github.com/PacificBiosciences/blasr_libcpp.git' into submodule path 'libcpp' failed

Maybe there is some sort of firewall issue.  Anyways, I am not getting any error messages anymore, but it looks like there is some sort of a problem:

     cwarden$ ./blasr 
     dyld: Library not loaded: libpbihdf.dylib
     Referenced from: /opt/blasr_install/blasr/./blasr
     Reason: image not found
     Trace/BPT trap: 5

FYI, here is my 2nd to last command:

     export LD_LIBRARY_PATH=/opt/blasr_install/blasr/libcpp/alignment:/opt/blasr_install/blasr/libcpp/hdf:/opt/blasr_install/blasr/libcpp/pbdata:/usr/local/Cellar/hdf5/1.8.16_1/lib::::

Can you please help me troubleshoot this issue?

**Comment by mhsieh** [comment]
Well I think you need DYLD_LIBRARY_PATH in stead of LD_LIBRARY_PATH , please give it a try.

**Comment by pb-cdunn** [comment]
A proxy can cause problems for the `git://` protocol. [Here](http://stackoverflow.com/a/32080571) is an idea for you.

**Comment by cwarden45** [comment]
Great - using DYLD_LIBRARY_PATH fixed my problem.  Thanks!

**Comment by vrainish-pacbio** [comment]
I've just updated wiki with note about DYLD_LIBRARY_PATH usage , in case of building Blasr on Mac
