### ISSUE TITLE
Compiling bax2bam on mac

### ISSUE THREAD

**Issue by cwarden45** [PacificBiosciences/blasr#218]
Hi,

I have successfully installed blasr and now I would like to use the bax2bam function.

I have tried following the instructions at https://github.com/PacificBiosciences/blasr/pull/176, but I get the following error message:

     CMake Error at CMakeLists.txt:125 (add_subdirectory):
     add_subdirectory given source "../gtest" which is not an existing
      directory.

I also found instructions in the BUILD.txt file, so I followed those instructions to use cmake in the utils/bax2bam/build folder (skipping the 'module load boost' step, since boost in installed for all users on my computer, and specifying the path to gtest).  However, I get the following error message:

     cwarden$ cmake -DGTEST_SRC_DIR=/opt/googletest/ ..
     CMake Error at CMakeLists.txt:69 (add_subdirectory):
     add_subdirectory given source
     "/opt/blasr_install/blasr/utils/bax2bam/../../../../../lib/cpp/pbbam" which
     is not an existing directory.

     -- Boost version: 1.60.0
     -- Found PythonInterp: /usr/local/bin/python (found version "2.7.11") 
     -- Looking for pthread.h
     -- Looking for pthread.h - found
     -- Looking for pthread_create
     -- Looking for pthread_create - found
     -- Found Threads: TRUE  
     -- Configuring incomplete, errors occurred!

I have successfully installed pbbam, so I tried to direct cmake to those files in the build folder:

     cmake -DGTEST_SRC_DIR=/opt/googletest/ -DPacBioBAM_RootDir=/opt/pbbam ..

However, I still get the same error message.

If I run cmake in the bax2bam folder instead of bax2bam/build (without trying to specify any pbbam files), I get the same error message but with the following extra information:

     CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
     Please set them or make sure they are set and tested correctly in the CMake files:
     BLASR_LIBRARIES
         linked by target "bax2bam" in directory /opt/blasr_install/blasr/utils/bax2bam/src
         linked by target "test_bax2bam" in directory /opt/blasr_install/blasr/utils/bax2bam/tests
    PBDATA_LIBRARIES
         linked by target "bax2bam" in directory /opt/blasr_install/blasr/utils/bax2bam/src
         linked by target "test_bax2bam" in directory /opt/blasr_install/blasr/utils/bax2bam/tests
     PBIHDF_LIBRARIES
        linked by target "bax2bam" in directory /opt/blasr_install/blasr/utils/bax2bam/src
        linked by target "test_bax2bam" in directory /opt/blasr_install/blasr/utils/bax2bam/tests

Can you please help me troubleshoot?  For example, if needed, can you please tell me which pbbam files to reference and how to reference them?

Thanks,
Charles

**Comment by cwarden45** [comment]
FYI, I've made the following progress with my troubleshooting:

1) I can get rid of the BLASR_LIBRARIES, PBDATA_LIBRARIES, and PBIHDF_LIBRARIES message with the following modification:

     cmake -DGTEST_SRC_DIR=/opt/googletest -DPBDATA_ROOT_DIR=/opt/blasr_install/blasr/libcpp

2) I can get rid of the pbbam erorr by manually modifying the CMakeLists.txt file:
    set(PacBioBAM_RootDir /opt/pbbam/)

3) I then need to set the htslib path, which I do with the following command:

     cmake -DGTEST_SRC_DIR=/opt/googletest -DPBDATA_ROOT_DIR=/opt/blasr_install/blasr/libcpp -Dhtslib_DIR=/opt/pbccs/_deps/htslib

4) I can then type 'make' and there is an bax2bam executable created in the 'bin' subfolder

5) If I test the executable with real files, I get the following error message:

     dyld: Library not loaded: libblasr.dylib
         Referenced from: /opt/blasr_install/blasr/utils/bax2bam/bin/bax2bam
         Reason: image not found

I've already run the following command, but this doesn't solve my problem:

       export DYLD_LIBRARY_PATH=/opt/blasr_install/blasr/libcpp/alignment:/opt/blasr_install/blasr/libcpp/hdf:/opt/blasr_install/blasr/libcpp/pbdata:/usr/local/Cellar/hdf5/1.8.16_1/lib::::

I'm guessing I need to add something to DYLD_LIBRARY_PATH, but simply adding /opt/blasr_install/blasr/libcpp doesn't work.

Can you please help me troubleshoot?

**Comment by mhsieh** [comment]
Normally we can start from figuring out if your libblasr.dylib exists and if it's in your DYLD_LIBRARY_PATH. Can you tell us where your libblasr.dylib file is?

**Comment by cwarden45** [comment]
Hi - I found a libblasr.dylib file in /opt/blasr_install/blasr/libcpp/alignment folder.  This is my first folder listed in DYLD_LIBRARY_PATH.

**Comment by cwarden45** [comment]
If it helps, I can run /opt/blasr_install/blasr/utils/bax2bam/bax2bam to get the help options, but this is the command that gives the error message:

    /opt/blasr_install/blasr/utils/bax2bam/bax2bam -o /path/to/output.bam /path/to/file.1.bax.h5 /path/to/file.2.bax.h5 /path/to/file.3.bax.h5

**Comment by mhsieh** [comment]
Hi, I am not sure what's going on, but have you by any chance switched hdf5 versions or switched compilers during the build?

**Comment by cwarden45** [comment]
I used homebrew to install hdf5 (as instructed in https://github.com/PacificBiosciences/blasr/issues/217 for blasr installation), but I haven't made any additional changes.

The Cmake/make shouldn't have changed, but I re-compiled blasr (and then bax2bam) to confirm (after running 'make clean')

I also tried only specifying the alignment subfolder (with the libblasr.dylb file), just in case there was some confusion due to having the hdf and hdf5 subfolders in the full DYLD_LIBRARY_PATH (which is what was provided from compiling blasr).

Unfortuantely, I am still getting the same error message.  Please let me know if you need any additional information.

**Comment by mhsieh** [comment]
I suspect there might be a problem with your compiler,  are you using homebrew gcc?

**Comment by cwarden45** [comment]
My default gcc is clang.  I haven't used a non-default setting for building any of the pacbio programs.

If I try compiling blasr with gcc from homebrew (using make CXX=/usr/local/Cellar/gcc49/4.9.3/bin/gcc-4.9), then I get an error message related to Blasr.o (saying ld: symbol(s) not found for architecture x86_64).  I tried this with make alone as well as with 'make build-submodule  CXX=/usr/local/Cellar/gcc49/4.9.3/bin/gcc-4.9'.  Same error message both times.

If I leave the blasr installation alone (confirming that the re-compilation with clang was successful) and use 'make CXX=/usr/local/Cellar/gcc49/4.9.3/bin/gcc-4.9' for only bax2bam, then I get the same error message when running the command (and I don't actually see any error messages when compiling bax2bam...only when I try to run the executable file).

**Comment by cwarden45** [comment]
FYI, the executable can only be made if I run 'make' in the 'bax2bam' folder.  If I move to the "build" folder and run the following command:

      cmake -DGTEST_SRC_DIR=/opt/googletest -DPBDATA_ROOT_DIR=/opt/blasr_install/blasr/libcpp -Dhtslib_DIR=/opt/pbccs/_deps/htslib ..

Then I see the following error message if I run 'make' in the 'build' folder:

     make[2]: ***No rule to make target '/opt/blasr_install/blasr/libcpp/alibnment/libblasr', needed by '../bin/bax2bam'.  Stop
     make[1]: *** [src/CMakeFiles/bax2bam.dir/all] Error 2
     make: *** [all] Error 2

Not sure if this relates to the error message that I see when running the bin/bax2bam executable, if I compile in the 'bax2bam' folder.

**Comment by cwarden45** [comment]
OK!  It looks like I was able to solve the problem by copying the .dylib files into /usr/local/lib.  In other words:

     sudo cp /opt/blasr_install/blasr/libcpp/alignment/libblasr.dylib /usr/local/lib
     sudo cp /opt/blasr_install/blasr/libcpp/hdf/libpbdata.dylib /usr/local/lib
     sudo cp /opt/blasr_install/blasr/libcpp/pbdata/libpbdata.dylib /usr/local/lib

**Comment by mhsieh** [comment]
That's pretty odd that DYLD_LIBRARY_PATH doesn't work as we expected, but as long as it works for you... Otherwise you might want to checkout out our pitchfork project.

**Comment by cwarden45** [comment]
Yeah - I agree that was weird.  Oh, well - bax2bam still seems to be running OK, so that's what matters.  Thanks for your help!

**Comment by cwarden45** [comment]
FYI, I recently had to re-compile my code, and it looks like it is better to use the version of gtest provided in blasr.  So, here is the cmake command that worked with the re-install:

First, manually modify the CMakeLists.txt file:
set(PacBioBAM_RootDir /opt/pbbam/)

Then,

```
cd utils/bax2bam
cmake -DPBDATA_ROOT_DIR=/opt/blasr/libcpp -Dhtslib_DIR=/opt/pbccs/_deps/htslib
make
```

executable file is in utils/bax2bam/bin
