### ISSUE TITLE
Blasr symbol lookup error

### ISSUE THREAD

**Issue by shashidhar22** [PacificBiosciences/blasr#219]
Running blasr with the following command:

```
blasr /data/users/sravishankar9/malaria/pacbio_sprai/all.fofn /data/users/sravishankar9/malaria/pacbio_sprai/result_20160331_114444/CA/9-terminator/asm_CA_01_20160331_155642.scf.fasta -out /tmp/tmpDqe9AW/7WPvGc.sam  -sam  -bestn 10 -minMatch 12  -nproc 2  -minSubreadLength 50 -minAlnLength 50  -minPctSimilarity 70 -minPctAccuracy 70 -hitPolicy randombest  -randomSeed 1
```

Running into the following error:

```
blasr: symbol lookup error: /data/users/sravishankar9/malaria/Toolkit/blasr/libcpp/hdf/libpbihdf.so: undefined symbol: _ZNK2H58CommonFG15getObjnameByIdxB5cxx11Ey
```

Any help resolving this error would be appreciated
Thank you

**Comment by vrainish-pacbio** [comment]
Take a look on 

https://github.com/PacificBiosciences/blasr/issues/114

looks similar ( not sure )

**Comment by shashidhar22** [comment]
I have added the libraries to LD_LIBRARY_PATH, i'm still getting the same error

**Comment by pb-cdunn** [comment]
Try this:

    ldd blasr

I suspect that you are loading a different HDF5 version than you compiled against.

**Comment by shashidhar22** [comment]
It is loading the same version of HDF5 version that I complied against

**Comment by pb-cdunn** [comment]
The missing symbol is `H5::CommonFG::getObjnameByIdx[abi:cxx11](unsigned long long) const`. It's possible that you built HDF5 without C++11, but you've built blasr with.

**Comment by shashidhar22** [comment]
I recompiled HDF5 with C++11, still getting the same error

**Comment by pb-cdunn** [comment]
You will need to search for that symbol in your HDF5 libraries. I would use `nm` on each HDF5 library listed by `ldd`. Probably, the symbol is not there, so next I would search *all* HDF5 libraries that I can find. It's possible that **blasr** is linking with some but not enough HDF5 libraries.

I would also look for `getObjnameByIdx` in HDF5 headers. That might best be done by using `gcc -E` when blasr_libcpp is compiled.

**Comment by shashidhar22** [comment]
Thanks! that helped, recompiling hdf5 worked
