### ISSUE TITLE
problem:"make blasr"

### ISSUE THREAD

**Issue by meibinbin** [PacificBiosciences/blasr#221]
Hello, I'm receiving the following error message when I attempt to make blasr.
```
libcpp/alignment/algorithms/anchoring/FindMaxIntervalImpl.hpp:395:5: note:   template argument deduction/substitution failed:
In file included from iblasr/BlasrAlign.hpp:85:0,
                 from iblasr/BlasrUtilsImpl.hpp:4,
                 from iblasr/BlasrUtils.hpp:162,
                 from Blasr.cpp:4:
iblasr/BlasrAlignImpl.hpp:252:31: note:   candidate expects 16 arguments, 17 provided
                     read.title);
                               ^
make: *** [Blasr.o] Error 1
```
please help me to solve this problem.I am looking forward to your answer as soon as possible.Thanks.

**Comment by vrainish-pacbio** [comment]
Please, follow "step by step blasr installation example" from wiki

https://github.com/PacificBiosciences/blasr/wiki/step-by-step-blasr-installation-example

to ensure you have most updated version of blasr and libraries

If the problem persists, comment here and provide also your gcc and OS version

**Comment by vrainish-pacbio** [comment]
Hi, 
Hopefully ,updating blasr to the most current version has solved the build problem.
Please, confirm so the issue can be closed
