### ISSUE TITLE
blasr not recognizing .bam file input

### ISSUE THREAD

**Issue by cwarden45** [PacificBiosciences/blasr#223]
Hi, 

I get the following error message when I try to run blasr:

     cwarden$ blasr subreads.subsample.bam ref.fa -sam -out test.sam -nproc 2
     [INFO] 2016-04-14T09:25:18 [blasr] started.
     Assertion failed: ("libblasr must be compiled with lib PBBAM to consume bam files." == 0), function MakeRGs, file format/SAMHeaderPrinter.cpp, line 387.
     Abort trap: 6

However, I made sure to exclude the --no-pbbam when configuring my installation (see https://github.com/PacificBiosciences/blasr/issues/217) and I installed pbbam before blasr.  Can you please tell me what I should do to re-compile blasr with pbbam?

Thanks,
Charles

**Comment by cwarden45** [comment]
With some assistance from a few other threads (https://github.com/PacificBiosciences/blasr/issues/225 and https://github.com/PacificBiosciences/pitchfork/issues/221), I re-compiled blasr using pitchfork.  I now get a slightly different error message (it is no longer reporting `Abort trap: 6`):

```
[INFO] 2016-04-21T16:24:31 [blasr] started.
Assertion failed: ("libblasr must be compiled with lib PBBAM to consume bam files." == 0), function MakeRGs, file format/SAMHeaderPrinter.cpp, line 387.
```

This is my command that I am using to run blasr:

`blasr subreads.bam ref.fa -sam -out subreads.blasr.sam -nproc 2`

Can you please help me troubleshoot?

**Comment by mhsieh** [comment]
It seems that the libblasr is built without pbbam, make sure you get rid of the old libblasr.dylib from your system (if possible, the whole system.) and use the libblasr.dylib you built with pitchfork recipes.

**Comment by cwarden45** [comment]
Ok - if I delete the files `libblasr.dylib` (from the 'alignment' subfolder of libcpp / blasr_libcpp), `libpbihdf.dylib` (from the 'hdf' subfolder of libcpp / blasr_libcpp), and `libpbdata.dylib` (from the 'pbdata' subfolder of libcpp / blasr_libcpp) from `/usr/local/lib` (which I copied over from an earlier instillation https://github.com/PacificBiosciences/blasr/issues/217) and re-compile blasr, then I get the following error message:

```
dyld: Library not loaded: libpbihdf.dylib
  Referenced from: /opt/pacbio/bin/blasr
  Reason: image not found
```

I currently have DYLD_LIBRARY_PATH  set to only include /opt/pacbio/lib.  In fact, the weird thing is that the file is actually in /opt/pacbio/lib (and I confirmed it wasn't just a link to a file in another location):

```
-rwxr-xr-x  1 cwarden  wheel  3559980 Apr 25 09:26 libblasr.dylib
-rw-r--r--  1 cwarden  wheel  2471572 Apr 18 13:17 libhdf5.10.dylib
-r--r--r--  1 cwarden  wheel  3876072 Apr 18 13:17 libhdf5.a
lrwxr-xr-x  1 cwarden  wheel       16 Apr 18 13:17 libhdf5.dylib -> libhdf5.10.dylib
-r--r--r--  1 cwarden  wheel     2351 Apr 18 13:17 libhdf5.settings
-rw-r--r--  1 cwarden  wheel   415208 Apr 18 13:17 libhdf5_cpp.11.dylib
-r--r--r--  1 cwarden  wheel   608368 Apr 18 13:17 libhdf5_cpp.a
lrwxr-xr-x  1 cwarden  wheel       20 Apr 18 13:17 libhdf5_cpp.dylib -> libhdf5_cpp.11.dylib
-rw-r--r--  1 cwarden  wheel   116176 Apr 18 13:17 libhdf5_hl.10.dylib
-r--r--r--  1 cwarden  wheel   146768 Apr 18 13:17 libhdf5_hl.a
lrwxr-xr-x  1 cwarden  wheel       19 Apr 18 13:17 libhdf5_hl.dylib -> libhdf5_hl.10.dylib
-rw-r--r--  1 cwarden  wheel    19480 Apr 18 13:17 libhdf5_hl_cpp.11.dylib
-r--r--r--  1 cwarden  wheel     6288 Apr 18 13:17 libhdf5_hl_cpp.a
lrwxr-xr-x  1 cwarden  wheel       23 Apr 18 13:17 libhdf5_hl_cpp.dylib -> libhdf5_hl_cpp.11.dylib
-rwxr-xr-x  1 cwarden  wheel  2538776 Apr 25 09:26 libpbbam.dylib
-rwxr-xr-x  1 cwarden  wheel  1091512 Apr 25 09:26 libpbdata.dylib
-rwxr-xr-x  1 cwarden  wheel  1394032 Apr 25 09:26 libpbihdf.dylib
lrwxr-xr-x  1 cwarden  wheel       12 Jan 20 10:06 libz.1.1.3.dylib -> libz.1.dylib
lrwxr-xr-x  1 cwarden  wheel       12 Jan 20 10:06 libz.1.2.5.dylib -> libz.1.dylib
-rwxr-xr-x  1 cwarden  wheel   177392 Jan 13 18:05 libz.1.dylib
lrwxr-xr-x  1 cwarden  wheel       12 Jan 20 10:06 libz.dylib -> libz.1.dylib
drwxr-xr-x  2 cwarden  wheel       68 Apr 25 09:26 pkgconfig
```

Just to be sure, I ran export DYLD_LIBRARY_PATH=/opt/pacbio/lib right before running blasr.

Can you please help me troubleshoot?

**Comment by mhsieh** [comment]
Hi Charles, if possible please send your `env` output to my email mhsieh aatt pacb.com and I will take a look.

**Comment by mhsieh** [comment]
Your env output looks fine to me. can you share with us the output of these commands?
1. `which blasr`
2. `DYLD_LIBRARY_PATH=/opt/pacbio/lib otool -L /opt/pacbio/bin/blasr`

**Comment by cwarden45** [comment]
No problem:

```
cwarden$ which blasr
/opt/pacbio/bin/blasr
 cwarden$ DYLD_LIBRARY_PATH=/opt/pacbio/lib /usr/bin/otool -L /opt/pacbio/bin/blasr
/opt/pacbio/bin/blasr:
	libpbihdf.dylib (compatibility version 0.0.0, current version 0.0.0)
	libblasr.dylib (compatibility version 0.0.0, current version 0.0.0)
	libpbdata.dylib (compatibility version 0.0.0, current version 0.0.0)
	/opt/pitchfork/workspace/pbbam/lib/libpbbam.dylib (compatibility version 0.0.0, current version 0.0.0)
	/usr/local/opt/hdf5/lib/libhdf5_cpp.11.dylib (compatibility version 12.0.0, current version 12.0.0)
	/usr/local/opt/hdf5/lib/libhdf5.10.dylib (compatibility version 12.0.0, current version 12.0.0)
	/usr/lib/libz.1.dylib (compatibility version 1.0.0, current version 1.2.5)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1226.10.1)
	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 120.1.0)
```

**Comment by mhsieh** [comment]
Interesting, I will do some test regarding this.

**Comment by mhsieh** [comment]
I would probably recommend trashing all related files and redo the pitchfork again, what's happening on your mac confuses me.

**Comment by cwarden45** [comment]
I re-compiled blasr with `make _startover` from pitchfork this morning (which is the one in /opt/pacbio/blasr).  For good measure, I started from scratch again just now and I"m getting the same error message.

For .bam file input, I get the error message described above.

For .fofn input, the alignment will start, but it will get hung up at that step for days (and I know that I can use another version of blasr to align the same reads within an hour).

**Comment by cwarden45** [comment]
Even though I can tell the library files should be recognized in their current location:

```
cwarden$ echo $DYLD_LIBRARY_PATH
/opt/pacbio/lib
```

I copied the relevant files (libpbihdf.dylib, libblasr.dylib, and libpbdata.dylib) to /usr/local/lib, which gets rid of the error message saying the libraries can't be opened.

Now, the alignment is starting.  So, I will report tomorrow whether the alignment is able to complete (solving the problem) or if it is still getting stuck (although this would be progress, since the alignment wouldn't even previously start with the .bam file input)

**Comment by vrainish-pacbio** [comment]
Hi Charles,

Just wondering if you can consider ( as a one-time experiment and if you have it available, to run your job on a Linux box with pitchfork installation, to make sure it's identical to what you have on your mac). I am not suggesting you switch your development environment from mac, but if the same versions of every relevant Pacbio tool run OK on Linux, then there is a double benefits for you : you have your results and it will prove that the reason for the problems is you mac environment

**Comment by vrainish-pacbio** [comment]
Addition : if you don't have a Linux box, consider virtual machine. I don't know if it's installed/installable on your system though.

**Comment by cwarden45** [comment]
Well, blasr is still running, but the long run-time is problem for .bam input as well as .fofn input, so I'll close this ticket.

Long story short, a VM won't work for a local solution in my case.  I've put in a request to have the software installed/updated on a Linux server, but that hasn't happened yet.  Since I fixed the run-time problem at one point, maybe there is still hope to get it working on my mac.

**Comment by cwarden45** [comment]
Also, Mengjuei  sent me a version pre-compiled version of blasr:

1) If I use that version of blasr on the .bam file input I get the following error message:

```
dyld: Library not loaded: /Users/mhsieh/pitchfork/workspace/pbbam/lib/libpbbam.dylib
  Referenced from: /Users/cwarden/Downloads/opt/pacbio/bin/blasr
  Reason: image not found
```

2) If I use that version of blasr on the .fofn file input, the alignment starts running without an error message

**Comment by mhsieh** [comment]
Did you source the setup-env.sh file before running blasr?

**Comment by cwarden45** [comment]
If I do that, I get rid of the error message, but I it looks like the run-time will still be an issue...

**Comment by mhsieh** [comment]
You would need either
1. `bash --init-file <PREFIX>/setup-env.sh` to create a sub-shell, or 
2. `source <PREFIX>/setup-env.sh` to enable it in current bash.

To be able to use pitchfork built product correctly.

For performance concern / production work, you should use blasr under linux environment.

**Comment by mhsieh** [comment]
My recommendation is to launch a linux vagrant box under you mac, do pitchfork under the that vm, you should be able to have better developer's experience out of it because:
1. a vanilla vagrant box of linux is cleaner than many other linux boxes you would have in your organization.
2. by manipulating the vm size, you get a better feel of the resource requirement of your task.

**Comment by cwarden45** [comment]
FYI, it looks like my "long run-time" problem was due to the way that I had ccache installed.  See https://github.com/PacificBiosciences/blasr/issues/232

If I use ccache for pitchfork, but I make sure it isn't actually in my PATH, an alignment with a .bam file input will start.  However, it gives a different error after the alignment is ~40% complete:

```
[INFO] 2016-05-04T09:46:56 [blasr] started.
blasr(4728,0x700000081000) malloc: *** error for object 0x7f82c8502438: incorrect checksum for freed object - object was probably modified after being freed.
*** set a breakpoint in malloc_error_break to debug
```

I have an open ticket for a related issue (see link above), but I wanted to post here to potentially help others with similar problems.
