### ISSUE TITLE
loadPulses attribute ReadType error (mac installation)

### ISSUE THREAD

**Issue by cwarden45** [PacificBiosciences/blasr#230]
I am having trouble running `loadPulses` with the latest version of `samtoh5` (and blasr):

```
loadPulses /path/to/movie.bas.h5 blasr.cmp.h5
[INFO] 2016-04-21T16:32:54 [loadPulses] started.
ERROR. Could not open attribute ReadType
```

If I use the same .cmp.h5 as an input, I get the same error message with an older version of loadPulses installed on a Linux server.

If I create the .cmp.h5 file using the older version of samtoh5 on the Linux server (aligned with an older version of blasr), then the older version of loadPulses works correctly.  I can't use the older version of samtoh5/loadPulses with a newer blasr alignment.  However, I can't use the newer version of samtoh5/loadPulses with the old blasr alignment.

Can you please help me troubleshoot?

**Comment by mhsieh** [comment]
This is the first time that I heard about this use case. I don't think you can fully regenerate cmp.h5 from sam file.

**Comment by cwarden45** [comment]
Sorry - I got confused about how one of my files was created.

It looks like solving my problem with samtoh5 may have caused blasr run-time to considerably increase (see https://github.com/PacificBiosciences/blasr/issues/225).  Being able to test the newest versions of samtoh5/loadPulses with an alignment created using the latest version of blasr is important, so I will close this issue.

If the new blasr alignment is successful and I am still having an issue with loadPulses, then I will re-open the issue.  Otherwise, it looks like it is probably a formatting issue with the old version of blasr.

**Comment by cwarden45** [comment]
FYI, I get the segmentation error if I use samtoh5 with the version of blasr that I compiled on my mac that has a reasonable run-time (so, it looks like solving the samtoh5 and run-time issues are caused by one another).  Since I could originally align a set of 5 subreads, I'll see if I can focus on the run-time issue (and assume an alignment larger number of reads will remain compatible with samtoh5...)

**Comment by cwarden45** [comment]
Yeah - if I re-create the .sam file from scratch, blasr gets stuck in the alignment step (it was running for 4+ days on an alignment that completed within an hour when compiled differently).  For now, I'll focus on the fact that blasr is not accepting .bam files as input (https://github.com/PacificBiosciences/blasr/issues/223), and it hasn't done for for any of the version that I have compiled.  Perhaps that will help me figure out what is going on.
