### ISSUE TITLE
how to compile blasr with pbbam?

### ISSUE THREAD

**Issue by cwarden45** [PacificBiosciences/blasr#232]
Hi,

I am trying to compile blasr with pbbam.  I am basically following the steps provided at https://github.com/PacificBiosciences/blasr/wiki/Step-by-step-blasr-installation-example, with the following modification:

` ./configure.py HDF5_INCLUDE=/usr/local/Cellar/hdf5/1.8.16_1/share HDF5_LIB=/usr/local/Cellar/hdf5/1.8.16_1/lib PBBAM_INCLUDE=/opt/pbbam/include/pbbam PBBAM_LIB=/opt/pbbam/lib`

It seems like I am on the right track because I got an error message when I had a typo in the PBBAM_INCLUDE path (I believe it didn't even look for those files if I left in the "--shared --sub" tags).  However, I can tell that blasr wasn't successfully complied with pbbam for the following reasons:

**1) If I try to use a unaligned .bam file as an input, I get the following error message.**

```
[INFO] 2016-05-03T14:24:17 [blasr] started.
Assertion failed: ("libblasr must be compiled with lib PBBAM to consume bam files." == 0), function MakeRGs, file format/SAMHeaderPrinter.cpp, line 387.
```

**2) If I move the location of the libpbbam.dylib file (with any blasr alignment), I don't get an error message** (I've noticed that I get an error message from libpbdata.dylib if libpbbam.dylib is not in the original location and blasr has been compiled with pbbam).

I've tried compiling blasr with pitchfork (see https://github.com/PacificBiosciences/blasr/issues/223).  While this does seem to use the pbbam code, blasr doesn't actually work (it hangs at the alignment step).  So, I am trying to identify the cause of the problem by compiling all the code step-by-step without pitchfork.

Can you please tell me what commands are necessary to compile blasr with pbbam (without pitchfork)?

Thanks,
Charles

**Comment by vrainish-pacbio** [comment]
Hi Charles ,

The example in "step by step ..." guide is how to build blasr WITHOUT pbbam
(see --no=pbbam flag given to configure.py ) 

./configure.py --shared --sub --no-pbbam

We might add a guide how to build blasr with pbbam.

Meanwhile, why can't you use pitchfork which by default builds blasr with bam support enabled ?

**Comment by cwarden45** [comment]
Yeah - I think that guide would be helpful.

If I use pitchfork, blasr doesn't work (the alignment step never completes, regardless of the input file type).

So, I am trying to identify what is causing the problem.  If I don't compile with pbbam (without pitchfork, using instructions similar to those provided above), then I can successfully run blasr.  So, I am trying to change this step, since that is what has had the most functionality so far.

**Comment by mhsieh** [comment]
I will need the testing data to verify this regarding "pitchfork blasr doesn't work" part.

**Comment by mhsieh** [comment]
Please note that we don't support mac, we can only help when we have time to look at.

**Comment by cwarden45** [comment]
I think part of the problem is having multiple blasr installations.  I've cleaned up as many files as I can find, but I am going back now to confirm that the version of blasr without pbbam does in fact work like it did before.  I shared a subset of data in other message treads, but no body has been able to reproduce the issue on their computer.

It looks like it may have to do with the HDF5 files (since I needed them to get blasr to work before).  I didn't initially specify anything special to pitchfork.  While I have tried using HAVE_HDF5, it is possible this didn't work for other reasons.

Yes - that is fair.  If following a set of instructions to compile blasr with pbbam (without pitchfork) runs without error messages but has the same problem, that is sufficient for this message thread.  I also understand if you can't provide a timely response.  I am also busy with other projects :)

**Comment by mhsieh** [comment]
So I am generally interested in your data, can you send me some tests? Thanks.

**Comment by cwarden45** [comment]
There is some demo data from troubleshoot.zip in this thread: https://github.com/PacificBiosciences/blasr/issues/225

That said, it looks like the version of blasr that I got working in that thread (with respect to the run time-issue - where I said "solves 1/2 of the problem") is no longer working (it has been about an hour).  This is the point where I started to use pitchfork, so I'm going to keep hunting for what has changed on my computer since that point.

However, I think it would still be nice to have compilation instructions for blasr+pbbam, so I'll leave the thread open for now.

**Comment by mhsieh** [comment]
So which one gives you trouble? is it `blasr test.fasta pDmeth.fa` ?
this is my result
```bash
$ /usr/bin/time blasr test.fasta pDmeth.fa
[INFO] 2016-05-03T16:35:15 [blasr] started.
m160407_175515_42284_c100875832550000001823187303261636_s1_X0/10/92_4952/0_4860/0_4788 pDmeth 0 0 -17627 85.5649 465 4970 6975 0 4788 4788 104305
m160407_175515_42284_c100875832550000001823187303261636_s1_X0/44/0_2144/0_2144/0_2095 pDmeth 0 0 -7868 87.3226 3076 4963 6975 0 2095 2095 45069
m160407_175515_42284_c100875832550000001823187303261636_s1_X0/50/0_6867/0_6867/0_4832 pDmeth 0 0 -17266 82.8205 0 4971 6975 0 4832 4832 118835
m160407_175515_42284_c100875832550000001823187303261636_s1_X0/163465/49712_56753/0_7041/0_5010 pDmeth 0 0 -20071 88.1349 0 4969 6975 0 5006 5010 114217
m160407_175515_42284_c100875832550000001823187303261636_s1_X0/163465/56797_58537/0_1740/0_1723 pDmeth 0 0 -7347 91.4882 4977 6664 6975 0 1723 1723 36706
[INFO] 2016-05-03T16:35:15 [blasr] ended.
        0.07 real         0.05 user         0.00 sys
```

**Comment by cwarden45** [comment]
The underlying problem does seem relate to the number of reads being aligned.  I can successfully run `blasr test.fasta pDmeth.fa -sam -out test.sam` (sorry for providing the .sam rather than .fa file), but the issue is that I **currently**  can't align the full dataset (even without compiling with pbbam, which is weird given that I could align the full dataset within an hour when compiling without pbbam, before testing the pitchfork version of blasr)

Currently, if run the full dataset without specifying the output file, I can see the alignment providing results for each read (with or without "-sam"), but the -out file is empty (even after running for an hour).  I will see if `blasr input.fofn ref.fa -sam > temp.sam` can finish aligning.  I'll let you know if that works (if so, that may help with the pbbam compilation problem).

My first issue with pitchfork related to ccache, so I'll also see if removing cache can get my original blasr compilation strategy to work again.  I'll provide an update tomorrow.

Thanks for your help.

**Comment by mhsieh** [comment]
Let's setup a hangout meeting tomorrow to see if I see something that I can fix.

**Comment by cwarden45** [comment]
Ok, sure - I currently don't have anything scheduled tomorrow.  What time
works for you?  I am on pacific time.

**Comment by cwarden45** [comment]
Ok - to give an update:

1) The version of blasr with ccache installed on my computer will finish the alignment if I don't specify an "-out" value.  If I specify that value (with ccache installed), it will hang at the alignment step for days.

2) I uninstalled ccache and re-complied blasr (to try and get the functionality that I had earlier).  This seems to solve the "long run-time error" (meaning, the alignment will finish, even with an "-out" outputfile file specified).

3) However, similar to before, samtoh5 (compiled without pitchfork and without ccache) gives a segmentation error.  So, I reinstalled ccache, but I removed the link from my PATH so  I can use it with pitchfork, if needed, but it affect my other installed programs (like the non-pitchfork version of blasr)

4) If I configure ccache this way, it also looks like it fixes the "long run-time" issue with the pitchfork version of blasr (so, I can use '-out' again).   So, that is good.

5) If I configure ccache this way, I can also start an alignment with an unaligned .bam file input (which now provides a partial alignment in the output file as the alignment runs), but it produces a different error message:

```
[INFO] 2016-05-04T09:46:56 [blasr] started.
blasr(4728,0x700000081000) malloc: *** error for object 0x7f82c8502438: incorrect checksum for freed object - object was probably modified after being freed.
*** set a breakpoint in malloc_error_break to debug
```

6) If I configure ccache this way, samtoh5 is not compatible with the .fofn alignment (even though the alignment does finish now, even with the pitchfork version of blasr)

**Comment by mhsieh** [comment]
ccache shouldn't have any effect on runtime environment, the cause might be something different, but I will help on your pitchfork ccache problem and then look into the `-out` issue.

**Comment by cwarden45** [comment]
Sure - the issue is a little different now, but I'm certainly glad to discuss in more detail after lunch.  Thanks again for your help.

**Comment by cwarden45** [comment]
Also, I am able to finish running blasr on the unaligned .bam files if I run it in a local directory.

Running blasr on network files seems to cause some extra problems, but they are inconsistent (when I tried a second time, I didn't get the malloc eror and instead just couldn't re-direct the alignment output to the output file - so, it went back to something like the "long run-time" error without even using -out).

If blasr consistently works with local files, I suppose that is good enough.

The blasr alignment with the unaligned .bam file gives a segmentation fault with samtoh5, but that should be a separate message thread so I'll close this issue.
