### ISSUE TITLE
bam2bax -version should report more informative versions

### ISSUE THREAD

**Issue by mhsieh** [PacificBiosciences/blasr#237]
1. version of pbbam(?)
2. version of blasr_libcpp
3. version of bam2bax tree

**Comment by vrainish-pacbio** [comment]
Possibly same format as blasr : MajorVersion.MinorVersion.ShortSHA1 ?

**Comment by afif-elghraoui** [comment]
`git describe` would give you nice version strings for any revision if you make tags out of the major.minor versions.
