### ISSUE TITLE
build issue with Intel `icpc` on Centos6

### ISSUE THREAD

**Issue by BenjaminSchwessinger** [PacificBiosciences/blasr#239]
Hi there, 
I am getting the following issue when installing blasr on a cluster. I am following the https://github.com/PacificBiosciences/blasr/wiki/Step-by-step-blasr-installation-example guide. I also checked if all pulls are the most recent version and they were fine.

the command make build-submodule throws the following error.
```
make[3]: Entering directory `/home/800/bxs800/blasr_install/blasr/libcpp/alignment'
icpc -std=c++11 -pedantic -Wno-long-long -Wall -Wextra -Wno-overloaded-virtual   -isystem /home/800/bxs800/blasr_install/hdf5/hdf5-1.8.16-linux-centos6-x86_64-gcc447-shared/include/ -c datastructures/alignment/FilterCriteria.cpp -o FilterCriteria.o
datastructures/alignment/FilterCriteria.cpp(166): warning #1011: missing return statement at end of non-void function "HitPolicy::Apply"
  }
  ^

datastructures/alignment/FilterCriteria.cpp(277): error: more than one instance of overloaded function "std::to_string" matches the argument list:
            function "std::to_string(long long)"
            function "std::to_string(unsigned long long)"
            function "std::to_string(long double)"
            argument types are: (DNALength)
      return std::string("(") + std::to_string(_minAlnLength) + ") " +
                                ^

datastructures/alignment/FilterCriteria.cpp(282): error: more than one instance of overloaded function "std::to_string" matches the argument list:
            function "std::to_string(long long)"
            function "std::to_string(unsigned long long)"
            function "std::to_string(long double)"
            argument types are: (int)
      return std::string("(") + std::to_string(static_cast<int>(_minPctSimilarity)) + ") " +
                                ^

datastructures/alignment/FilterCriteria.cpp(287): error: more than one instance of overloaded function "std::to_string" matches the argument list:
            function "std::to_string(long long)"
            function "std::to_string(unsigned long long)"
            function "std::to_string(long double)"
            argument types are: (int)
      return std::string("(") + std::to_string(static_cast<int>(_minPctAccuracy)) + ") " + 
                                ^

compilation aborted for datastructures/alignment/FilterCriteria.cpp (code 2)
make[3]: *** [FilterCriteria.o] Error 2
make[3]: Leaving directory `/home/800/bxs800/blasr_install/blasr/libcpp/alignment'
make[2]: *** [libblasr] Error 2
make[2]: Leaving directory `/home/800/bxs800/blasr_install/blasr/libcpp'
make[1]: *** [all] Error 2
make[1]: Leaving directory `/home/800/bxs800/blasr_install/blasr/libcpp'
make: *** [build-submodule] Error 2
```

**Comment by pb-cdunn** [comment]
I'll fix the return-statement warning.

For the errors, your compiler seems to be missing the `int` overload of `std::to_string()`:
* http://en.cppreference.com/w/cpp/string/basic_string/to_string

You might have to find a solution yourself and let us know. I'm curious: What version of **icpc** are you using?

**Comment by BenjaminSchwessinger** [comment]
Thanks Chris. I was using the intel-cc/16.0.3.210 as compiler on a national supercomputer. I was asking with the support team and he came up with the following. I was wondering if you have a header file I can amend to include the string_to_string code. This might be worth trying.

///cluster support reply///
I've seen this before, and from what I was able to tell it's because the
code you're building relies on C++11 STL features that just aren't in the
system STL headers on Raijin. Keep in mind that Raijin is running CentOS
6, which uses quite an old version of GCC (and, correspondingly, libc and
libstdc++).

It's worth distinguishing between the C++ language and the C++ STL. While
the Intel compilers are fully C++11-compliant in terms of the language,
they use the system STL headers and libraries and so are only as C++11
compliant as the underlying system installation for the STL.

In particular, the code is calling ::std::to_string with an int argument;
there's no such function in the old STL we have on Raijin, and so it
looks for something compatible. Unfortunately, it finds more than one
that fit equally (with long long, unsigned long long, and long double
arguments), and hence the function call is ambiguous.

You can work around this by explicitly casting it to one of those types.
Then it has an exact match and won't try to find compatible signatures.
I'd recommend "long long" since it matches the signedness of int and must
be at least the same size:

   return std::string("(") + 
     std::to_string(static_cast<long long>(_minAlnLength)) + ") " +

It might get a bit tedius replacing all such occurances in the code.
Alternatively, if there's a header file that gets included everywhere,
you could cheat and define the needed function there (technically,
extending the ::std namespace is undefined, but it should work in this
case):

  #include <string>
  namespace std {
    inline string to_string ( int x ) {
      return to_string(static_cast<long long>(x));
    }
  }

**Comment by pb-cdunn** [comment]
Yes, `long long` is what I was thinking too. Extending STL is tough because that might fail when the `int` function exists already.

Could you find out what version of **gcc** is on Raijin? `gcc --version`.

**Comment by pb-cdunn** [comment]
Yes, `long long` is what I was thinking too. Extending STL is tough because that might fail when the `int` function exists already.

Could you find out what version of **gcc** is on Raijin? `gcc --version`.

**Comment by BenjaminSchwessinger** [comment]
That's the version gcc (GCC) 4.4.7 20120313 (Red Hat 4.4.7-16). I am also talking with someone else here today or Friday who already set it up on this cluster. more soon.

**Comment by mhsieh** [comment]
I can reproduce this on icc 15.0.2 + centos6. now looking to any possible way to get around of this.

**Comment by mhsieh** [comment]
Ben, can you load gcc/4.8.2 environment module as well? It would be nice if they don't conflict each other.

**Comment by mhsieh** [comment]
from https://usersupport.nci.org.au/software/nci_software.php?software=C+and+C%2B%2B&site=ANU&from_site=ANU Raijin doesn't have gcc newer than 4.4.7

**Comment by mhsieh** [comment]
but other google search seems to be indicating that raijin already has gcc/4.9.0

**Comment by BenjaminSchwessinger** [comment]
It is still early in Oz. I will get back to you on this. I tried the installation with gcc (GCC) 4.4.7 with a intel-cc/16.0.3.210 module loaded that could execute the C++11. Yet the underlying libraries (libc and
libstdc++) are not compatible with the blasr set up. I will talk with someone today who might have got the set up right. I will update on how we figured. Thanks for your help!

**Comment by BenjaminSchwessinger** [comment]
I finally go round fixing it. Unloading other compilers and loading the following fixed the problem.
4) gcc/4.9.0             5) intel-cc/16.0.2.181   6) intel-fc/16.0.2.181

All set and ready to go. Thanks for the suggestions.
