### ISSUE TITLE
Issue with --bam option

### ISSUE THREAD

**Issue by gk7279** [PacificBiosciences/blasr#245]
Hi 

When I try to run this command below, it gives me an error saying not a valid option

/path/to/blasr /path/tomy/rawdata/sample.bas.h5 /refs/rat/rn6.fa  --out /output/dir/rat_alignments.bam --nproc 16 --bam

For some reasons, it is not reading the dashes before the bam properly. If I specify ---bam, it calls it --bam. If I do --bam, it calls it -bam. It is missing one dash.

Thanks

**Comment by vrainish-pacbio** [comment]
Hi ,

I'll check it. Meanwhile, can you, please, run blasr --version and post results.
Also, please make sure you have the latest version of blasr installed ( follow step by step blasr installation on wiki )

**Comment by gk7279** [comment]
blasr	 5.2.caebccd

I have followed your wiki page installation instructions.

**Comment by vrainish-pacbio** [comment]
Thanks for the the info, I'll check it and let you know.

**Comment by vrainish-pacbio** [comment]
Hi ,

I can't reproduce your problem. I've cloned/built blasr version , it's the same you are using 5.2.caebccd,
I invoke blasr with exact same flags 

./blasr ... --out out.bam  --nproc 16 --bam 

and it runs OK.

Can you please, attach a complete output after you invoke blasr.

I don't quite understand when you write "If I specify ---bam, it calls it --bam. If I do --bam, it calls it -bam." Does Blasr exit with error , complaining on non-existing option ?

Can you please, attach a complete output after you invoke blasr.

**Comment by gk7279** [comment]
Thank you. That seems not much of a help. 

Coming back to your question regarding the bam option....

When I run

./blasr .... --out out.bam --nproc 16 --bam

It prints an error saying -bam option not found. Here there is only one dash before bam. But the option that we gave to the tool is --bam (two dashes)

**Comment by vrainish-pacbio** [comment]
My apologies, I am going to update blasr wiki page.

What happens is as follows : the step by step installation example builds blasr WITHOUT bam support (pbbam libraries). That's why your blasr doesn't recognize --bam flag.

In order to build blasr with bam support you need to use pitchfork. See the link below.

https://github.com/PacificBiosciences/pitchfork

**Comment by gk7279** [comment]
Thank you. Can you please update the wiki page of blasr on how to do this?

**Comment by vrainish-pacbio** [comment]
Please, follow instructions in the link below, It will build blasr which supports --bam

https://github.com/PacificBiosciences/pitchfork

I've already updated the wiki page of step by step blasr installation example indicating that it build blasr which doesn't support --bam

**Comment by gk7279** [comment]
Hello @vrainish-pacbio - Thank you so much for the pitchfork idea. It just finished and the tool no longer complains about the --bam option.

However the story began now

When I run the same command as above, I see this error

./blasr: /usr/lib64/libstdc++.so.6: version `CXXABI_1.3.8' not found (required by /path/to/pitchfork/bin/../lib/libpbihdf.so)

I understand that libstdc++.so.6 is looking for the CXX libraries. How do I make blasr to use pitchfork installed libstdc++ instead of my global libstdc++ from /usr/lib64.

Please note that I have also tried using the 

bas --init-file /path/to/pitchfork/setup-env.sh

And it doesn't help.

Thank you

**Comment by vrainish-pacbio** [comment]
Hi ,

Good to hear that you've successfully built blasr with bam support using pitchfork.
I've never seen such an error before ( I am using pitchfork exclusively ), so I need to take a look.

Regards, Vladimir

**Comment by mhsieh** [comment]
Hi @gk7279 , what's the compiler are you using? Are you using pre-built software component?

Thanks,
--mj

**Comment by vrainish-pacbio** [comment]
Hi  hk7279 
In the future please follow instructions on wiki page how to report the issue 
We need all the info below as minimum to understand what happens

Please, follow the main wiki page how to report issues in Blasr. 

    Blasr version ( use blasr --version to obtain it )
    Exact and complete Blasr invocation command and its output
    Your OS
    Your compiler version
    Last, but not least, make sure you have the latest version of Blasr ( please, follow step by step blasr installation example in case you have any problems cloning/building it ).
 
If you building blasr using pitchfork, please ensure also youi use most updated pitchfork build

**Comment by gk7279** [comment]
Hi @vrainish-pacbio 

I have used the most recent pitchfork.

a. The command I used was -` ./blasr .... --out out.bam --nproc 16 --bam`

b. I cannot see the version of blasr because of the above error. But it is 5.2.

c. My OS info
`Linux 2.6.32-431.17.1.el6.x86_64 #1 SMP Wed May 7 23:32:49 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux`

d. My compiler
`gcc version 4.4.7 20120313 (Red Hat 4.4.7-16) (GCC)`

**Comment by mhsieh** [comment]
Hi,
First you need to a newer version of gcc, I am not sure why you can pass the gcc version test. Now investigating.

**Comment by mhsieh** [comment]
```
mhsieh@centos66:~/pitchfork$ uname -a
Linux centos66 2.6.32-504.8.1.el6.x86_64 #1 SMP Wed Jan 28 21:11:36 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
mhsieh@mp0311-sge66:~/pitchfork$ gcc --version
gcc (GCC) 4.4.7 20120313 (Red Hat 4.4.7-11)
Copyright (C) 2010 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

mhsieh@centos66:~/pitchfork$ make blasr
make -f mk/init.mk init
make[1]: Entering directory `/home/UNIXHOME/mhsieh/pitchfork'
/home/UNIXHOME/mhsieh/pitchfork/bin/checkSystem
/home/UNIXHOME/mhsieh/pitchfork/bin/checkCC gcc
[ERROR] unexpected program error in /home/UNIXHOME/mhsieh/pitchfork/bin/checkCC
make[1]: *** [sanity] Error 1
make[1]: Leaving directory `/home/UNIXHOME/mhsieh/pitchfork'
make: *** No rule to make target `initialized.o', needed by `ccache'.  Stop.
```

**Comment by gk7279** [comment]
Thank you @mhsieh. I am using a new compiler now.

However, there is another error.

ERROR, could not output alignments in BAM unless input reads are in PacBio BAM or DATASET files.
ERROR, could not output alignments in BAM unless input reads are in PacBio BAM or DATASET files.

I am using the *.bas.h5 file.

I think I should be feeding all the three *.bax.h5 files instead of the bas.h5 file. Am I right?

Please comment. Thanks

**Comment by mhsieh** [comment]
Vladimir to follow up, but I guess you need bax2bam.

**Comment by gk7279** [comment]
I have bax2bam though

**Comment by vrainish-pacbio** [comment]
gk7279, it's not an error per se, there are certain restrictions on input / output file formats combination

Try to convert your input reads to bam format.
Sorry for the inconvenience.

**Comment by gk7279** [comment]
Cant I use the bax files straight?

**Comment by mhsieh** [comment]
If I recall correctly, you probably need to convert bax file to bam file, and use it as the input.

**Comment by gk7279** [comment]
Thank you @mhsieh and @vrainish-pacbio 

I tried bax2bam.

Any idea on how to resolve this one?

ERROR: unsupported sequencing chemistry combination: 
    binding kit:        100236500
    sequencing kit:     001558034
    basecaller version: 2.0.2.0.124543

ERROR: BindingKit, SequencingKit, and ChangeListID are mandatory but unavailable

**Comment by mhsieh** [comment]
Hi, do you have the metadata.xml file?

**Comment by gk7279** [comment]
Yes, I do. But when I feed it through `--xml=/path/to/sample.xml`, It prints the help screen without executing. Any ideas?

Thank you

**Comment by mhsieh** [comment]
You are using --xml wrong. Supposed your bax.h5 files are at /home/gk7279/h5data/MYMOVIE/
Here is how you do it:
1. copy the <moviename>.metadata.xml to /home/gk7279/h5data/
2. `mkdir -p /home/gk7279/bamdata`
3. `cd /home/gk7279/bamdata`
3. `bax2bam /home/gk7279/h5data/MYMOVIE/<moviename>.metadata.xml`

Reference:
1. https://github.com/PacificBiosciences/SMRT-Analysis/wiki/Cannot-import-new-SMRT-Cells
2. https://github.com/PacificBiosciences/blasr/blob/master/utils/bax2bam/tests/bax2bam.t

**Comment by ylipacbio** [comment]
More reference:

* [How to work with RS II data](https://github.com/PacificBiosciences/pbalign/wiki/Mapping-RS-II-reads-(in-movie.bax.h5)-and-calling-consensus-using-pbalign-BLASR-while--sam-option-is-deprecated)
* [How to work with Sequel data](https://github.com/PacificBiosciences/pbalign/wiki/Work-with-sequel-BAM-files-and-datasets.)

**Comment by gk7279** [comment]
Thank you @ylipacbio and @mhsieh 

None of the above tutorials state that I need hdf files. But when I run the bax2bam as mentioned above

I see this error

ERROR, could not open hdf file /home/gk7279/h5data/MYMOVIE/<moviename>.metadata.xml

Thanks

**Comment by gk7279** [comment]
I even placed the mcd.h5 files at the same level as the metadata.xml file and still cant get the script to work.

**Comment by ylipacbio** [comment]
Hi @gk7279,

I have updated command to call 'bax2bam` in mhsieh's last comment.  Would you please try it again. 

Example bax2bam usage:

```
bax2bam movie.1.bax.h5 -o output # which converts movie.1.bax.h5 to output.subreads.bam, output scraps.bam
```
If this problem is not solved, please provide the following info
```
ls /home/gk7279/h5data/MYMOVIE
ls /home/gk7279/h5data/
```
Thanks!

**Comment by gk7279** [comment]
Thank you @ylipacbio 

I tried your suggestion and here is what I get

```
ERROR: unsupported sequencing chemistry combination: 
    binding kit:        100236500
    sequencing kit:     001558034
    basecaller version: 2.0.2.0.124543

ERROR: BindingKit, SequencingKit, and ChangeListID are mandatory but unavailable

```

Outputs

```
ls /home/gk7279/h5data/MYMOVIE
m131116_012914_42152_c100582382550000001823096804281411_s1_p0.1.bax.h5
m131116_012914_42152_c100582382550000001823096804281411_s1_p0.2.bax.h5
m131116_012914_42152_c100582382550000001823096804281411_s1_p0.3.bax.h5
m131116_012914_42152_c100582382550000001823096804281411_s1_p0.bas.h5

ls /home/gk7279/h5data/
MYMOVIE
m131116_012914_42152_c100582382550000001823096804281411_s1_p0.mcd.h5
m131116_012914_42152_c100582382550000001823096804281411_s1_p0.metadata.xml
```

**Comment by gk7279** [comment]
I just realized that I do have subreads.fastq and subreads.fasta along with some log files and csv files.

I also have ccs.fastq and ccs.fasta files. 

But I have three fastq files pertaining to each of the bax.h5 files.

**Comment by mhsieh** [comment]
What polymerase/chemistry was this?

**Comment by mhsieh** [comment]
P4-C2 / 2.0 , which is not supported in new world pbbam.

**Comment by mhsieh** [comment]
So a quick recommendation is to use smrtanalysis 2.3.0.p5

**Comment by gk7279** [comment]
Is there a linux version of smrtanalysis?

I got one from here - http://www.pacb.com/support/software-downloads/

But it say .run 

Any ideas @mhsieh

**Comment by mhsieh** [comment]
It's the linux version. a tarball + installer hiding inside of a bash script.

**Comment by mhsieh** [comment]
Ref:
1. http://www.pacb.com/wp-content/uploads/SMRT-Analysis-Software-Installation-v2-3-0.pdf
2. http://www.pacb.com/wp-content/uploads/SMRT-Analysis-Release-Notes-v2-3-0-p5.pdf
3. https://github.com/mhsieh/SMRTAnalysis_2.3.0_install/blob/master/vagrant-u1404/Vagrantfile

**Comment by mhsieh** [comment]
@gk7279 That being said, we are working on the issue preventing you from using the bax2bam, so if you are willing to wait, we can also solve it from that front.

**Comment by bzvew** [comment]
Can I not use pitchfork and let blasr 5.1 support --bam option? I cannot install pitchfork because of my network issue. I manage to install blasr with much effort but now --sam cannot use then need to reinstall use pitchfork? Why in the install guide to mention how to support bam option directly?

**Comment by ylipacbio** [comment]
@bzvew It depends on which data you are working on. 

If reads are sequel data in PacBio BAM format (e.g., mxxxxxxxxxx.*.subreads.bam), BLASR post 5.1 can be used to align reads with ```--bam``` option and generate aligned.bam output which contains all QVs needed for consensus calling (using ARROW). You don't need to install pitch and BLASR.

If reads are RS II data in PacBio Bas/Bax.h5 format (e.g., mxxxxxxxxxx.*.bax.h5), Please first convert H5 file to BAM file using bax2bam. bam2bam installation without using pitchfork is [here](https://github.com/PacificBiosciences/blasr/wiki/INSTALL-bax2bam-without-using-pitchfork-(not-recommended)).

Note that you may need to patch bax2bam makefile (i.e., blasr/utils/bax2bam/makefile) as shown in commit [319438](https://github.com/PacificBiosciences/blasr/commit/3194382a781276fb6bc52f71cfad6f69b3a97abb) if you are not using the latest code.
