### ISSUE TITLE
any option for enable/disable fusion gene support when mapping to reference genome?

### ISSUE THREAD

**Issue by wangyugui** [PacificBiosciences/blasr#257]
Hi.

Is there any option for enable/disable fusion gene support when mapping to reference genome?
or what is the default process of fusion gene(--clipping [none|hard|subread|soft](none)?)?

Best Regards
Wang Yugui

**Comment by ylipacbio** [comment]
At this point, there is no option for automatic fusion gene finding in BLASR.
