### ISSUE TITLE
Error while "make build-submodule"

### ISSUE THREAD

**Issue by Estel-Kitsune** [PacificBiosciences/blasr#267]
Hi,

I'm following the "step by step blasr installation" instructions. While I'm running "make build-submodule", I am getting the following error message:

make[3]: Entering directory `/usr/local/pkg/blasr/blasr/libcpp/alignment'
g++ -std=c++0x -pedantic -Wno-long-long -Wall -Wextra -Wno-overloaded-virtual   -I/usr/local/pkg/blasr/hdf5/hdf5-1.8.16-linux-centos6-x86_64-gcc447-shared/include/  -c format/SAMHeaderPrinter.cpp -o SAMHeaderPrinter.o
format/SAMHeaderPrinter.cpp: In constructor ‘SAMHeaderSQ::SAMHeaderSQ(const string&, const DNALength&, const string&)’:
**format/SAMHeaderPrinter.cpp:188:3: error: type ‘SAMHeaderSQ’ is not a direct base of ‘SAMHeaderSQ’**

Could you help me with this problem?
PS: I had to change -std=c++11 by -std=c++0x because the g++ version on the server is 4.6

**Comment by vrainish-pacbio** [comment]
Hi Estelle,

Before I look into it , please do/post the following 

ensure you have the latest version of blasr and related libraries ( if in doubt , delete and clone blasr again, shouldn't take more the 5 min  )

post your OS (output of 
uname -a 
command)

**Comment by Estel-Kitsune** [comment]
Hi Vrainish,

It seems I have the latest version:

> $git show
> commit 6fa6cc2ef893d4425131018e277e1406f3763c6c

This is the output of the **uname -a** command:

> $uname -a
> Linux vbsg-velvet 3.13.0-86-generic #131~precise1-Ubuntu SMP Fri May 13 19:43:06 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

Thanks for your help!

**Comment by mhsieh** [comment]
Hi, gcc 4.6 is not compatible, can you find a way to somehow use a newer toolchain? --mj

**Comment by Estel-Kitsune** [comment]
Hi mj, I'll see what I can do about that. Thanks!

**Comment by mhsieh** [comment]
I am suspecting that this version of gcc is not working too well with the hdf5 installation. I am now testing on some other build of hdf5 and see if that helps.
