### ISSUE TITLE
ERROR: --bam is not a valid option.

### ISSUE THREAD

**Issue by joqb** [PacificBiosciences/blasr#270]
Hello, 

I am using blasr 5.2 as 
blasr reads.fasta ref.fasta --bam
but I get ERROR: --bam is not a valid option.

I tried many other syntax like
blasr reads.fasta ref.fasta --out out.bam
blasr reads.fasta ref.fasta --bam --out out.bam
only the former gives an output file but it's no bam file, it's just the terminal out in a text file.

Any suggestion?

Best,
joqb

**Comment by pb-cdunn** [comment]
Does `blasr -h` show these options?

**Comment by vrainish-pacbio** [comment]
You need to build blasts with ban support. Please, use pitchfork for this purpose.

**Comment by pb-cdunn** [comment]
Vlad, if built without bam-support, with the `--bam` option still appear from `blasr -h`?

**Comment by joqb** [comment]
@pb-cdunn Yes blasr -h shows the option --bam to be used instead of --sam.
@vrainish-pacbio Thank you for the quick reply I forwarded the information to my IT

**Comment by vrainish-pacbio** [comment]
I think yes. I need to fix -h not to print ban related info if blasr built with no ban support

**Comment by ylipacbio** [comment]
Fixed.
