### ISSUE TITLE
SAM alignment is still needed for FALCON-Unzip

### ISSUE THREAD

**Issue by pb-jchin** [PacificBiosciences/blasr#271]
Please take a look: https://github.com/PacificBiosciences/FALCON_unzip/issues/29
There are many possible solutions but it will probably need some discussion.

**Comment by armintoepfer** [comment]
Is that still open or has it already been resolved?

**Comment by ylipacbio** [comment]
To my knowledge, this is a solved issue. Feel free to reopen it.
