### ISSUE TITLE
Error "/usr/bin/ld: cannot find -lz" when running "make blasr"

### ISSUE THREAD

**Issue by thefantasticdron** [PacificBiosciences/blasr#272]
Hello,

I am encountering the following error when running `make blasr`:

```
[seanla@breezy blasr]$ make
Unknown option: -C
usage: git [--version] [--exec-path[=GIT_EXEC_PATH]] [--html-path]
           [-p|--paginate|--no-pager] [--no-replace-objects]
           [--bare] [--git-dir=GIT_DIR] [--work-tree=GIT_WORK_TREE]
           [--help] COMMAND [ARGS]
/global/software/gcc/gcc-5.1.0/bin/g++ -o blasr -O3 -g -DSHA1_7=\"\" -std=c++0x -pedantic -Wall -Wextra -Wno-div-by-zero -Wno-overloaded-virtual -MMD -MP -fno-builtin-malloc -fno-builtin-calloc -fno-builtin-realloc -fno-builtin-free -fno-omit-frame-pointer  -I/home/seanla/Software/blasr/libcpp/alignment -I/home/seanla/Software/blasr/libcpp/hdf -I/home/seanla/Software/blasr/libcpp/pbdata -I/home/seanla/Software/hdf5/include/ -MF"blasr.d" Blasr.o -static -L/home/seanla/Software/blasr/libcpp/alignment -L/home/seanla/Software/blasr/libcpp/hdf -L/home/seanla/Software/blasr/libcpp/pbdata -L/home/seanla/Software/hdf5/lib/ -lpbihdf -lblasr -lpbihdf -lpbdata  -lhdf5_cpp -lhdf5   -lz -lrt -lpthread -ldl
/usr/bin/ld: cannot find -lz
collect2: error: ld returned 1 exit status
make: *** [blasr] Error 1
```

I have `hdf5-1.8.17` manually installed on my system using `g++ 5.1.0`.

Any ideas on how I can fix this?

Thank you,
Sean

**Comment by vrainish-pacbio** [comment]
Please,  follow "step-by-step installation example" in separate directory.

https://github.com/PacificBiosciences/blasr/wiki/step-by-step-blasr-installation-example


That's to see if you problem might be related to your hdf5 manual install.

**Comment by mhsieh** [comment]
Dear Sean, First of all, you will need a newer git for `git -C` syntax to work. Secondly can you tell us what operating system (Linux? distribution and version) are you using?

**Comment by mhsieh** [comment]
My immediate reaction is to suggest you to fix the zlib issue for the hdf5 linking. but that would depend on the linux distribution you have.
