### ISSUE TITLE
Blasr fails silently when given a DataSet and --noSplitSubreads

### ISSUE THREAD

**Issue by bnbowman** [PacificBiosciences/blasr#273]
This command gives me an empty BAM file and no warning or error:
"""
blasr --noSplitSubreads --bestn 1 --nproc 8 --out temp.bam --bam --minAlnLength 3000 --minPctAccuracy 70 m140926_214155_42142_c100701722550000001823138703261550_s1_p0.subreadset.xml /pbi/dept/secondary/siv/testdata/pblaa-unittest/P6-C4/HLA_ANRI/References/bc0--1.fasta
"""

While this works as intended:
"""
blasr --bestn 1 --nproc 8 --out temp.bam --bam --minAlnLength 3000 --minPctAccuracy 70 m140926_214155_42142_c100701722550000001823138703261550_s1_p0.subreadset.xml /pbi/dept/secondary/siv/testdata/pblaa-unittest/P6-C4/HLA_ANRI/References/bc0--1.fasta
"""

Could I get an explanation as to why this is, and at a minimum a warning if this is intended behavior?

**Comment by vrainish-pacbio** [comment]
--noSplitSubreads flag in first case,  causes Blasts to switch to a completely different mode of alignment :  rather then aligning each subread separately ( as in second case ). It stitches all subreads , adaptors etc of a given ZMW  hole itogether into  a single Polymeraze read which Blasts then try to align against reference.

**Comment by vrainish-pacbio** [comment]
To add, blasr doesn't give any warning if the resulting file has no alignments. It's a legitimate result meaning that no alignments were found ( or few were found but filtered by one of the filter options )
