### ISSUE TITLE
Could not initialize ccs file

### ISSUE THREAD

**Issue by tolot27** [PacificBiosciences/blasr#275]
I've some old bax.h5 file sets, one from October, 2013 and one from October, 2014. I can extract ccs reads  from the older set using the command `bax2bam --allowUnrecognizedChemistryTriple --ccs *.bax.h5`. Unfortunately, it does not work for the newer data set. Instead,

`ERROR, Could not initialize ccs file m141024_194544_42149_c100670002550000001823136702061562_s1_p0.1.bax.h5`

is returned. Interestingly, I do not need to provide the parameter `--allowUnrecognizedChemistryTriple` with the new data set. But for both runs, the same binding and sequencing kit were used:

```
binding kit:        100236500
sequencing kit:     001558034
```

But the basecaller version differ (2.0.2.0.124543 and 2.3.0.0.140640 respectively). `ccs` from [unanimity](https://github.com/PacificBiosciences/unanimity) does not work either because of `unsupported sequencing chemistry combination`.

How can I get the ccs reads from the newer run?

**Comment by tolot27** [comment]
Okay, found it myself. The h5 files do not contain the node `PulseData/ConsensusBaseCalls`. It looks like newer basecaller versions (after 2.0.2) did not create consensus basecalls automatically.

Now it would be great if ccs form unanimity would also support unrecognized chemistry triples. I'll raise an issue for that.

**Comment by tolot27** [comment]
Unfortunately, there is no issue tracker available in the [unanimity repository](https://github.com/PacificBiosciences/unanimity). Hence, I'll reopen this issue until the issue tracker becomes available.

**Comment by ylipacbio** [comment]
This is a unanimity issue. 

Please report this issue through tech support. 

The technical support team can be reached by email, phone, or online-form:  http://www.pacb.com/support/technical-support/

If you have more information to provide, please email support@pacificbiosciences.com and attach any log files, images, or supplementary materials.
