### ISSUE TITLE
How to extract uniq reads from blasr results?

### ISSUE THREAD

**Issue by Donbbit** [PacificBiosciences/blasr#276]
It's said to see optional fields in sam format when use BWA and focus on TAG 'NH'. However, BLASR seems to differ from BWA results . I don't find 'NH'  TAG in my optional fields. So how can I get uniq reads and duplicate reads from SAM format?

**Comment by ylipacbio** [comment]
BLASR does not support the NH tag. However, in BLASR sam/bam output, all alignments of a read should be placed together (sequentially) regardless of nproc without sort. So just count the occurrence if  you are interested.
