### ISSUE TITLE
What is scraps.bam contain?

### ISSUE THREAD

**Issue by lamz138138** [PacificBiosciences/blasr#279]
Hi!

I had use bax2bam to process my data, and got two bam files (subreads.bam and scraps.bam), I think I should use subreads.bam in downstream analysis, like getting CCS, but I wonder what is scraps.bam use for, what information it contained? Although I can find it could be use in barcode split, I still fell confuse about the file.

Best wishes!

**Comment by vrainish-pacbio** [comment]
Hi ,

scraps.bam file contains of adaptors and barcodes, subreads,bam has subreads only. In case of need , original polymerase read can be restored from scraps.bam and subreads.bam

**Comment by lamz138138** [comment]
Hi, thanks very much!

**Comment by vrainish-pacbio** [comment]
You welcome.

Link below can point you to a lot info regarding Pacbio reads structure and terminology

http://www.pacb.com/wp-content/uploads/2015/09/Pacific-Biosciences-Glossary-of-Terms.pdf

**Comment by lamz138138** [comment]
OK, thanks again!
