### ISSUE TITLE
Failure to compile on OS X Mavericks with clang compiler

### ISSUE THREAD

**Issue by molpopgen** [PacificBiosciences/blasr#28]
I've not done the work to determine if this is OSX specific or clang-specific.  However, the clang compiler often picks up on C++ issues that GCC misses (in my experience).  These are the unique errors that I get when compiling using this version of clang on the current master branch of blasr with hdf5 1.8.12 installed from source:
```
../common/algorithms/alignment/IDSScoreFunction.h:24:50: error: no matching constructor for initialization of 'BaseScoreFunction'
../common/algorithms/anchoring/../../statistics/cdfs.h:424:9: error: use of undeclared identifier 'NormCDFTable'
../common/algorithms/anchoring/../../statistics/cdfs.h:433:10: error: use of undeclared identifier 'Poisson'
../common/algorithms/anchoring/../../statistics/cdfs.h:452:7: error: use of undeclared identifier 'Poisson'
../common/data/hdf/BufferedHDFArray.h:74:29: error: destructor type 'HDFWriteBuffer<char>' in object destruction expression does not match the type 'BufferedHDFArray<char>' of the object being destroyed
../common/data/hdf/BufferedHDFArray.h:74:29: error: destructor type 'HDFWriteBuffer<float>' in object destruction expression does not match the type 'BufferedHDFArray<float>' of the object being destroyed
../common/data/hdf/BufferedHDFArray.h:74:29: error: destructor type 'HDFWriteBuffer<int>' in object destruction expression does not match the type 'BufferedHDFArray<int>' of the object being destroyed
../common/data/hdf/BufferedHDFArray.h:74:29: error: destructor type 'HDFWriteBuffer<std::__1::basic_string<char> >' in object destruction expression does not match the type 'BufferedHDFArray<std::__1::basic_string<char> >' of the object being destroyed
../common/data/hdf/BufferedHDFArray.h:74:29: error: destructor type 'HDFWriteBuffer<unsigned char>' in object destruction expression does not match the type 'BufferedHDFArray<unsigned char>' of the object being destroyed
../common/data/hdf/BufferedHDFArray.h:74:29: error: destructor type 'HDFWriteBuffer<unsigned int>' in object destruction expression does not match the type 'BufferedHDFArray<unsigned int>' of the object being destroyed
../common/data/hdf/BufferedHDFArray.h:74:29: error: destructor type 'HDFWriteBuffer<unsigned short>' in object destruction expression does not match the type 'BufferedHDFArray<unsigned short>' of the object being destroyed
./../common/datastructures/bwt/../../datastructures/suffixarray/../../ipc/SharedMemoryAllocator.h:14:6: error: use of undeclared identifier 'ftruncate'
./../common/datastructures/bwt/../../datastructures/suffixarray/SharedSuffixArray.h:30:21: error: use of undeclared identifier 'getpid'
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../lib/c++/v1/algorithm:677:97: error: invalid operands to binary expression ('const RegionAnnotation' and 'int')
11 warnings and 8 errors generated.
17 warnings and 8 errors generated.
20 warnings and 5 errors generated.
25 warnings and 10 errors generated.
5 warnings and 2 errors generated.
Blasr.cpp:4243:9: error: use of undeclared identifier 'StringToScoreMatrix'
FilterBySubreadAgreement.cpp:225:3: error: use of undeclared identifier 'FileOfFileNames'
FilterBySubreadAgreement.cpp:227:5: error: use of undeclared identifier 'FileOfFileNames'
```

**Comment by sjackman** [comment]
Please fix this issue.

**Comment by gawbul** [comment]
@sjackman :+1:

**Comment by gawbul** [comment]
I've tried everything from gcc4.5 to gcc5 with both hdf5 1.8.14 and hdf5 1.8.15 on my Yosemite 10.10.4 MBP and nothing is working! This bug should be reopened, as it fails to fix the problem put forward!

**Comment by gawbul** [comment]
Thanks for reopening, @ylipacbio. What OS, compiler and hdf5 version do you build with at PacBio? I am going to setup a vagrant box with blasr installed in it for the time being to work around these issues.

**Comment by sjackman** [comment]
BLASR 2.2 successfully compiles for me on Mac OS Yosemite 10.10.3 using GCC 5.1 and HDF5 1.8.14. If it's helpful, I can send you a Homebrew bottle, Steve.

**Comment by sjackman** [comment]
Or is it only HEAD/master that doesn't compile?

**Comment by ylipacbio** [comment]
Hi gawbul,

We are using CentOS 6, gcc 4.8.4, hdf 1.8.12 for compiling blasr. 

Sincerely,
Yuan

**Comment by ylipacbio** [comment]
Hi sjackman,

We are making lots of changes to blasr and blasr_libcpp recently, which may or may not break the build on iOS. We will check that out when we finish this round of development. 

Sincerely, 
Yuan

**Comment by sjackman** [comment]
A minor matter of terminology, but Mac OS runs on desktop machines, and iOS runs on iPhones and iPads.

**Comment by gawbul** [comment]
@sjackman a link to the bottle would be handy, please :+1:

**Comment by sjackman** [comment]
@gawbul https://www.dropbox.com/s/1kawm1sj9z40y7s/blasr-2.2.yosemite.bottle.tar.gz?dl=0

**Comment by gawbul** [comment]
@sjackman Awesome! Thanks!! :smile:

**Comment by sjackman** [comment]
There's also the bottle compiled on Mountain Lion which may or may not work on Yosemite.
https://bintray.com/artifact/download/homebrew/bottles-science/blasr-2.2.mountain_lion.bottle.tar.gz

**Comment by gawbul** [comment]
@sjackman :+1:

**Comment by pb-cdunn** [comment]
We will *definitely* fix this soon. Not only do we want **blasr* to compile on OSX and iOS, not only is **clang** a better compiler, but we need to upgrade to at least **gcc-4.8** to be compatible with other PacBio software. I'll look at #29 from @molpopgen.

**Comment by pb-cdunn** [comment]
Solved. See bottom #125, FAQ, or just read this:
* https://gcc.gnu.org/onlinedocs/libstdc++/manual/using_dual_abi.html
