### ISSUE TITLE
How did --minPctSimilarity work in blasr ?

### ISSUE THREAD

**Issue by biozzq** [PacificBiosciences/blasr#280]
Hi,

I am preparing to align two genomes by `blasr` with one split into 1k pieces to get the segments with similarity over 95% (following command).
`blasr split.fa reference.fa -m 5 --sa reference.fa.sa --nproc 8 --bestn 1 --affineExtend 0 --affineAlign --affineOpen 8 --sdpTupleSize 13 --noSplitSubreads --unaligned unmapped.fa --minPctSimilarity 95 --out mapped` 

But I find the unmapped sequences can be also mapped to reference.fa without `--minPctSimilarity` and the results like following which has truncated the `qAlignedSeq matchPattern tAlignedSeq`,

`1 1000 0 997 +  chr1 51421553 182280 183275 + -4410 958 0 39 37 254` 
`2 1000 0 996 +  chr1 51421553 177343 178352 + -4450 965 0 31 44 254`
`3 1000 0 1000 + chr1 51421553 176343 177343 + -4565 971 0 29 29 254`

we can see the similarity are all above 95%, why did they have been reported to the unmapped.fa?

Many thanks
Best

**Comment by bionwsuafzy** [comment]
I want to know, too.
How the parameters are set?

**Comment by biozzq** [comment]
Hi all,
@ylipacbio @vrainish-pacbio @pb-cdunn 
I also find my output about mismatch is all 0, I think I have missed some parameters or made some mistakes in some parameters. 

Best

**Comment by vrainish-pacbio** [comment]
Short answer is that -minPctSimularity is one of many post-alignment filtration flags.
After subread is aligned , the resulting alignment need to pass a number of tests ( filters ) which determine if it will be placed to output file or not. For examplle , Blasr can filter all alignments below certain length etc .

May I ask why do you use --noSplitSubreads flag ?

Do you need to assemble all subreads back to an original polymerase read witn adaptors. and barcodes ? That's what this option do.

**Comment by biozzq** [comment]
Hi @vrainish-pacbio 

Thanks. Yes, all my reads do not contain adaptors, I just want to use blasr to instead of blastn for its speed. Furthermore, when I remove parameters `--affineAlign`, the mismatch will not be 0.

Ps, I also do not know why the similarity of a 1k read has 971 matches is under 95%
`3 1000 0 1000 + chr1 51421553 176343 177343 + -4565 971 0 29 29 254`

Best

**Comment by ylipacbio** [comment]
Here `Mismatches` actually means `substitutions` while `insertions` and `deletions` are *NOT* considered as `Mismatches`.
