### ISSUE TITLE
How blasr identify the adapters in original polymerase reads ?

### ISSUE THREAD

**Issue by RyanBio** [PacificBiosciences/blasr#281]
Hi all,
@ylipacbio @vrainish-pacbio @pb-cdunn
The blasr parameters --noSplitSubreads says "Do not split subreads at adapters". I want to know how blasr identify the adapters in original polymerase reads ? And how to split polymerase reads into subreads directly? Thanks.

Best.
Ryan

**Comment by vrainish-pacbio** [comment]
When this option is given, subreads adaptors and barcodes are stititched back into a single polymerase reads and then is being aligned against reference, which in such a case is most likely is an unrolled template, not a genome . This is a special purpose flag

The adaptors are unique sequences of 50-60 bases. They are not identified iin Blasts, but recognized on much early stage by a separate module.

Please see Pacbio Glossary of terms for more info

**Comment by RyanBio** [comment]
Hi, Vladimir
Thanks for your reply.
Blasr use the parameters "--noSplitSubreads" for aligning against an "unrolled-template" reference.
Actually, i want to find a tool which can identify and cut adaptors  according to a polymerase read. 
I will see other Pacbio tools for more info.

Best
Ryan

**Comment by vrainish-pacbio** [comment]
Hi Ryan,

It's not clear for me : do you have a polymerase read and you would like to split it to subreads and adaptors toi align each subread separately ?
