### ISSUE TITLE
samtoh5 not found

### ISSUE THREAD

**Issue by pawelosipowski** [PacificBiosciences/blasr#286]
Hi, when running blasr 5.3.90d98ad installed through pitchfork I get an error of `samtoh5 not found`. What is it?

**Comment by mhsieh** [comment]
Note: I solved this in pitchfork, but consider this is a plead to keep these utilities in software 3.x .

**Comment by mhsieh** [comment]
https://github.com/PacificBiosciences/pitchfork/issues/297
