### ISSUE TITLE
LoadPulses error - Either the number of elements exceeds maxElement (2147483647). Or the estimated memory  consumption exceeds maxMemory (4 GB)

### ISSUE THREAD

**Issue by pawelosipowski** [PacificBiosciences/blasr#291]
Hi, can you explain me what is happening here. It doesn't seem a big issue..

```
[ERROR] 2016-10-04 07:25:07,080Z [root Execute 67] LoadPulsesService returned a non-zero exit status. [INFO] 2016-10-04T09:23:12 [loadPulses] started.
Either the number of elements exceeds maxElement (2147483647). Or the estimated memory 
consumption exceeds maxMemory (4 GB).
Loading pulses from ./m160721_030657_42158_c100999392550000001823227209081697_s1_p0.3.bax.h5 by read.
loading 171947 alignments for movie 1
ERROR, the query sequence does not match the aligned query sequence.
HoleNumber: 157106, MovieName: m160721_030657_42158_c100999392550000001823227209081697_s1_p0, ReadIndex: 48118, qStart: 7, qEnd: 12951
Aligned sequence:<long seq here>
Original sequence:<long seq here>
loadPulses: LoadPulses.cpp:2300: int main(int, char**): Assertion `0' failed.
Aborted (core dumped)
[INFO] 2016-10-04 07:25:07,271Z [pbalign.pbalignrunner _pacbio_main_runner 153] exiting with return code 1 in 49971.90 sec.
(END)
```

the command is:
`pbalign /storage3/reads_b10/pacbio_2016/pb_2016.fofn /storage3/long_read_assembly/polishing/pb_B10v2_12000.fasta /storage3/long_read_assembly/polishing/pbalign_out.cmp.h5 --forQuiver --log-file pbalign.log --nproc 24`
pbalign 3.0
blasr 5.3.90d98ad
installed through pitchfork
Could you explain me some more on this query sequence, what is the exact problem here and solution, please
Regards

**Comment by ylipacbio** [comment]
Please use *legacy pbalign* and *legacy blasr* instead of the version that you currently use.

Please first uninstall the current pitchfork build, and then install legacy pbalign using pitchfork `make legacy_pbalign`.

To avoid loadPulses assertion error, please use pbalign option `--byread`.
