### ISSUE TITLE
execute blasr failed

### ISSUE THREAD

**Issue by fklayer** [PacificBiosciences/blasr#296]
Hi there,

I currently compiled blasr on our cluster following the instructions here:
https://github.com/PacificBiosciences/blasr/wiki/Step-by-step-blasr-installation-examplehttps://github.com/PacificBiosciences/blasr/wiki/Step-by-step-blasr-installation-example

after the last step by adding the LD_LIBRARY_PATH to my bashrc when I executing blasr with ./blasr

it prints out the following error message:

./blasr: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by ./blasr)
./blasr: /usr/lib64/libstdc++.so.6: version`CXXABI_1.3.8' not found (required by ./blasr)
./blasr: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by ./blasr)
./blasr: /usr/lib64/libstdc++.so.6: version`CXXABI_1.3.8' not found (required by /home/fengk/software/blasr_install/blasr/libcpp/hdf/libpbihdf.so)
./blasr: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /home/fengk/software/blasr_install/blasr/libcpp/hdf/libpbihdf.so)
./blasr: /usr/lib64/libstdc++.so.6: version`CXXABI_1.3.8' not found (required by /home/fengk/software/blasr_install/blasr/libcpp/alignment/libblasr.so)
./blasr: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /home/fengk/software/blasr_install/blasr/libcpp/alignment/libblasr.so)
./blasr: /usr/lib64/libstdc++.so.6: version`CXXABI_1.3.8' not found (required by /home/fengk/software/blasr_install/blasr/libcpp/pbdata/libpbdata.so)
./blasr: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /home/fengk/software/blasr_install/blasr/libcpp/pbdata/libpbdata.so)
./blasr: /usr/lib64/libstdc++.so.6: version`GLIBCXX_3.4.21' not found (required by /home/fengk/software/blasr_install/hdf5/hdf5_with_gcc5.3/lib/libhdf5_cpp.so.12)

Could you please help fix this problem

Thanks, 

Kai

**Comment by pb-cdunn** [comment]
If you post how you solved this, it might help others.

**Comment by fklayer** [comment]
just add the gcc/lib64 (the gcc which you are using to compile blasr) to your LD_LIBRARY_PATH, blasr will work.
