### ISSUE TITLE
make build-submodule issue

### ISSUE THREAD

**Issue by nataliering** [PacificBiosciences/blasr#301]
Hi,

I'm following the step-by-step instructions, and having problems when I reach the "make build-submodule" step.

I did change the steps slightly, because the wget from HDF5 wasn't working for me, so I downloaded hdf5-1.8.16-linux-centos6-x86_64-gcc447-shared.tar.gz from [https://support.hdfgroup.org/ftp/HDF5/releases/hdf5-1.8.16/bin/linux-centos6-x86_64-gcc447/](url) instead, and then used -zxvf on it in the /blasr_install/hdf5 directory as per the instructions. 

Other than this change, everything seems to work fine until "make build-submodule", which exits with the following error: 

`make libpbihdf
make[2]: Entering directory '/home/ubuntu/blasr_install/blasr/libcpp'
make -C /home/ubuntu/blasr_install/blasr/libcpp//hdf all
make[3]: Entering directory '/home/ubuntu/blasr_install/blasr/libcpp/hdf'
g++ -std=c++11 -pedantic -Wall -Wextra -Wno-overloaded-virtual   -I/blasr_install/         hdf5/hdf5-1.8.16-linux-centos6-x86_64-gcc447-shared/include/  -c BufferedHDFArray.         cpp -o BufferedHDFArray.o
In file included from BufferedHDFArray.cpp:1:0:
BufferedHDFArray.hpp:10:18: fatal error: hdf5.h: No such file or directory
compilation terminated.
/home/ubuntu/blasr_install/blasr/libcpp/hdf//../rules.mk:20: recipe for target 'Bu         fferedHDFArray.o' failed
make[3]: *** [BufferedHDFArray.o] Error 1
make[3]: Leaving directory '/home/ubuntu/blasr_install/blasr/libcpp/hdf'
makefile:21: recipe for target 'libpbihdf' failed
make[2]: *** [libpbihdf] Error 2
make[2]: Leaving directory '/home/ubuntu/blasr_install/blasr/libcpp'
makefile:8: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/home/ubuntu/blasr_install/blasr/libcpp'
makefile:54: recipe for target 'build-submodule' failed
make: *** [build-submodule] Error 2
`

I'm having a bad day with things failing on me for no obvious reason and am at a loss! Any ideas why this is happening, and how I can fix it please? I need blasr in order to run ABruijn assembly on some long reads.

Thanks in advance!

**Comment by vrainish-pacbio** [comment]
Hi Natalie,

I'll take a look, I recall some other people had issues with HDF5, Meanwhile, can you please, post your OS and gcc version , Take a look on wiki page how to obtain them if you don't know.

Regards, Vladimir

**Comment by nataliering** [comment]
Hi Vladimir

Thanks for your reply.

I'm using a virtual machine through MRC CLIMB, which is running:

OS - Ubuntu 16.04.1 LTS (GNU/Linux 4.4.0-31-generic x86_64) 
gcc - (Ubuntu 5.4.0-6ubuntu1~16.04.4) 5.4.0 20160609.

The image I'm using came with some packages pre-installed, so might already have had another different version of HDF5 and would now have two - I don't know if that would cause this problem?

Regards,
Natalie

**Comment by vrainish-pacbio** [comment]
Hi Natalie,

Please, post also your configure.py entire command

**Comment by nataliering** [comment]
Hi Vladimir

I just used the one from the step-by-step guide: 

`./configure.py --shared --sub --no-pbbam HDF5_INCLUDE=${TOP}/blasr_install/hdf5/hdf5-1.8.16-linux-centos6-x86_64-gcc447-shared/include/ HDF5_LIB=${TOP}blasr_install/hdf5/hdf5-1.8.16-linux-centos6-x86-64-gcc447-shared/lib
`

(That's a copy-paste of what I actually typed, in case there's a typo I didn't notice...).

Natalie

**Comment by vrainish-pacbio** [comment]
Thanks, let me check something

**Comment by vrainish-pacbio** [comment]
Hi Natalie

You have 
-I/blasr_install/ hdf5/hdf5-1.8.16-linux-centos6-x86_64-gcc447-shared/include/

while it it should be -I/home/ubuntu/blasr_include 

Please , check if you didn't forget to  execute **VERY first command** from "example"
TOP=$(pwd)

after it 
echo $TOP should print ( in your case) /home/ubuntu

**Comment by vrainish-pacbio** [comment]
You can look into defines.mk file to ensure HDF5_INC and HDF5_LIB are defined correctly ( have /home/ubuntu)

**Comment by vrainish-pacbio** [comment]
If not you need to rerun configure.py

**Comment by nataliering** [comment]
Hi Vladimir

Thanks for that - yes I had forgotten to do TOP=$(pwd)!

I removed all the directories and started again, this time the configure.py did define HDF5_INC and HDF_LIB correctly, and make build-submodule didn't fail in the same place.

Unfortunately, it's failing on libpbihdf now instead. Here's the error message:

`g++ -shared  -L../pbdata -L/home/ubuntublasr_install/hdf5/hdf5-1.8.16-linux-cent                                                                                        os6-x86-64-gcc447-shared/lib -o libpbihdf.so -Wl,-soname,libpbihdf.so BufferedHD                                                                                        FArray.shared.o HDFRegionsWriter.shared.o HDFZMWMetricsWriter.shared.o HDFWriter                                                                                        Base.shared.o DatasetCollection.shared.o HDFRegionTableReader.shared.o HDFNewBas                                                                                        Reader.shared.o HDFAtom.shared.o HDFCmpExperimentGroup.shared.o HDFPulseDataFile                                                                                        .shared.o HDFPulseCallsWriter.shared.o HDFCmpSupportedFields.shared.o HDFBaseCal                                                                                        lsWriter.shared.o HDFZMWReader.shared.o HDFFile.shared.o HDFAlnInfoGroup.shared.                                                                                        o HDFPulseWriter.shared.o HDFGroup.shared.o HDFUtils.shared.o HDFZMWWriter.share                                                                                        d.o HDFScanDataWriter.shared.o HDFScanDataReader.shared.o HDFData.shared.o HDFBa                                                                                        xWriter.shared.o HDFPulseH5Writer.shared.o BufferedHDF2DArray.shared.o HDFAttrib                                                                                        utable.shared.o HDFAlnGroupGroup.shared.o -lpbdata -lhdf5 -lhdf5_cpp
/usr/bin/ld: cannot find -lhdf5
collect2: error: ld returned 1 exit status
/home/ubuntu/blasr_install/blasr/libcpp/hdf//../rules.mk:14: recipe for target '                                                                                        libpbihdf.so' failed
make[3]: *** [libpbihdf.so] Error 1
make[3]: Leaving directory '/home/ubuntu/blasr_install/blasr/libcpp/hdf'
makefile:21: recipe for target 'libpbihdf' failed
make[2]: *** [libpbihdf] Error 2
make[2]: Leaving directory '/home/ubuntu/blasr_install/blasr/libcpp'
makefile:8: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/home/ubuntu/blasr_install/blasr/libcpp'
makefile:54: recipe for target 'build-submodule' failed
make: *** [build-submodule] Error 2
`

Sorry to be a pain, I was so happy when I saw it passing the BufferedHDFArray stage!

Regards,
Natalie

**Comment by vrainish-pacbio** [comment]
Hi Natalie,
First, there is a progress  which is good. I'll take a look morning and post solution. Hdf5 libraries caused problems for other people as well.

Regards, Vladimir

**Comment by vrainish-pacbio** [comment]
-L/home/ubuntublasr_install/hdf5/hdf5-1.8.16-

Hi Natalie,

There is an absense of forward slash between ububtu and blasr after -L

Can you please check if this a result of typo/mistake in your copy and paste or it's really not there

**Comment by nataliering** [comment]
Hi Vladimir

It really is missing:

![image](https://cloud.githubusercontent.com/assets/23463469/20303318/cc4f227a-ab22-11e6-93c9-0a1065e30daf.png)

**Comment by vrainish-pacbio** [comment]
Hi Natalie,

Thanks I'll check what happens.

Vladimir

**Comment by vrainish-pacbio** [comment]
Hi Natalie

Please, do the following:

Remove ENTIRE **blasr_install** directory

Do **everything** from scratch including bringing and untaring hdf5 ( don't forget **TOP** ), just
follow step-by-step  ( copy and paste every command from it)

I  had a problem in build-submodule as well, did what I described above and build blasr succesfully just now

**Comment by nataliering** [comment]
Hi Vladimir

More progress! I deleted everything and started again, following every step exactly. make build-submodule worked!

But.... make blasr failed. Everything:

`ubuntu@nat-nanopore-essentials:~/blasr_install/blasr$ make blasr
g++ -O3 -g -DSHA1_7=\"8c16f52\" -std=c++0x -pedantic -Wall -Wextra -Wno-div-by-z                                                                                        ero -Wno-overloaded-virtual -MMD -MP -fno-builtin-malloc -fno-builtin-calloc -fn                                                                                        o-builtin-realloc -fno-builtin-free -fno-omit-frame-pointer  -I/home/ubuntu/blas                                                                                        r_install/blasr/libcpp/alignment -I/home/ubuntu/blasr_install/blasr/libcpp/hdf -                                                                                        I/home/ubuntu/blasr_install/blasr/libcpp/pbdata -I/home/ubuntu/blasr_install/hdf                                                                                        5/hdf5-1.8.16-linux-centos6-x86_64-gcc447-shared/include/  -c -o Blasr.o Blasr.c                                                                                        pp
g++ -o blasr -O3 -g -DSHA1_7=\"8c16f52\" -std=c++0x -pedantic -Wall -Wextra -Wno                                                                                        -div-by-zero -Wno-overloaded-virtual -MMD -MP -fno-builtin-malloc -fno-builtin-c                                                                                        alloc -fno-builtin-realloc -fno-builtin-free -fno-omit-frame-pointer  -I/home/ub                                                                                        untu/blasr_install/blasr/libcpp/alignment -I/home/ubuntu/blasr_install/blasr/lib                                                                                        cpp/hdf -I/home/ubuntu/blasr_install/blasr/libcpp/pbdata -I/home/ubuntu/blasr_in                                                                                        stall/hdf5/hdf5-1.8.16-linux-centos6-x86_64-gcc447-shared/include/ -MF"blasr.d"                                                                                         Blasr.o -L/home/ubuntu/blasr_install/blasr/libcpp/alignment -L/home/ubuntu/blasr                                                                                        _install/blasr/libcpp/hdf -L/home/ubuntu/blasr_install/blasr/libcpp/pbdata -L/ho                                                                                        me/ubuntu/blasr_install/hdf5/hdf5-1.8.16-linux-centos6-x86_64-gcc447-shared/lib                                                                                         -lpbihdf -lblasr -lpbihdf -lpbdata  -lhdf5_cpp -lhdf5   -lz -lrt -lpthread -ldl
/home/ubuntu/blasr_install/blasr/libcpp/hdf/libpbihdf.so: undefined reference to                                                                                         `H5::H5Location::iterateAttrs(void (*)(H5::H5Location&, std::__cxx11::basic_str                                                                                        ing<char, std::char_traits<char>, std::allocator<char> >, void*), unsigned int*,                                                                                         void*)'
/home/ubuntu/blasr_install/blasr/libcpp/hdf/libpbihdf.so: undefined reference to                                                                                         `H5::CommonFG::createGroup(std::__cxx11::basic_string<char, std::char_traits<ch                                                                                        ar>, std::allocator<char> > const&, unsigned long) const'
/home/ubuntu/blasr_install/blasr/libcpp/hdf/libpbihdf.so: undefined reference to                                                                                         `H5::CommonFG::getObjnameByIdx[abi:cxx11](unsigned long long) const'
/home/ubuntu/blasr_install/blasr/libcpp/hdf/libpbihdf.so: undefined reference to                                                                                         `H5::Attribute::write(H5::DataType const&, std::__cxx11::basic_string<char, std                                                                                        ::char_traits<char>, std::allocator<char> > const&) const'
/home/ubuntu/blasr_install/blasr/libcpp/hdf/libpbihdf.so: undefined reference to                                                                                         `H5::Attribute::read(H5::DataType const&, std::__cxx11::basic_string<char, std:                                                                                        :char_traits<char>, std::allocator<char> >&) const'
/home/ubuntu/blasr_install/blasr/libcpp/hdf/libpbihdf.so: undefined reference to                                                                                         `H5::Exception::getDetailMsg[abi:cxx11]() const'
collect2: error: ld returned 1 exit status
makefile:63: recipe for target 'blasr' failed
make: *** [blasr] Error 1
`

Sorry!
Natalie

**Comment by pb-cdunn** [comment]
Different version of gcc when HDF5 was built? (Or at least no `--std=c++11` flag.)

**Comment by nataliering** [comment]
Hi Christopher - how can I check that/is there anything I can do to fix it?

**Comment by pb-cdunn** [comment]
Re-install HDF5, I guess. Then you will know how it was built.

**Comment by nataliering** [comment]
Hi Christopher

As per the rest of this thread, I re-installed HDF5 today using the step-by-step Blasr installation instructions ([https://github.com/PacificBiosciences/blasr/wiki/Step-by-step-blasr-installation-example](url)).  Re-installing again now can't make a difference, can it? Any other ideas what might be causing the latest error with make blasr please?

**Comment by mhsieh** [comment]
by install, you meant re-downloading it from the www.hdfgroup.org website? No, this doesn't work with the shiny new ubuntu16.

First of all, do you happen to have admin permission for this linux server?

**Comment by nataliering** [comment]
Hello, yes that's what I meant by re-install. Unfortunately I don't think I have admin permissions as I'm just using an image on a virtual machine. Is there a work around that doesn't need admin? Or should I go back to an older version of Ubuntu?

**Comment by mhsieh** [comment]
If you started the image yourself, you should be already an admin to that image. Do you know how to run sudo in this ubuntu 16 instance?

**Comment by pb-cdunn** [comment]
The basic issue:

* http://askubuntu.com/questions/770358/how-should-i-handle-abi-incompatability-between-gcc-4-9-and-gcc-5
* http://stackoverflow.com/questions/34571583/understanding-gcc-5s-glibcxx-use-cxx11-abi-or-the-new-abi

**Comment by mhsieh** [comment]
My suggestion based on current "step-by-step" was to use system hdf5 so @nataliering can be unblocked quickly.

**Comment by nataliering** [comment]
Hi,

Yes I can run sudo. What do I need to do please?

**Comment by mhsieh** [comment]
Can you do `sudo apt-get install libhdf5-dev` in your ubuntu16 vm? I will follow up with the modification to the step according to this.

**Comment by mhsieh** [comment]
You now don't need the hdf5 download and extraction part from the steps. After that, two commands require some modification:
```
./configure.py --shared --sub --no-pbbam HDF5_INCLUDE=/usr/include HDF5_LIB=/usr/lib
```
and
```
LD_LIBRARY_PATH=${TOP}/blasr_install/blasr/libcpp/alignment:${TOP}/blasr_install/blasr/libcpp/hdf:${TOP}/blasr_install/blasr/libcpp/pbdata:/usr/lib:
```

**Comment by nataliering** [comment]
It's saying I already have libhdf5-dev: 

`Reading package lists... Done
Building dependency tree
Reading state information... Done
libhdf5-dev is already the newest version (1.8.16+docs-4ubuntu1).
The following packages were automatically installed and are no longer required:
  libgsl2 linux-headers-4.4.0-24 linux-headers-4.4.0-24-generic
  linux-image-4.4.0-24-generic
Use 'sudo apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 79 not upgraded.
`
But when I run make build-submodule, it's back to the original error I was having at the top of this thread:

`make[3]: Entering directory '/home/ubuntu/blasr_install/blasr/libcpp/hdf'
g++ -std=c++11 -pedantic -Wall -Wextra -Wno-overloaded-virtual   -I/usr/include  -c BufferedHDFArray.cpp -o BufferedHDFArray.o
In file included from BufferedHDFArray.cpp:1:0:
BufferedHDFArray.hpp:10:18: fatal error: hdf5.h: No such file or directory
compilation terminated.
/home/ubuntu/blasr_install/blasr/libcpp/hdf//../rules.mk:20: recipe for target 'BufferedHDFArray.o' failed
make[3]: *** [BufferedHDFArray.o] Error 1
make[3]: Leaving directory '/home/ubuntu/blasr_install/blasr/libcpp/hdf'
makefile:21: recipe for target 'libpbihdf' failed
make[2]: *** [libpbihdf] Error 2
make[2]: Leaving directory '/home/ubuntu/blasr_install/blasr/libcpp'
makefile:8: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/home/ubuntu/blasr_install/blasr/libcpp'
makefile:54: recipe for target 'build-submodule' failed
make: *** [build-submodule] Error 2
`

When I look in /usr/include, hdf5 is in there. But there's nothing related to hdf5 in /usr/lib. Am I doing something wrong?!

**Comment by mhsieh** [comment]
Try this instead, ubuntu16 place the files in somewhere I didn't expect:
```./configure.py --shared --sub --no-pbbam HDF5_INCLUDE=/usr/include/hdf5/serial HDF5_LIB=/usr/lib/x86_64-linux-gnu/hdf5/serial
```and
```
LD_LIBRARY_PATH=${TOP}/blasr_install/blasr/libcpp/alignment:${TOP}/blasr_install/blasr/libcpp/hdf:${TOP}/blasr_install/blasr/libcpp/pbdata:/usr/lib/x86_64-linux-gnu/hdf5/serial```

**Comment by nataliering** [comment]
It works! Well, I've not tried to run it yet, but ./blasr --version returns "blasr 5.3.8c16f52"!

Thanks to all of you for your help and patience :)
