### ISSUE TITLE
different output from bax2bam

### ISSUE THREAD

**Issue by bostanict** [PacificBiosciences/blasr#305]
Hi,

I am running bax2bam to convert bax files to bam.

when I run the command specifying each of the subread files from 1 smart cell, the subread bam file is different in size comparing to the time I run bax2bam using wildcard in address:

case 1:

    bax2bam p0.1.bax.h5 p0.2.bax.h5 p0.3.bax.h5 -o movie1 --subread --pulsefeatures=DeletionQV,DeletionTag,InsertionQV,IPD,MergeQV,SubstitutionQV,PulseWidth,SubstitutionTag

case 2:

    bax2bam *.bax.h5 -o movie2 --subread --pulsefeatures=DeletionQV,DeletionTag,InsertionQV,IPD,MergeQV,SubstitutionQV,PulseWidth,SubstitutionTag

output:
the scraps files are identical in size but the movie files (bam and bam.bai) are  different a little in size.

so I just want to know if I can sue wild card and f this is to system addressing that the size is different or the result will be different in each command line. Thanks

**Comment by ylipacbio** [comment]
Would you please `ls -lha` and show file sizes or show the number of alignments in both bam output files by `samtools view output.bam |wc -l`. 

The output bam file contains the command line that was called so it's OK to see a little difference in size.
