### ISSUE TITLE
How to defined coverage and identity?

### ISSUE THREAD

**Issue by lamz138138** [PacificBiosciences/blasr#306]
Hi!

I had mapped pacbio data with blasr, and the output format is sam, then calculated coverage (the percentage of reads that was mapped) and identity by myself. But I don't know how to set the threshold for this two parameters, so I set coverage threshold as 0.5,0.55, 0.6, 0.65, 0.7, 0.75, 0.8, 0.85, 0.9, 0.95, then I think 0.55 could be a threshold as it discard most alignments. Howevere, I don't think my criteria isn't stringent, is there any empirical value or how can I select the two parameters?

Best wishes!

**Comment by ylipacbio** [comment]
>then calculated coverage (the percentage of reads that was mapped) and identity by myself.

The criteria is all up to your applications. The mean pacbio raw read to reference identity is usually around 85%, and mean pacbio ccs reads to reference identity is usually around 95% or higher.

I am surprised that with a coverage cutoff of 0.55, most alignments were discarded. In fact most alignments should pass. Did you calculate coverage in the coordinate of subreads (i.e., num of mapped bases in a subread over number of bases in a subread) or in the coordinate of unrolled read? To most users, only subread coverage matters.

**Comment by lamz138138** [comment]
Hi, thanks for your reply!

I defined coverage XL/XQ (XL and XQ are tag provided by blasr), I think it is same as you mention above.  Maybe I didn't state clearly above, as following picture, there are total 38,999 reads mapped, then using different coverage threshold, we would filter some aligned reads. I hypothesis that there is a point where most false alignment reads would be filtered out, after that point, the filter rate would be slow since most alignment are true alignment. This is why I chose 0.55. The percentage is defined as (number of align reads at the threshold)/38,999. I may make a mistake here, instead of using the number of align reads, I should use the number of align record, and you can ignore HC.

![image](https://cloud.githubusercontent.com/assets/10007608/20703620/5db74e74-b657-11e6-9f42-af53fe28e0b1.png)

**Comment by ylipacbio** [comment]
Please do not compute coverage based on XQ because XQ is the length of unrolled zmw read, not length of the query subread. You may get length of the query subread by (qe - qs) where qe and qs are SAM tags representing start and end positions of a subread in coordinate of unrolled zmw read. See https://github.com/PacificBiosciences/PacBioFileFormats/blob/3.0/BAM.rst#use-of-read-tags-for-per-read-information for details
