### ISSUE TITLE
BLASR log information

### ISSUE THREAD

**Issue by KrithikaSubramanian** [PacificBiosciences/blasr#308]
Hi,

I am using BLASR for aligning Oxford Nanopore reads. How will I find out the below details:
1. Number of reads are mapped.?
2. Number of reads are not mapped.?
3. Coverage.?

Can anyone suggest me regarding this.

Thanks
Krithika

**Comment by vrainish-pacbio** [comment]
Have you tried to run samtools on the output ?

**Comment by KrithikaSubramanian** [comment]
Yes @vrainish-pacbio 
I have 45894 reads. Its Including three gene sequences with few different samples. I did aligned with corresponding reference gene sequence.  After alignment, I tried "samtools flagstat".  Properly paried is 0, read 1, read 2 is 0.

For example: Gene 1 flagstat
samtools flagstat
34027 + 0 in total (QC-passed reads + QC-failed reads)
0 + 0 duplicates
34027 + 0 mapped (100.00%:-nan%)
0 + 0 paired in sequencing
0 + 0 read1
0 + 0 read2
0 + 0 properly paired (-nan%:-nan%)
0 + 0 with itself and mate mapped
0 + 0 singletons (-nan%:-nan%)
0 + 0 with mate mapped to a different chr
0 + 0 with mate mapped to a different chr (mapQ>=5)

And, Can you please calrify me. 
Gene 1, 34027 + 0 in total (QC-passed reads + QC-failed reads) out of 45894
Gene 2, 32301 + 0 in total (QC-passed reads + QC-failed reads) out of 45894
Gene 3, 5243 + 0 in total (QC-passed reads + QC-failed reads) out of 45894

I am expecting. If I add all mapped reads, I will get total number of reads (45894). But I am getting, 71571. How Its possible.? Is I am in correct path.? 
Some reads are aligned with both gene.?

**Comment by evolvedmicrobe** [comment]
Hi @KrithikaSubramanian,

This isn't really a question specific to BLASR, you can find answers to how to read and interpret BAM files as well as perform common bioinformatics tasks on such forums as http://seqanswers.com/ and https://www.biostars.org/.

For your particular problem, you should note that the total observed for a BAM file is less than the total number of reads for an alignment.  samtools flagstat is designed to run on a single BAM file last I checked, and it sounds like you have created different BAMs from different references so all bets are off.

Also note that the paired reads is a concept specific to Illumina, where they are trying to get around the difficulties of not being able to read through an entire molecule.  Similarly, duplicate reads are often not as relevant for PacBio data as users are free to sequence individual molecules and so do not need to introduce PCR bias/duplicates if they choose not to.

Cheers,
N

**Comment by KrithikaSubramanian** [comment]
Thank you for your answers @evolvedmicrobe 
Yes, Its different BAMs from different reference.
I thought, Nanopore data is the long reads, because of that I got, same reads aligned with different reference sequence.
