### ISSUE TITLE
blasr installation error: H5Cpp.h: No such file or directory

### ISSUE THREAD

**Issue by Gaussia** [PacificBiosciences/blasr#309]
Before I describe my issue in detail I should point out that I know that it's a common issue. I have worked on it the last few days and looked at all the posts in:
https://github.com/PacificBiosciences/blasr/issues?utf8=%E2%9C%93&q=is%3Aissue%20H5Cpp.h
as well as help in:
https://github.com/PacificBiosciences/blasr/wiki/Blasr-Installation-Qs-&-As
without getting it to work.

With that said: I am using OpenSUSE. I should also point out that I don't have very much experiance in using the Linux terminal or bash.

I'm following the instructions in:
https://github.com/PacificBiosciences/blasr/wiki/Step-by-step-blasr-installation-example
starting in /home/username/ I write:
`TOP=$(/home/username) `
(also tried: 
`TOP=$/home/username `
 and 
`TOP=/home/username  `
and 
`TOP=(/home/username)  `
) neither seems to work.

next I continue with:

`mkdir -p blasr_install `
`cd blasr_install `

`mkdir -p hdf5 `
`cd hdf5 `
`wget https://www.hdfgroup.org/ftp/HDF5/releases/hdf5-1.8.16/bin/linux-centos6-x86_64-gcc447/hdf5-1.8.16-linux-centos6-x86_64-gcc447-shared.tar.gz `
`tar -zxvf hdf5-1.8.16-linux-centos6-x86_64-gcc447-shared.tar.gz `
`cd .. `

`git clone https://github.com/PacificBiosciences/blasr.git --recursive `
`cd blasr `

`./configure.py --shared --sub --no-pbbam HDF5_INCLUDE=${TOP}/blasr_install/hdf5/hdf5-1.8.16-linux-centos6-x86_64-gcc447-shared/include/ HDF5_LIB=${TOP}/blasr_install/hdf5/hdf5-1.8.16-linux-centos6-x86_64-gcc447-shared/lib/ `
`make configure-submodule `
`make build-submodule  `

the last command 
`make build-submodule `
works for a while until it outputs:
...
`make[2]: Entering directory '/home/torkel/blasr_install/blasr/libcpp'`
`make -C /home/torkel/blasr_install/blasr/libcpp//hdf all`
`make[3]: Entering directory '/home/torkel/blasr_install/blasr/libcpp/hdf'`
`g++ -std=c++11 -pedantic -Wall -Wextra -Wno-overloaded-virtual   -I/home/torkel/blasr_install``/hdf5-1.8.18/include  -c HDFAttributable.cpp -o HDFAttributable.o`
`In file included from HDFAttributable.cpp:2:0:`
`HDFAttributable.hpp:6:19: fatal error: H5Cpp.h: No such file or directory`
` #include <H5Cpp.h>`
`                   ^`
`compilation terminated.`
`/home/torkel/blasr_install/blasr/libcpp/hdf//../rules.mk:20: recipe for target 'HDFAttributable.o' failed`
`make[3]: *** [HDFAttributable.o] Error 1`
`make[3]: Leaving directory '/home/torkel/blasr_install/blasr/libcpp/hdf'`
`makefile:21: recipe for target 'libpbihdf' failed`
`make[2]: *** [libpbihdf] Error 2`
`make[2]: Leaving directory '/home/torkel/blasr_install/blasr/libcpp'`
`makefile:8: recipe for target 'all' failed`
`make[1]: *** [all] Error 2`
`make[1]: Leaving directory '/home/torkel/blasr_install/blasr/libcpp'`
`makefile:54: recipe for target 'build-submodule' failed`
`make: *** [build-submodule] Error 2`
I have checked all the other commands and none of them seems to output any errors.

Now I've tried several solutions (including looking at all the previous times the issue's been raised).
- When writing:
`./configure.py ...`
I have tried adding 
`./configure.py --enable-cxx ...`
as well as
`./configure.py  --prefix=your_desired_folder --enable-cxx ...`
(with your_desired_folder as different folders, /home/username/blasr_install/hdf5, /home/username/blasr_install/, /home/username/blasr_install/blasr)
I've also tried putting 
`--enable-cxx ...`
at the end of the configure. The terminal just returns that it doesn't recognize --enable.. or --prefix...
- I have checked an in /home/username/blasr_install/hdf5/hdf5-1.8.16-linux-centos6-x86_64-gcc447-shared/include you can find many files, including H5cpp.h.
- I have tried installing hdf5 from the sourcefiles according to their instructions. The instruction seemed to go ok and a got a folder ...blasr_install/hdf5-1.8.18    . This folder however doesn't include lib nor include, and I don't know how to adapted the step by step instructions to this alternative way of setting hdf5 up. Just running the commands again doesn't succeed.
-  Some suggestions include editing various lines in the make files. But I'm a bit unsure of which. There are non in hdf5... In blasr I got makefile, sub.mk and configure.py which could be interesting.  HDF5 is only mentioned once in makefile, and not in a way I can change to anything meaningful. Many of the instructions are unclear one exactly were to do what. Including using make on hdf5 (but that doesn't exist?).
- One suggest that it might be a mix up between using absolute and relative path. Seems like this could be it, but I don't understand how to solve it if such was the case. The only hint I have is to insert HDF5_INC=absolute-path after configure.py     . I tried but failed but I suspect it's because I don't know how to do so correctly.

**Comment by vrainish-pacbio** [comment]
Please, enter

**pwd** ( it will simply print your current directory, nothing else )

then 
 
**TOP=$(pwd)** ( it will assign current directory to shall variable TOP)

then 

**echo $TOP**  (it will print the content of shell variable TOP ( pay attention, don't miss dollar sign, that's how you access shell variables)

output of **pwd** command and **echo $TOP** should be the same

**Comment by Gaussia** [comment]
Thank you.

I misinterpreted 
`TOP=$(pwd)`
`#e.g. /home/username`
In the instruction that something should be replaced with /home/username (with my own name instead of "username" of course). Now I understand. But it should make no difference since pwd gave the output:
`/home/username`
the same I replaced pwd with in the command.

To try I re did everything from scratch using 
`TOP=$(pwd)`
but the result is unfortunately still the same error.

**Comment by ylipacbio** [comment]
Hi @Gaussia,

We recommend to install blasr via pitchfork. Please give pitchfork a try, which is convenient and easy to use.

https://github.com/PacificBiosciences/blasr/wiki/Blasr-Installation-Qs-&-As#answer

**Comment by Gaussia** [comment]
Thank you.

I will try as soon as possible when I get access to my computer again after the holiday.

**Comment by ylipacbio** [comment]
Close this issue now. Feel free to reopen it if you have any further questions.
