### ISSUE TITLE
Compatible version with pbtranscript-tofu

### ISSUE THREAD

**Issue by henryxushi** [PacificBiosciences/blasr#310]
I am using pbtranscript-tofu to do the analysis. I have installed blasr V5.3. It seems that it is incompatible with pbtranscript-tofu, as pbtranscript-tofu still use single dash option, i.e. -nproc. I am wondering where I can find the 'old' version of blasr, which is compatible with pbtranscript-tofu. Thanks, Henry.

**Comment by mhsieh** [comment]
Do you need compatible version of pbalign as well?

**Comment by henryxushi** [comment]
I have figured it out. When I use blasr 1.3.1, it works without errors, which is in smrtanalysis2.3.0 package. In order to run pbtranscript-tofu, I think it is better to directly use the binary distribution in smrtanalysis2.3.0 package rather than installing the latest version.
