### ISSUE TITLE
New release tag?

### ISSUE THREAD

**Issue by ilovezfs** [PacificBiosciences/blasr#316]
Would you mind creating a new release tag? I'm one of the Homebrew maintainers, and noticed your latest release (2.2) says "Please prefer the master branch." Since we only distribute tagged releases in Homebrew, that's not advice we can follow in terms of downstream packaging unless we were to "invent" a version number that you didn't assign and choose a "random" revision from head.

Thanks!

**Comment by afif-elghraoui** [comment]
What I've been doing is looking at the blame for `Blasr.cpp` to see which commit updated the version string. For example, https://github.com/PacificBiosciences/blasr/blame/master/Blasr.cpp#L35

So 5.3 corresponds to https://github.com/PacificBiosciences/blasr/commit/1baabc8a14fc36d632cd9ee921f92d7fbed62dae . But I agree that it would be nice if they did `git tag 5.3` when they made that commit.

**Comment by ylipacbio** [comment]
@ilovezfs  I have made a tag called smrtanalysis-4.0.0, and it is the latest stable version, is that OK? Please let me know if you prefer the tag name to be called `5.3`.

**Comment by afif-elghraoui** [comment]
I know you didn't address me, but for Debian, it would be more helpful to have blasr's version (although having both doesn't hurt, either). I suspect that the Homebrew people and other packagers would prefer the same thing.

**Comment by ilovezfs** [comment]
@ylipacbio for Homebrew, the main issue is just that the version number be monotonically increasing so I'd defer to anyone else's preferences beyond that.

**Comment by ilovezfs** [comment]
@ylipacbio I have opened https://github.com/Homebrew/homebrew-science/pull/4254.

Note there are some significant issues with building and packaging on macOS so I have opened
https://github.com/PacificBiosciences/blasr/issues/321
https://github.com/PacificBiosciences/blasr/issues/322

**Comment by armintoepfer** [comment]
Hi! I added cmake support that works like a charm on MacOS using homebrew's dependencies. Please give it a try and let me know how it went

**Comment by armintoepfer** [comment]
I'm talking to the right people about creating the correct tag.
Meanwhile, I've edited the blasr.rb to support support for HEAD using `cmake` https://github.com/armintoepfer/homebrew-science/commit/b890827aa03a94c1557d49de803169e745dcdf71

**Comment by ilovezfs** [comment]
I'm seeing
```
-- Build files have been written to: /tmp/blasr-20170216-10700-149r5i4
==> make install
make: *** No rule to make target `install'.  Stop.
```

**Comment by winni2k** [comment]
Tags please.  

On [bioconda](https://bioconda.github.io/recipes/blasr/README.html) I can download blasr version `5.3.9c6f0a5` and `5.3.f8bfa9c`.  Can anyone tell me which one is newer?

**Comment by 0xaf1f** [comment]
> Tags please.

Looks like this won't happen, if
https://github.com/PacificBiosciences/pbbam/issues/10#issuecomment-335546898 is any indication

> On bioconda I can download blasr version 5.3.9c6f0a5 and 5.3.f8bfa9c. Can anyone tell me which one is newer? (without cloning the repo and inspecting with git)
>
> It looks like conda thinks it's 5.3.9c6f0a5...

This looks like a bioconda problem in how it deals with the versioning here.
In Debian, we take care of this sort of problem by rewriting the version string so that they can be properly compared, like using a date string: 5.3+20171025.

**Comment by winni2k** [comment]
> This looks like a bioconda problem in how it deals with the versioning here.

True.  Conda is a whole other can of worms...

It appears that [bwa-mem](https://github.com/lh3/bwa) has a PacBio aware mapping mode (`-x pacbio`) and is easy to get a hold of, so I'll just use that ¯\_(ツ)_/¯

**Comment by 0xaf1f** [comment]
Or [ngm-lr](https://github.com/philres/ngmlr) or [minimap2](https://github.com/lh3/minimap2)

**Comment by armintoepfer** [comment]
Done.
