### ISSUE TITLE
Blasr output error!!!

### ISSUE THREAD

**Issue by linglingtingfei** [PacificBiosciences/blasr#317]
Hello There,
I came across a problem shown on screenshot at below. chrM_filtered.fa.txt should be output file, I don't know why it said No such file or directory there? It seems that blasr output uncorrectedly. Any help will be appreciated.
My code: `ncrna_pipeline -f /zs32/data-analysis/liucy_group/llhuang/PacBio-publicdata/Aizheimer-data/Alzheimer_final_confident/chrM.fasta -p 3 -c cpat -o human`
Error:
![image](https://cloud.githubusercontent.com/assets/20789616/21334645/e5de0ed6-c693-11e6-84e8-bdadc52c0d72.png)
![image](https://cloud.githubusercontent.com/assets/20789616/21334647/eb91dd1c-c693-11e6-8b2c-3465ef6fc647.png)

**Comment by ylipacbio** [comment]
Please provide the specific BLASR command that has been used, thanks. There is not enough info in the screenshot of a third-party pipeline building upon BLASR.

**Comment by armintoepfer** [comment]
Closing as there hasn't been feedback in a month.
