### ISSUE TITLE
difference blasr output in two fasta file

### ISSUE THREAD

**Issue by linglingtingfei** [PacificBiosciences/blasr#318]
Hi There,
Anyone can help me to resolve the problem(shown on screenshot), Why it doesn't work for /gencode.v19.pc_transcripts.fa but does work for /gencode.v19.lncRNA_transcripts.fa?
My code: ` ncrna_pipeline -f chrM.fasta -p 3 -c cpat -o human`
Anyone used to LncRNA Pipeline developed by Alberto Arrigoni? What is the final output?

Error:
![image](https://cloud.githubusercontent.com/assets/20789616/21337634/047809e4-c6aa-11e6-9765-32ea131039c4.png)

**Comment by ylipacbio** [comment]
This sounds like a ncrna_pipeline problem.
I will close this issue now. Feel free to reopen it with *specific BLASR commands* that have been used, as well as input files if needed.
