### ISSUE TITLE
make blasr error

### ISSUE THREAD

**Issue by saadabrar12** [PacificBiosciences/blasr#320]
I was having problems installing Blasr in my system. My Ubuntu Version is Ubuntu 16.04.1 LTS. TIA

**saad@Mercenary:~/blasr_install/blasr$ make blasr
g++ -o blasr -O3 -g -DSHA1_7=\"8d086d7\" -std=c++0x -pedantic -Wall -Wextra -Wno-div-by-zero -Wno-overloaded-virtual -MMD -MP -fno-builtin-malloc -fno-builtin-calloc -fno-builtin-realloc -fno-builtin-free -fno-omit-frame-pointer  -I/home/saad/blasr_install/blasr/libcpp/alignment -I/home/saad/blasr_install/blasr/libcpp/hdf -I/home/saad/blasr_install/blasr/libcpp/pbdata -I/home/saad/blasr_install/hdf5/hdf5-1.8.16-linux-centos6-x86_64-gcc447-shared/include/ -MF"blasr.d" Blasr.o -L/home/saad/blasr_install/blasr/libcpp/alignment -L/home/saad/blasr_install/blasr/libcpp/hdf -L/home/saad/blasr_install/blasr/libcpp/pbdata -L/home/saad/blasr_install/hdf5/hdf5-1.8.16-linux-centos6-x86_64-gcc447-shared/lib/ -lpbihdf -lblasr -lpbihdf -lpbdata  -lhdf5_cpp -lhdf5   -lz -lrt -lpthread -ldl
/home/saad/blasr_install/blasr/libcpp/hdf/libpbihdf.so: undefined reference to `H5::H5Location::iterateAttrs(void (*)(H5::H5Location&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, void*), unsigned int*, void*)'
/home/saad/blasr_install/blasr/libcpp/hdf/libpbihdf.so: undefined reference to `H5::CommonFG::createGroup(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, unsigned long) const'
/home/saad/blasr_install/blasr/libcpp/hdf/libpbihdf.so: undefined reference to `H5::CommonFG::getObjnameByIdx[abi:cxx11](unsigned long long) const'
/home/saad/blasr_install/blasr/libcpp/hdf/libpbihdf.so: undefined reference to `H5::Attribute::write(H5::DataType const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const'
/home/saad/blasr_install/blasr/libcpp/hdf/libpbihdf.so: undefined reference to `H5::Attribute::read(H5::DataType const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) const'
/home/saad/blasr_install/blasr/libcpp/hdf/libpbihdf.so: undefined reference to `H5::Exception::getDetailMsg[abi:cxx11]() const'
collect2: error: ld returned 1 exit status
makefile:63: recipe for target 'blasr' failed
make: *** [blasr] Error 1

**Comment by pb-cdunn** [comment]
I think your HDF5 was built with a different C++ ABI than you are using when you build blasr.

**Comment by mjhsieh** [comment]
hdf5-1.8.16-linux-centos6-x86_64-gcc447-shared is not usable with ubuntu16's g++ .

**Comment by saadabrar12** [comment]
What can be done to solve the problem? Could you please guide through it?

**Comment by mjhsieh** [comment]
Which document did you follow to build blasr?

**Comment by saadabrar12** [comment]
https://github.com/PacificBiosciences/blasr/wiki/Step-by-step-blasr-installation-example

**Comment by mjhsieh** [comment]
First of all, do you have admin permission in your ubuntu16 machine?

**Comment by mjhsieh** [comment]
If you have the admin permission, please do this `sudo apt-get install libhdf5-dev`

**Comment by saadabrar12** [comment]
Yes. I have already installed HDF5.

**Comment by mjhsieh** [comment]
please remove the extracted hdf5 file by doing
```
rm -rf blasr_install/hdf5
```
then clean up the incomplete compilation artifacts
```
cd blasr_install/blasr
git clean -xdf
cd ..
```
then change the configuration option to
```
./configure.py --shared --sub --no-pbbam HDF5_INCLUDE=/usr/include/ HDF5_LIB=/usr/lib/
```
and follow the rest of the recipe with `export LD_LIBRARY_PATH=${TOP}/blasr_install/blasr/libcpp/alignment:${TOP}/blasr_install/blasr/libcpp/hdf:${TOP}/blasr_install/blasr/libcpp/pbdata`

See if that works.

**Comment by saadabrar12** [comment]
Still the same problem. 

saad@Mercenary:~/blasr_install/blasr$ make blasr 
g++ -O3 -g -DSHA1_7=\"8d086d7\" -std=c++0x -pedantic -Wall -Wextra -Wno-div-by-zero -Wno-overloaded-virtual -MMD -MP -fno-builtin-malloc -fno-builtin-calloc -fno-builtin-realloc -fno-builtin-free -fno-omit-frame-pointer  -I/home/saad/blasr_install/blasr/libcpp/alignment -I/home/saad/blasr_install/blasr/libcpp/hdf -I/home/saad/blasr_install/blasr/libcpp/pbdata -I/usr/include/  -c -o Blasr.o Blasr.cpp
In file included from /home/saad/blasr_install/blasr/libcpp/alignment/files/../../hdf/HDFBasReader.hpp:18:0,
                 from /home/saad/blasr_install/blasr/libcpp/alignment/files/ReaderAgglomerate.hpp:14,
                 from iblasr/BlasrHeaders.h:79,
                 from iblasr/BlasrMiscs.hpp:4,
                 from Blasr.cpp:3:
/home/saad/blasr_install/blasr/libcpp/alignment/files/../../hdf/HDFArray.hpp:7:19: fatal error: H5Cpp.h: No such file or directory
compilation terminated.
<builtin>: recipe for target 'Blasr.o' failed
make: *** [Blasr.o] Error 1

**Comment by mjhsieh** [comment]
Okay I think you might need to remove blasr directory and do it again since this doesn't look clean to me. basically ```rm -rf blasr_install/blasr``` and redo from the `git clone` step.

**Comment by saadabrar12** [comment]
Now its displaying error in building the sub module.

BufferedHDFArray.hpp:10:18: fatal error: hdf5.h: No such file or directory
compilation terminated.
/home/saad/blasr_install/blasr/libcpp/hdf//../rules.mk:20: recipe for target 'BufferedHDFArray.o' failed
make[3]: *** [BufferedHDFArray.o] Error 1
make[3]: Leaving directory '/home/saad/blasr_install/blasr/libcpp/hdf'
makefile:21: recipe for target 'libpbihdf' failed
make[2]: *** [libpbihdf] Error 2
make[2]: Leaving directory '/home/saad/blasr_install/blasr/libcpp'
makefile:8: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/home/saad/blasr_install/blasr/libcpp'
makefile:54: recipe for target 'build-submodule' failed
make: *** [build-submodule] Error 2

**Comment by mjhsieh** [comment]
Okay, this time I really booted my ubuntu16 box and found that the HDF5_INCLUDE should be
/usr/include/hdf5/serial and HDF5_LIB should /usr/lib/x86_64-linux-gnu

**Comment by mjhsieh** [comment]
also I think the recipe should use HDF5_INC instead of HDF5_INCLUDE, let me fix that.

**Comment by mjhsieh** [comment]
I did fix my previous instruction and tested in https://youtu.be/mqVTEM_M4jk
