### ISSUE TITLE
dylib should set install names and rpaths based on prefix

### ISSUE THREAD

**Issue by ilovezfs** [PacificBiosciences/blasr#321]
For Homebrew, I'm ending up needing to do some gymnastics to get blasr (4.0.0 tag) to install properly:
```
    system "./configure.py", "--sub",
                             "--no-pbbam",
                             "--shared",
                             "HDF5_INCLUDE=#{Formula["hdf5"].opt_include}",
                             "HDF5_LIB=#{Formula["hdf5"].opt_lib}"
    system "make", "configure-submodule"
    system "make", "build-submodule"
    system "make"
    %w[libcpp/alignment/libblasr.dylib libcpp/pbdata/libpbdata.dylib
       libcpp/hdf/libpbihdf.dylib].each do |f|
      lib_name = Pathname.new(f).basename.to_s
      MachO::Tools.change_install_name("blasr", lib_name, "#{lib}/#{lib_name}")
      lib.install f
    end
    bin.install "blasr"
```

It would be good if configure took `--prefix=` and there were a `make install` that could handle the dylib install names and rpaths without my having to resort to using the ruby `MachO` library or to using `/usr/bin/install_name_tool`.

**Comment by mjhsieh** [comment]
it might be easier if you can look at [pitchfork](https://github.com/PacificBiosciences/pitchfork/) and see if you can see if I already solved it in different way.

**Comment by armintoepfer** [comment]
We won't support source builds from now on, but provide the latest version on bioconda:
`conda install -c bioconda blasr`
