### ISSUE TITLE
writing to sam or bam

### ISSUE THREAD

**Issue by dorothyeloy** [PacificBiosciences/blasr#324]
I downloaded Blasr yesterday and have been trying to get it to print the output to a bam or sam file.  Each time I get an error like : ERROR: -sam is not a valid option.  I have tried --sam --bam -sam and -bam.
None of the following have worked:
blasr pacbioreads.fasta genome.fasta --sam 
blasr pacbioreads.fasta genome.fasta --out pacbio_to_genome.sam
blasr pacbioreads.fasta genome.fasta --sam --out pacbio_to_genome.sam

And I tried all the above with -sam, --bam, and -bam instead of --sam.  The second one ran but did not make a .sam file, all others gave the above error.  Any suggestions?  Thanks!

**Comment by RxLoutre** [comment]
I have the exact same problem for days... And that's blocking the right use of pbalign because this problem within blasr is still insolved...

**Comment by mhsieh** [comment]
You now need pbbam for --sam option, so if you are working on ba[s,x].h5 files or just dealing with fasta files, you may well just get the older blasr from your smrtanalysis 2.3.0p5 installation.

**Comment by RxLoutre** [comment]
What is pbbam ? A kind of patch so we can use blasr with --sam option ? Or it a tool that I will use like this : `pbbam  pacbioreads.fasta genome.fasta --sam` and then you will align reads to your assembly ?
Where can I download (and find installation instructions) an older version of blasr ?

**Comment by ylipacbio** [comment]
The latest BLASR should be able to produce SAM/BAM outputs as long as inputs are *VALID* pacbio reads. Here is a concrete example.

https://github.com/PacificBiosciences/blasr/wiki/BLASR-Frequently-Asked-Questions#can-blasr-produce-sambam-output-when-input-is-a-fasta-file

**Comment by armintoepfer** [comment]
Please install via pitchfork or cmake to get blasr with pbbam support. Or get the official smrtanalysis build from PacBio that contains blasr.
