### ISSUE TITLE
STDIN

### ISSUE THREAD

**Issue by chkcole** [PacificBiosciences/blasr#325]
Question:
Is is possible to get blasr to read from stdin?
I have a huge bam file sitting on a remote ftp server and I want to align it using blasr but I don't want to actually have the entire thing present on my computer.
I was planning on using `samtools fasta` to pipe it from the server into an aligner and then have the aligner write to a file.
since my reference is only a few percent of the organisms actual genome, the sam file will only contain a small portion of the total reads.
any help would be appreciated.

**Comment by ylipacbio** [comment]
BLASR does not support reading from stdin. Input has to be a file.
