### ISSUE TITLE
Make errors

### ISSUE THREAD

**Issue by jinshui0202** [PacificBiosciences/blasr#326]
Hi everyone,
Some errors as followed when "make blasr"':
```cpp
iblasr/BlasrUtilsImpl.hpp:968:15: error: ‘T_AlignmentCandidate’ has no member named ‘MakeQueryForward’
.....
iblasr/BlasrAlignImpl.hpp:612:35: error: no match for ‘operator<<’ (operand types are ‘std::basic_ostream<char>’ and ‘const WeightedInterval’)
.....
iblasr/BlasrAlignImpl.hpp:757:68: error: use of ‘AlignIntervals(T_TargetSequence&, T_QuerySequence&, T_QuerySequence&, WeightedIntervalSet&, int (*)[5], int, int, int, int, SequenceIndexDatabase<TDBSequence>&, std::vector<AlignmentCandidate<DNASequence, FASTQSequence>*>&, MappingParameters&, MappingBuffers&, int) [with T_TargetSequence = FASTASequence; T_QuerySequence = SMRTSequence; TDBSequence = FASTQSequence]::__lambda1’ before deduction of ‘auto’
         ConfigureQuery(alignment->qStrand == Forward ? read: rcRead);
                                                                    ^
iblasr/BlasrAlignImpl.hpp:757:68: error: invalid use of ‘auto’
```

**Comment by jjohnire** [comment]
I am seeing the same problem:

$ fgrep error make.out 
iblasr/BlasrAlignImpl.hpp:264:62: error: no match for ‘operator<<’ (operand types are ‘std::basic_ostream<char>’ and ‘const WeightedInterval’)
iblasr/BlasrUtilsImpl.hpp:968:15: error: ‘T_AlignmentCandidate’ has no member named ‘MakeQueryForward’
iblasr/BlasrAlignImpl.hpp:612:35: error: no match for ‘operator<<’ (operand types are ‘std::basic_ostream<char>’ and ‘const WeightedInterval’)
iblasr/BlasrAlignImpl.hpp:757:68: error: invalid use of ‘auto’

**Comment by armintoepfer** [comment]
My guess, you are using an ancient c++ compiler that doesn't support C++11

**Comment by jinshui0202** [comment]
My gcc version is 4.8.5. The OS is centos 7.

**Comment by jjohnire** [comment]
I have tried both gcc version 4.8.5 & 4.9.3 on Scientific Linux release 7.2

**Comment by jinshui0202** [comment]
Actually, this tool is very very difficult to complie. I have tried several times, but was failed every time. But it is a very import tool for deail with PacBio data...

**Comment by ressy** [comment]
Oddly enough, I ran into this same thing on Friday, on Ubuntu 16 LTS with GCC 5.4.0.  I had been able to build blasr just fine a few weeks ago, so I figure something must have changed, but so far I haven't been able to build it by checking out other recent commits either.

**Comment by armintoepfer** [comment]
The blasr-libcpp submodule sha1 hasn't been updated. We'll fix that asap.

**Comment by mhsieh** [comment]
@jinshui0202 you might want to try pitchfork or wait for Armin's recipe to be merged into the source tree.

**Comment by jjohnire** [comment]
All now compiles. Thanks!
