### ISSUE TITLE
compilation bax2bam fails

### ISSUE THREAD

**Issue by ebioman** [PacificBiosciences/blasr#327]
Hello
I am trying to follow the instruction to compile bax2bam. Blasr itself worked well but this tool
is a little bit more tricky.

I succeed with the make till this error:
<pre><code>
[ 86%] Building CXX object tests/CMakeFiles/test_bax2bam.dir/src/test_hqregions.cpp.o
/builddir/build/BUILD/blasr-8d086d747e51a409f25481524e92e99750b14d59/utils/bax2bam/tests/src/test_hqregions.cpp:7:43: fatal error: alignment/utils/RegionUtils.hpp: No such file or directory
 #include "alignment/utils/RegionUtils.hpp"
                                           ^
compilation terminated.
make[3]: *** [tests/CMakeFiles/test_bax2bam.dir/src/test_hqregions.cpp.o] Error 1
</code></pre>

I defined the variables according to the manual install instructions and have the following adjusted defines.mk

<pre><code>
HTSLIB_INC           ?= /software/UHTS/Analysis/HTSlib_PB/170119/include
HDF5_INC             ?= /software/include
PBBAM_INC            ?= /software/Development/Libraries/pbbam/0.7.4/include
CXXFLAGS             ?= -O3
LIBPBDATA_LIBFLAGS   ?= -lpbdata
LIBPBIHDF_LIB        ?= /software/Development/Libraries/blasr_libcpp/20170117/hdf
SHELL                ?= bash
LIBPBDATA_INC        ?= /software/Development/Libraries/blasr_libcpp/20170117/pbdata
LIBPBIHDF_INC        ?= /software/Development/Libraries/blasr_libcpp/20170117/hdf
RT_LIBFLAGS          ?= -lrt
ZLIB_LIBFLAGS        ?= -lz
HTSLIB_LIB           ?= /software/UHTS/Analysis/HTSlib_PB/170119/lib
PTHREAD_LIBFLAGS     ?= -lpthread
NOPBBAM              ?= 1
LIBBLASR_LIBFLAGS    ?= -lblasr
LIBPBDATA_LIB        ?= /software/Development/Libraries/blasr_libcpp/20170117/pbdata
HDF5_LIB             ?= /software/lib64
HDF5_LIBFLAGS        ?= -lhdf5_cpp -lhdf5
DL_LIBFLAGS          ?= -ldl
LIBPBIHDF_LIBFLAGS   ?= -lpbihdf
LIBBLASR_INC         ?= /software/Development/Libraries/blasr_libcpp/20170117/alignment
LIBBLASR_LIB         ?= /software/Development/Libraries/blasr_libcpp/20170117/alignment
PBBAM_LIB            ?= /software/Development/Libraries/pbbam/0.7.4/lib64

BOOST_INC := /software/include/boost
BOOST_ROOT := /software/lib64
PPBAM_ROOTDIR := /software/Development/Libraries/pbbam/0.7.4/

# Always set SH_LIB_EXT to .a
SH_LIB_EXT ?= .a 
</code></pre>

This was generated based on the defines.mk from a successful blasr build and complemented accordingly.
Any ideas what might be causing it?
Thanks

**Comment by ebioman** [comment]
Hmm
So I found in the test/src that there are some include which add  the entire pathname.
E.g.


    #include "HDFBasReader.hpp"
    #include "alignment/utils/RegionUtils.hpp"
    #include "hdf/HDFRegionTableReader.hpp"

Now the first and the 3rd are in the same folder defined by the variable LIBPBIHDF_INC but the 3rd has "hdf" added to the lookup.

 Fixing accordingly works in my case:

    sed -i  's|alignment/utils/RegionUtils.hpp|utils/RegionUtils.hpp|'  utils/bax2bam/tests/src/*.cpp
    sed -i  's|hdf/HDFRegionTableReader.hpp|HDFRegionTableReader.hpp|'  utils/bax2bam/tests/src/*.cpp

I encountered similar issues with bam2bax but did not bother there as I dont need it.
I hope this helps somebody running in the same issue...

**Comment by mhsieh** [comment]
bax2bam build should be a cmake operation, thus `defines.mk` is not used. What was your cmake argument?

**Comment by ebioman** [comment]
@mjhsieh  thanks for the feedback. I followed your guideline from [here](https://github.com/PacificBiosciences/blasr/wiki/INSTALL-bax2bam-without-using-pitchfork-%28not-recommended%29)
which asks to define the defines.mk as I did above and then build with the following command:

    cd <abs_path_to>/blasr/utils/bax2bam && make 

And indeed the is a make-file which imports the variables from the defines.mk:

    SRCDIR:=$(dir $(realpath $(lastword $(MAKEFILE_LIST))))
    include ${CURDIR}/../../defines.mk
    include ${SRCDIR}/../../rules.mk

It is strange as it then in the makefile essentially calls cmake and imports the environmental variables:

<pre><code>
all: ${CURDIR}/src/* ${CURDIR}/tests/src/*
	@mkdir -p ${CURDIR}/build && \
	 cd ${CURDIR}/build && \
		cmake -DBOOST_ROOT=${BOOST_ROOT} \
          -DPacBioBAM_INCLUDE_DIRS=${PBBAM_INC} \
          -DHTSLIB_INCLUDE_DIRS=${HTSLIB_INC} \
          -DPacBioBAM_LIBRARIES=${PBBAM_LIB}/libpbbam${SH_LIB_EXT} \
          -DHTSLIB_LIBRARIES=${HTSLIB_LIB}/libhts${SH_LIB_EXT} \
          -DPBDATA_INCLUDE_DIRS=${LIBPBDATA_INC} \
          -DPBDATA_LIBRARIES=${LIBPBDATA_LIB}/libpbdata${SH_LIB_EXT} \
          -DPBIHDF_INCLUDE_DIRS=${LIBPBIHDF_INC} \
          -DPBIHDF_LIBRARIES=${LIBPBIHDF_LIB}/libpbihdf${SH_LIB_EXT} \
          -DBLASR_INCLUDE_DIRS=${LIBBLASR_INC}/ \
          -DBLASR_LIBRARIES=${LIBBLASR_LIB}/libblasr${SH_LIB_EXT} \
          -DHDF5_INCLUDE_DIRS=${HDF5_INC} \
          -DHDF5_CPP_LIBRARIES=${HDF5_LIB}/libhdf5_cpp${SH_LIB_EXT} \
          -DHDF5_LIBRARIES=${HDF5_LIB}/libhdf5${SH_LIB_EXT} \
          -DBax2Bam_EXE_LINKER_FLAGS="-Wl,--no-as-needed -ldl -pthread -lrt " \
          ../ && \
		make

</code></pre>

**Comment by ylipacbio** [comment]
Thank you @ebioman, I will fix the tests.

The makefile serves as a easy way to build bax2bam for users who have successfully built blasr using makefile and defines.mk.

We will simplify the CMakefile for github users.
