### ISSUE TITLE
bax2bam fails to process files in fofn when they contain space

### ISSUE THREAD

**Issue by potapovneb** [PacificBiosciences/blasr#328]
When files inside a FOFN (File-of-file-names) contain spaces, bax2bam fails to process them correctly:
```bash
$ bax2bam --version
0.0.8

$ cat input.fofn
/mnt/pacbio/primary/test sample/A01_1/Analysis_Results/m160303_031756_42200_c100992392550000001823224707191660_s1_p0.1.bax.h5
/mnt/pacbio/primary/test sample/A01_1/Analysis_Results/m160303_031756_42200_c100992392550000001823224707191660_s1_p0.2.bax.h5
/mnt/pacbio/primary/test sample/A01_1/Analysis_Results/m160303_031756_42200_c100992392550000001823224707191660_s1_p0.3.bax.h5

$ bax2bam --fofn=input.fofn -o movie
ERROR, could not open hdf file/mnt/pacbio/primary/test, exiting.
```

Running directly from the command line and escaping spaces works fine:
```bash
$ bax2bam /mnt/pacbio/primary/test\ sample/A01_1/Analysis_Results/m160303_031756_42200_c100992392550000001823224707191660_s1_p0.1.bax.h5 -o movie
```

**Comment by ylipacbio** [comment]
File paths with space is generally NOT supported by SMRTAnalysis tools, including bam2bax.
Please rename the directory and remove spaces from file paths.

**Comment by ylipacbio** [comment]
My personal experience is that one little space within a file path would break almost all pipelines at so many places -- it is a big trouble, but luckily can be handled easily by renaming the directory.

**Comment by potapovneb** [comment]
The output path for PacBio sequencing data is defined based on sample name (at least for RSII instrument), which users manually enter before starting a sequencing run:
```bash
/mnt/pacbio/primary/${SampleName}/...
```
It might be helpful to replace all spaces in the sample name automatically so that does not corrupt the downstream analysis. So far, there are no restrictions on how the sample can be named thus such situations can be quite frequent.

On RSII instrument, at least RS_Resequencing protocol works fine with filenames containing spaces. This is why I was surprised when bax2bam from SMRTLink failed to process such FOFNs.

**Comment by ylipacbio** [comment]
RS_Resequencing initially didn't work and then was modified to support file paths with space later (and I was the assignee).

But supporting file paths with space was not a requested feature for SMRTLink software in general. And to my knowledge, there is no guarantee file paths with space would work with SMRTLink 4.0 pipelines, except the resequencing workflow (thanks to efforts by Nat).
