### ISSUE TITLE
Installation Error with Blasr on mac

### ISSUE THREAD

**Issue by MalikS10** [PacificBiosciences/blasr#330]
Hi I ran the following commands:

git clone git://github.com/PacificBiosciences/blasr.git && cd blasr
    git submodule update --init --remote
    mkdir build && cd build
    cmake .. && make

I get the following error:

Scanning dependencies of target toAfg
[ 55%] Building CXX object CMakeFiles/toAfg.dir/utils/ToAfg.cpp.o
make[2]: *** No rule to make target `external/pbbam/build/lib/libpbbam.a', needed by `toAfg'.  Stop.
make[1]: *** [CMakeFiles/toAfg.dir/all] Error 2
make: *** [all] Error 2

Thanks for your help!

**Comment by armintoepfer** [comment]
Would you mind installing via ninja? I'll remove the make way, it's too slow and will complicate the cmake files. Please let me know if it works via ninja

**Comment by MalikS10** [comment]
ok so I used 
cmake -GNinja .. && ninja
And it seemed to work , then I added the blasr executable to my path. Is this the right way? Should I be doing something else after this?

**Comment by armintoepfer** [comment]
If you run `ninja install` it will install blasr to your global bin directory or you do it your way, which is totally fine. As long it works, fine :)

**Comment by MalikS10** [comment]
I think its working ... Thanks Armin!

**Comment by ebriars** [comment]
Hi there,

I am trying to install Blasr and ran the same cmake commands as MalikS10 but got the same error:

> Scanning dependencies of target toAfg
[ 55%] Building CXX object CMakeFiles/toAfg.dir/utils/ToAfg.cpp.o
make[2]: *** No rule to make target external/pbbam/build/lib/libpbbam.a', needed bytoAfg'. Stop.
make[1]: *** [CMakeFiles/toAfg.dir/all] Error 2
make: *** [all] Error 2

After seeing this issue I followed what MalikS10 did and then tried `make -GNinja .. && ninja`, but was getting the warning

> clang: warning: argument unused during compilation: '-MMD'", 

and then a failure message 

> [251/254] Linking CXX executable toAfg
FAILED: toAfg 
: && /Library/Developer/CommandLineTools/usr/bin/c++   -std=c++11 -pedantic -Wno-long-long -Wall -Wextra -Wno-return-type -Wno-overloaded-virtual -Wno-unused-parameter -Wno-div-by-zero -MMD -MP -fno-builtin-malloc -fno-builtin-calloc -fno-builtin-realloc -fno-builtin-free -fno-omit-frame-pointer -Wno-unused-variable -Wno-unused-local-typedefs -DUSE_PBBAM -DCMAKE_BUILD -O3 -DNDEBUG -Wl,-search_paths_first -Wl,-headerpad_max_install_names  CMakeFiles/toAfg.dir/utils/ToAfg.cpp.o  -o toAfg  libdeps.a -lhdf5 -lhdf5_cpp external/pbbam/build/lib/libpbbam.a external/pbbam/build/external/htslib/libhts.a /usr/lib/libz.dylib && :
ld: library not found for -lhdf5
clang: error: linker command failed with exit code 1 (use -v to see invocation)
[253/254] Building CXX object CMakeFiles/blasr.dir/Blasr.cpp.o
clang: warning: argument unused during compilation: '-MMD'
ninja: build stopped: subcommand failed.

I'm not sure where to go from here and any help would be appreciated!

**Comment by armintoepfer** [comment]
1) You can ignore warnings.
2) Either run `make -j` twice or use ninja

> ld: library not found for -lhdf5
Do you have hdf5 installed? Did you follow the instructions for mac?
