### ISSUE TITLE
read ID changed after blasr

### ISSUE THREAD

**Issue by fang88888** [PacificBiosciences/blasr#333]
hi all;
    before alignmenting my reads to reference, the read id is m54051_161204_023707/10027676/0_5726; but after aligement the reads to reference by blasr the id is m54051_161204_023707/10027676/0_5555; how can I get the original read id ?
 Looking forward to receiving your early reply.

**Comment by ylipacbio** [comment]
Would you please provide input file type and CMD line? Thanks
