### ISSUE TITLE
ConsensusTools.sh CircularConsensus

### ISSUE THREAD

**Issue by smm19900210** [PacificBiosciences/blasr#334]
I used bam2bax convert from bam to bax, and then use the command "ConsensusTools.sh CircularConsensus --minFullPasses 0 --minPredictedAccuracy 75 --parameters /share/nas2/genome/biosoft/smrtanalysis/smrtanalysis/current/analysis/etc/algorithm_parameters/2014-09 --numThreads 10 --fofn test.fofn -o ccs --zmwStart=0 --zmwCount=1000"
but it happened error, error message as below:
Unhandled Exception:
System.Exception: Unrecognized PlatformId in ScanData/RunInfo
  at PacBio.IO.MetadataReader.GetMetadataReader (IGroup scanData, IGroup zmwGroup) [0x00057] in /home/NANOFLUIDICS/build/workspace/S2.3_smrtanalysis_libc-2.5_centos-53/software/smrtanalysis/bioinformatics/lib/dotnet/PacBio.IO/MetadataReader.cs:135 
  at PacBio.IO.ReaderBase`1[PacBio.IO.IZmwBases].Init (System.String dataGroupName) [0x0009d] in /home/NANOFLUIDICS/build/workspace/S2.3_smrtanalysis_libc-2.5_centos-53/software/smrtanalysis/bioinformatics/lib/dotnet/PacBio.IO/ReaderBase.cs:104

**Comment by ylipacbio** [comment]
* To call consensus, please use `variantCaller` in package https://github.com/PacificBiosciences/GenomicConsensus
 * `variantCaller` takes bam files as input, `bam2bax` is not needed

**Comment by nlhepler** [comment]
Even more to the point, ConsensusTools.sh is part of SMRTPortal (2.3), bam2bax is part of SMRTLink (3+) (and honestly is an internal tool only, completely unsupported to the outside).

Using it in this way, to put PacBioBAM data through older tools is *absolutely* unsupported behavior. Our tools are not forwards compatible. If you need to do ccs, use ccs as part of pitchfork.

**Comment by smm19900210** [comment]
thanks nlhepler and ylipacbio, i have another question, my input file is ccs.bam format, how can i get these files: fulllength_nonchimeric_readlength_hist.png, isoseq_classify.html, isoseq_classify.json, reads_of_insert_report.html, reads_of_insert_report.json, roi_accuracy_hist.png, roi_npasses_hist.png, roi_readlength_hist.png.  these files are produced by reads_of_insert_report.py and smrtreporter of SMRTPortal (2.3)
