### ISSUE TITLE
"Aborted (core dumped)" with BAM formatted input

### ISSUE THREAD

**Issue by malonge** [PacificBiosciences/blasr#335]
Hi,

I am using pbalign for downstream polishing with quiver. These tools require that I use BAM format for my raw input data, so I used bax2bam to convert my bax.h5 files to BAM files.

However, pbalign now fails because blasr fails. Running blasr standalone, I get the following error: 

```
$ sh run_blasr
[INFO] 2017-02-27T16:01:38 [blasr] started.
run_blasr: line 1: 31537 Aborted                 (core dumped) blasr --nproc 10 data/m161026_005600_00120_c101082802550000001823240502241724_s1_p0.subreads.bam 7500_100_125_4.p_ctg.fasta --out alignments.bam --sa 7500_100_125_4.p_ctg.fasta.sa
```

The program runs for a while and begins writing to the output BAM file before it crashes. This makes me think that it is an input data related problem, especially given that I converted these files from bax.h5.

To do this covnersion, I used the following command:

```
bax2bam movie.1.bax.h5 movie.2.bax.h5 movie.3.bax.h5 --subread --pulsefeatures=DeletionQV,DeletionTag,InsertionQV,IPD,MergeQV,SubstitutionQV,PulseWidth,SubstitutionTag
```

And for this test, I used a single "subreads.bam" file produced from the above command. Do I also need to use the "scraps.bam" and "subreads.bam.bpi" file? 

Thanks

**Comment by ylipacbio** [comment]
with 
```bax2bam movie.1.bax.h5 movie.2.bax.h5 movie.3.bax.h5 --subread --pulsefeatures=DeletionQV,DeletionTag,InsertionQV,IPD,MergeQV,SubstitutionQV,PulseWidth,SubstitutionTag -o movie```, 
movie.subreads.bam and movie.scraps.bam should be generated.

To sanity check bam file generated from bax2bam, you may run 
```samtools view -h movie.subreads.bam > /dev/null```
```samtools view -h movie.scraps.bam > /dev/null```

**Comment by malonge** [comment]
Thank you I will check this. 

Regarding the two different BAM files, is one supposed to use both "scraps" and "subreads" for input into programs such as blasr?

**Comment by malonge** [comment]
I ran the test, and both the "scraps.bam" and "subreads.bam" do not cause an error when running samtools view.

Not surprisingly, when running samtools view on the partial blasr output, I get the following error.

```
[W::sam_read1] parse error at line 1
[main_samview] truncated file.
```

**Comment by ylipacbio** [comment]
just use the `subreads.bam` for input into blasr, and leave scraps.bam in the same directory as subreads.bam because blasr sometimes may access it for more info (although you don't have to explictly specify the file path).

**Comment by malonge** [comment]
I tried just using the subreads.bam file as you suggested and still got the same error. I also tried using a different reference just to rule that out and that also failed. Doesn't look like I am running out of memory. 

Any other ideas why this might be happening?

**Comment by ylipacbio** [comment]
Try something simple first,
```bax2bam movie.1.bax.h5  --subread --pulsefeatures=DeletionQV -o movie```
try rebuilt your bax2bam tool (or install smartanlaysis directly)

If movie.subreads.bam file is still truncated, please report  your data and os environment to pacbio tech support.

The technical support team can be reached by email, phone, or online-form:  http://www.pacb.com/support/technical-support/

If you have more information to provide, please email support@pacificbiosciences.com and attach any log files, images, or supplementary materials.
