### ISSUE TITLE
blasr Iso-Seq fasta output to transcript fasta sequences

### ISSUE THREAD

**Issue by splaisan** [PacificBiosciences/blasr#337]
(using version: blasr 5.3.5b30da0)

The original command from https://github.com/PacificBiosciences/cDNA_primer/wiki/Aligner-tutorial:-GMAP,-STAR,-BLAT,-and-BLASR is not working because of the --sam deprecation.
Replacing --sam by --bam does not work either as the input is fasta and not BAM format. How can this be corrected to make the Iso-Seq to known transcript comparison executable?

original command:
```
blasr Tyson_human_brain_2to3k.2seqs.fa gencode.v19.pc_transcripts.fa \
--nproc 24 --sam --out test.sam
```

modified failing command:
```
blasr Tyson_human_brain_2to3k.2seqs.fa gencode.v19.pc_transcripts.fa \
--nproc 24 --bam --out test.bam

[INFO] 2017-03-03T14:23:50 [blasr] started.
ERROR, can not convert non-pacbio reads to pbbam record.
```

Thanks

This appears to be a duplicate of the closed: https://github.com/PacificBiosciences/blasr/issues/312

**Comment by armintoepfer** [comment]
We recommend using gmap to map isoseq data

**Comment by splaisan** [comment]
I understand but it does not change the fact that blasr doe not work as expected with parameters explained in its manpage unless I did something wrong.
