### ISSUE TITLE
cmake/make failed with the error:No rule to make target 'external/pbbam/build/lib/libpbbam.a'

### ISSUE THREAD

**Issue by wangyugui** [PacificBiosciences/blasr#338]
Hi.

cmake/make failed with the error:No rule to make target 'external/pbbam/build/lib/libpbbam.a'
```
mkdir build && cd build && cmake .. && make
make[2]: *** No rule to make target 'external/pbbam/build/lib/libpbbam.a', needed by 'blasr'.  Stop.
```

**Comment by wangyugui** [comment]
we can continue to build with this command.

``
cd external/pbbam/build/  && make && cd ../../../
```

**Comment by armintoepfer** [comment]
https://github.com/PacificBiosciences/blasr/issues/330
