### ISSUE TITLE
cmake pbbam install error

### ISSUE THREAD

**Issue by rrlove** [PacificBiosciences/blasr#339]
After no luck installing blasr with make, I tried cmake. Running the following commands:

git clone git://github.com/PacificBiosciences/blasr.git && cd blasr
git submodule update --init --remote
mkdir build && cd build
cmake -DHDF5_ROOT=/afs/crc.nd.edu/user/r/rlove1/local/bin/hdf5-1.8.18/hdf5 .. && make

produces the error:

make[2]: *** [CMakeFiles/deps.dir/libcpp/alignment/files/ReaderAgglomerate.cpp.o] Error 1
make[1]: *** [CMakeFiles/deps.dir/all] Error 2
make: *** [all] Error 2

As per [Issue #330](url=https://github.com/PacificBiosciences/blasr/issues/330), I next started over and tried the make -j way. After:

git clone git://github.com/PacificBiosciences/blasr.git && cd blasr
git submodule update --init --remote
mkdir build && cd build
cmake -DHDF5_ROOT=/afs/crc.nd.edu/user/r/rlove1/local/bin/hdf5-1.8.18/hdf5 .. && make -j

I get the error:

make[2]: *** [CMakeFiles/deps.dir/libcpp/alignment/query/SequentialZmwGroupQuery.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[2]: *** [CMakeFiles/deps.dir/libcpp/alignment/format/SAMHeaderPrinter.cpp.o] Error 1
make[2]: *** [CMakeFiles/deps.dir/libcpp/alignment/query/PbiFilterZmwGroupQuery.cpp.o] Error 1
make[2]: *** [CMakeFiles/deps.dir/libcpp/alignment/files/ReaderAgglomerate.cpp.o] Error 1
make[1]: *** [CMakeFiles/deps.dir/all] Error 2
make: *** [all] Error 2

and after a second make -j:

make[2]: *** [external/pbbam/build/src/CMakeFiles/pbbam.dir/PbiIndex.cpp.o] Error 1
make[2]: *** [external/pbbam/build/src/CMakeFiles/pbbam.dir/VirtualZmwReader.cpp.o] Error 1
make[2]: *** [external/pbbam/build/src/CMakeFiles/pbbam.dir/PbiFilterQuery.cpp.o] Error 1
make[2]: *** [external/pbbam/build/src/CMakeFiles/pbbam.dir/ReadAccuracyQuery.cpp.o] Error 1
make[2]: *** [external/pbbam/build/src/CMakeFiles/pbbam.dir/ZmwReadStitcher.cpp.o] Error 1
make[2]: *** [external/pbbam/build/src/CMakeFiles/pbbam.dir/QNameQuery.cpp.o] Error 1
make[2]: *** [external/pbbam/build/src/CMakeFiles/pbbam.dir/EntireFileQuery.cpp.o] Error 1
make[2]: *** [external/pbbam/build/src/CMakeFiles/pbbam.dir/ZmwQuery.cpp.o] Error 1
make[2]: *** [external/pbbam/build/src/CMakeFiles/pbbam.dir/BarcodeQuery.cpp.o] Error 1
make[2]: *** [external/pbbam/build/src/CMakeFiles/pbbam.dir/ZmwGroupQuery.cpp.o] Error 1
make[2]: *** [external/pbbam/build/src/CMakeFiles/pbbam.dir/GenomicIntervalQuery.cpp.o] Error 1
make[2]: *** [external/pbbam/build/src/CMakeFiles/pbbam.dir/WhitelistedZmwReadStitcher.cpp.o] Error 1
make[2]: *** [external/pbbam/build/src/CMakeFiles/pbbam.dir/Validator.cpp.o] Error 1
make[2]: *** [external/pbbam/build/src/CMakeFiles/pbbam.dir/SubreadLengthQuery.cpp.o] Error 1
make[2]: *** [external/pbbam/build/src/CMakeFiles/pbbam.dir/PbiIndexedBamReader.cpp.o] Error 1
make[2]: *** [external/pbbam/build/src/CMakeFiles/pbbam.dir/PbiFilter.cpp.o] Error 1
make[2]: *** [external/pbbam/build/src/CMakeFiles/pbbam.dir/PbiIndexIO.cpp.o] Error 1
make[2]: *** [external/pbbam/build/src/CMakeFiles/pbbam.dir/PbiFilterTypes.cpp.o] Error 1
make[2]: *** [external/pbbam/build/src/CMakeFiles/pbbam.dir/VirtualZmwCompositeReader.cpp.o] Error 1
make[1]: *** [external/pbbam/build/src/CMakeFiles/pbbam.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
make[2]: *** [CMakeFiles/deps.dir/libcpp/alignment/format/SAMHeaderPrinter.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[2]: *** [CMakeFiles/deps.dir/libcpp/alignment/query/PbiFilterZmwGroupQuery.cpp.o] Error 1
make[2]: *** [CMakeFiles/deps.dir/libcpp/alignment/files/ReaderAgglomerate.cpp.o] Error 1
make[2]: *** [CMakeFiles/deps.dir/libcpp/alignment/query/SequentialZmwGroupQuery.cpp.o] Error 1
make[1]: *** [CMakeFiles/deps.dir/all] Error 2
make: *** [all] Error 2

In all 3 cases there are much longer error messages I can include if necessary. Do you have any suggestions as to what I can change?

Thanks.

**Comment by armintoepfer** [comment]
Try the ninja approach, if the others don't work for you

**Comment by rrlove** [comment]
I needed BAM support, so ended up installing via pitchfork.
