### ISSUE TITLE
new release with content of libcpp and pbbam

### ISSUE THREAD

**Issue by mictadlo** [PacificBiosciences/blasr#341]
Hi,
I downloaded `https://github.com/PacificBiosciences/blasr/archive/f8bfa9c5565ae01ea669af872edaae5e55471d98.tar.gz` but the `libcpp` and `pbbam` folders are empty.

(Bio)conda does not support `git submodule update --init --remote`. Are you able to create a release which contains the content of `libcpp` and `pbbam`. After this, we would be able to complete this Bioconda [reciepe](https://github.com/bioconda/bioconda-recipes/pull/4244).

Thank you in advance.

Michal

**Comment by armintoepfer** [comment]
We won't support source builds from now on, but provide the latest version on bioconda:
`conda install -c bioconda blasr`
