### ISSUE TITLE
Outputting the clusters and their scores in BLASR

### ISSUE THREAD

**Issue by Strideradu** [PacificBiosciences/blasr#342]
Hi there,

We have a question about outputting the clusters and their scores in blasr. We can successfully output two related files using parameters -anchors and -clusters. However, we cannot find detailed explanation about the output format. For example, how can we obtain the anchors inside the output clusters? And, where is the score for ranking the clusters? In the anchor output, all the last item is 1. Not sure whether it is the score for each anchor match?

It is worth mentioning that we are applying blasr for de novo assembly. Thus, we compare two reads using blasr. An example command is copied below:

> blasr pair2_query.fasta pair2_target.fa -minReadLength 2000 -maxScore 1000 -maxLCPLength 16 -m 0 -out ./pair2-blasr.out -bestn 150 -anchors ./pair2-anchor.out -clusters ./pair2-cluster.out

**Comment by mchaisso** [comment]
Hi,
  Is there a reason you need the anchors and/or clusters?  These are mainly for help optimize/debug blasr.   You may be able to get at your goal with the different alignment output formats.

-mark

**Comment by Strideradu** [comment]
Hi,

Thanks for your reply! So right now I am trying to test the performance of different seeding filtration strategies. So if I can output the original anchors and clusters that would be the great help for my task. And it seems that the cluster score should be different to final alignment score.

**Comment by mchaisso** [comment]
Hi Nan,
  The anchors are in the format
qpos tpos length strand
where strand== 0 is forward, 1 is reverse

Regarding the cluster scores, I honestly haven't looked at this code in
over 5 years. The score is roughly computed as a probably of observing the
set of anchors randomly from a Markovian process with transitions based on
the frequency of smaller k-mers (8-mers) in the genome. This was much more
meaningful for short alignments with high error rates, and the sum of the
length of matches is better now.

Anything above that is beyond the scope of what I can help out with right
now. I would recommend getting creative with the anchor set, or just
writing your own method to detect matches if variable length anchors make
scoring difficult.

cheers,
-mark

**Comment by Strideradu** [comment]
Thanks for your reply! I think I may want to go back to check the source code with your suggestions.
