### ISSUE TITLE
samtoh5 doesn't move forward.

### ISSUE THREAD

**Issue by nottwy** [PacificBiosciences/blasr#344]
I try to use samtoh5 to convert sam to .cmp.h5.

But when the size of the target .cmp.h5 reaches 646M, the file never becomes larger any more.

I checked the condition of the samtoh5 and found it worked well.

The memory samtoh5 has used is much smaller than the memory size of my system.
The condition returned from command 'top' shows that samtoh5 is 'R'.

So is there anyone who can tell me what happened now?

**Comment by ylipacbio** [comment]
samtoh5 is deprecated, see below for details

https://github.com/PacificBiosciences/blasr/wiki/BLASR-Frequently-Asked-Questions#why-samfilter-or-samtoh5-crashed-on-sam-file-created-by-blasr

Please move forward from h5 to bam 
https://github.com/PacificBiosciences/PacBioFileFormats/wiki/BAM-recipes
