### ISSUE TITLE
samtoh5 (Segmentation fault)

### ISSUE THREAD

**Issue by nottwy** [PacificBiosciences/blasr#345]
I invoke samtoh5 like this to trace the program:
`strace samtoh5 p2c.sam preads_falcon.fa mu01.cmp.h5 2> mu01.cmp.h5.log`
Then there is a **Segmentation fault**.
And this is the file [mu01.cmp.h5.log](https://github.com/PacificBiosciences/blasr/files/920353/mu01.cmp.h5.txt)

**Comment by ylipacbio** [comment]
https://github.com/PacificBiosciences/blasr/wiki/BLASR-Frequently-Asked-Questions#why-samfilter-or-samtoh5-crashed-on-sam-file-created-by-blasr

**Comment by nottwy** [comment]
So, another question.
I want to use ngs short reads to polish assembly genome.
So I align reads to genome with bwa and get one .sam file. How can I use it to polish genome? Any suggestions?

**Comment by mchaisso** [comment]
Pilon

-mark

**Comment by nottwy** [comment]
Can I use the latest version of arrow or quiver to polish genome with NGS reads mapping results such bam file?

**Comment by mchaisso** [comment]
No, quiver/arrow is for pacbio reads only
