### ISSUE TITLE
blasr --sam/--bam is not a valid version

### ISSUE THREAD

**Issue by nottwy** [PacificBiosciences/blasr#346]
Dear developers,

I install blasr 5.3 according to the instruction in this page: [BLASR + utils (make)](https://github.com/PacificBiosciences/blasr/blob/master/doc/INSTALL_MAKE.md)

with gcc 6.3.0 and hdf5 1.8.18.

This is my configure.
`./configure.py --sub HDF5_INCLUDE=/path/to/hdf5/include/ HDF5_LIB=/path/to/hdf5/lib/`

I try to run blasr like this to output bam result:
`blasr reads.fa ref.fa --hitPolicy allbest  --bestn 3 --nCandidates 5 --minPctIdentity 0.98 --nproc 24 --bam --out result.bam --unaligned result.unaligned.fasta`

but it always failed with:
`ERROR: --bam is not a valid option.`

**Comment by ylipacbio** [comment]
please provide 

blasr --version

**Comment by armintoepfer** [comment]
We won't support source builds from now on, but provide the latest version on bioconda:
`conda install -c bioconda blasr`
