### ISSUE TITLE
output unmapped reads

### ISSUE THREAD

**Issue by mictadlo** [PacificBiosciences/blasr#347]
Hi 
Does blasr output unmapped reads, because I try to remove contamination from PacBio reads?

```
sa2bwt choloraplast.fasta choloraplast.fasta.sa choloraplast.fasta.bwt
blasr reads.bas.h5 choloraplast.fasta -bwt choloraplast.fasta.bwt
```

Thank you in advance.

Michal

**Comment by mchaisso** [comment]
The -unaligned flag will write out the unmapped reads to this file, but it
is the full fasta. If you have sam output (-sam),  unaligned will have "*"
for the chromosome.

best,
-mark

**Comment by mictadlo** [comment]
Thank you.
