### ISSUE TITLE
ERROR, mixed query file types is not allowed.

### ISSUE THREAD

**Issue by mictadlo** [PacificBiosciences/blasr#349]
Hi,
I am using RS II and Sequel FASTQ files. I tried to align the FASTQ file against a reference FASTA file and get mapped and unmapped alignment.
```
blasr ana.fastq 508.fasta --sa 508.fasta.sa --bam alignement_blasr.bam
ERROR, mixed query file types is not allowed.
```
What did I miss?

Thank you in advance.

Michal

**Comment by mictadlo** [comment]
Hi,
I also tried it with `bax.h5` an still got the same problem with blasr v5.1
```
blasr test.bax.h5 508.fasta --sa 508.fasta.sa --bam alignement_blasr.bam
ERROR, mixed query file types is not allowed.
```

What could be the problem?

Thank you in advance.

Michal

**Comment by armintoepfer** [comment]
Why don't you align each platform individually and then merge the BAM files? Why does it have to be in one blasr execution?

**Comment by mictadlo** [comment]
I do not understand, I took on bax.h5 and I tried to align it against a reference. How do you do it?
