### ISSUE TITLE
holeNumbers list inefficient

### ISSUE THREAD

**Issue by jackshencn** [PacificBiosciences/blasr#350]
Hi,

If I use option -holeNumbers xxx, blasr is very slow if the number is big. Based on the blasr.c, it appears a while loop is used to iterate through all the ZMW using FetchReads until IsGoodRead returns true. 

I'm trying to do subset mapping to a local assembled contig. The whole genome is spread across 90 SMRT cells thus for each mapping there's only 1 ZMW needs to map. Can you implement the function the other way around by iterating the holeNumbers list. 

Thanks!

**Comment by mchaisso** [comment]
Depending on your needs, this version does random access for the hole
number list: www.github.com/mchaisso/blasr .  The problem is it doesn't
currently allow for different hole numbers per movie name, so you'd have to
run once per movie.

-mark
