### ISSUE TITLE
install directions won't work, but a small modification will work

### ISSUE THREAD

**Issue by dgordon562** [PacificBiosciences/blasr#352]
If I just do the following, make will crash with zlib not found:
```sh
git clone git@github.com:PacificBiosciences/pitchfork.git
cd pitchfork
make init
make blasr PREFIX=/opt/mybuild             # if you want to build your own blasr
bash --init-file /opt/mybuild/setup-env.sh # either to use the build in the sub-shell
source /opt/mybuild/setup-env.sh           # or     to use the build in current shell 
```
as listed on:

https://github.com/PacificBiosciences/blasr/wiki/Blasr-Installation-Qs-&-As

However, if on the "make blasr" line, I leave out the "PREFIX=/opt/mybuild", it works.  The PREFIX doesn't even work if I set it to a valid directory on my system.

Including it gives the following error:
```sh
cd mydir/pitchfork/170517/pitchfork/staging/zlib-1.2.8 && tar cf - * | tar xf - -C mydir/pitchfork/170517
find mydir/pitchfork/170517/pitchfork/staging/zlib-1.2.8 ! -type d|awk -F 'mydir/pitchfork/170517/pitchfork/staging/zlib-1.2.8/' '{print $2}' > mydir/pitchfork/170517/var/pkg/zlib-1.2.8
/bin/bash: mydir/pitchfork/170517/var/pkg/zlib-1.2.8: No such file or directory
make[1]: *** [mydir/pitchfork/170517/var/pkg/zlib-1.2.8] Error 1
make[1]: Leaving directory `mydir/pitchfork/170517/pitchfork/ports/thirdparty/zlib'
make: *** [zlib] Error 2
```

**Comment by dgordon562** [comment]
CD believes this causes a bad pitchfork and I should work with you here on github.  He suggests that I delete this pitchfork and instead use 
HAVE_ZLIB=(path)` into pitchfork/.git/settings.mk
but wanted me to ask you to be sure.

**Comment by dgordon562** [comment]
Using HAVE_ZLIB as stated above, causes the following crash, which I believe is a bug in the installation script (see below).  However, if I execute the mkdir command (below) in the order listed below, the install script will run to completion:

git clone git@github.com:PacificBiosciences/pitchfork.git
cd pitchfork

then set .git/settings.mk

to have:
HAVE_ZLIB     = /net/gs/vol3/software/modules-sw/zlib/1.2.6/Linux/RHEL6/x86_64

make init

mkdir -p /net/eichler/vol2/home/dgordon/pitchfork/170517a/var/pkg
make blasr PREFIX=/net/eichler/vol2/home/dgordon/pitchfork/170517a



.
.
.
find /net/gs/vol3/software/modules-sw/zlib/1.2.6/Linux/RHEL6/x86_64/lib -name 'zlib.pc' -exec cp -aL {} /net/eichler/vol2/home/dgordon/pitchfork/170517a/pitchfork/staging/zlib/lib/pkgconfig/ \;
cd /net/eichler/vol2/home/dgordon/pitchfork/170517a/pitchfork/staging/zlib && tar cf - * | tar xf - -C /net/eichler/vol2/home/dgordon/pitchfork/170517a
find /net/eichler/vol2/home/dgordon/pitchfork/170517a/pitchfork/staging/zlib ! -type d|awk -F '/net/eichler/vol2/home/dgordon/pitchfork/170517a/pitchfork/staging/zlib/' '{print $2}' > /net/eichler/vol2/home/dgordon/pitchfork/170517a/var/pkg/zlib
/bin/bash: /net/eichler/vol2/home/dgordon/pitchfork/170517a/var/pkg/zlib: No such file or directory
make[1]: *** [do-install] Error 1

**Comment by mhsieh** [comment]
Can you check the existence of `/net/eichler/vol2/home/dgordon/pitchfork/170517a/var` ?

Just do an `ls -l /net/eichler/vol2/home/dgordon/pitchfork/170517a/var`

**Comment by dgordon562** [comment]
Sure, it is there.  That's because I created it (see the mkdir in the previous post).  Without creating it, 
/net/eichler/vol2/home/dgordon/pitchfork/170517a/var/pkg doesn't exist.  I don't know about
/net/eichler/vol2/home/dgordon/pitchfork/170517a/var

>  ls -l /net/eichler/vol2/home/dgordon/pitchfork/170517a/var
total 32
drwxr-xr-x 2 dgordon eichlerlab 2048 May 17 15:28 pkg
{dgordon}e188:~/pitchfork/170517a/pitchfork

**Comment by mhsieh** [comment]
it should be done by `make init`

can you `make _startover` and just `make init` and see if you have the right directory structure?

**Comment by dgordon562** [comment]
OK.

I'll start completely over in a new directory with git clone...

**Comment by dgordon562** [comment]
Below shows that make init doesn't create /net/eichler/vol2/home/dgordon/pitchfork/170517b/var but rather /net/eichler/vol2/home/dgordon/pitchfork/170517b/pitchfork/deployment/var/pkg

If you are on vacation, MJ, I'm actually fine now, having scrounged up a pre-built version of pbalign that I needed.  It would be good to be able to build it (and variantCaller) at some point, but I think I'm ok for now...  

Thanks!!!
David

'''

> make init
make -f mk/init.mk init
make[1]: Entering directory `/net/eichler/vol2/home/dgordon/pitchfork/170517b/pitchfork'
/net/eichler/vol2/home/dgordon/pitchfork/170517b/pitchfork/bin/checkSystem
/net/eichler/vol2/home/dgordon/pitchfork/170517b/pitchfork/bin/checkCC gcc
mkdir -p "/net/eichler/vol2/home/dgordon/pitchfork/170517b/pitchfork/workspace"
mkdir -p "/net/eichler/vol2/home/dgordon/pitchfork/170517b/pitchfork/distfiles"
mkdir -p "/net/eichler/vol2/home/dgordon/pitchfork/170517b/pitchfork/staging"
mkdir -p "/net/eichler/vol2/home/dgordon/pitchfork/170517b/pitchfork/deployment/bin"
mkdir -p "/net/eichler/vol2/home/dgordon/pitchfork/170517b/pitchfork/deployment/etc"
mkdir -p "/net/eichler/vol2/home/dgordon/pitchfork/170517b/pitchfork/deployment/include"
mkdir -p "/net/eichler/vol2/home/dgordon/pitchfork/170517b/pitchfork/deployment/lib"
mkdir -p "/net/eichler/vol2/home/dgordon/pitchfork/170517b/pitchfork/deployment/lib/pkgconfig"
mkdir -p "/net/eichler/vol2/home/dgordon/pitchfork/170517b/pitchfork/deployment/share"
mkdir -p "/net/eichler/vol2/home/dgordon/pitchfork/170517b/pitchfork/deployment/var/pkg"
echo "export   LD_LIBRARY_PATH=/net/eichler/vol2/home/dgordon/pitchfork/170517b/pitchfork/deployment/lib:\$LD_LIBRARY_PATH"  |sed -e 's/::*/:/g' > "/net/eichler/vol2/home/dgordon/pitchfork/170517b/pitchfork/deployment/setup-env.sh"
echo "export PATH=/net/eichler/vol2/home/dgordon/pitchfork/170517b/pitchfork/deployment/bin:\$PATH"|sed -e 's/::*/:/g' >> "/net/eichler/vol2/home/dgordon/pitchfork/170517b/pitchfork/deployment/setup-env.sh"
echo "unset PYTHONPATH"
unset PYTHONPATH
make[1]: Leaving directory `/net/eichler/vol2/home/dgordon/pitchfork/170517b/pitchfork'
touch mk//../initialized.o
/net/eichler/vol2/home/dgordon/pitchfork/170517b/pitchfork/bin/checkSystem
/net/eichler/vol2/home/dgordon/pitchfork/170517b/pitchfork/bin/checkCC gcc
mkdir -p "/net/eichler/vol2/home/dgordon/pitchfork/170517b/pitchfork/workspace"
mkdir -p "/net/eichler/vol2/home/dgordon/pitchfork/170517b/pitchfork/distfiles"
mkdir -p "/net/eichler/vol2/home/dgordon/pitchfork/170517b/pitchfork/staging"
mkdir -p "/net/eichler/vol2/home/dgordon/pitchfork/170517b/pitchfork/deployment/bin"
mkdir -p "/net/eichler/vol2/home/dgordon/pitchfork/170517b/pitchfork/deployment/etc"
mkdir -p "/net/eichler/vol2/home/dgordon/pitchfork/170517b/pitchfork/deployment/include"
mkdir -p "/net/eichler/vol2/home/dgordon/pitchfork/170517b/pitchfork/deployment/lib"
mkdir -p "/net/eichler/vol2/home/dgordon/pitchfork/170517b/pitchfork/deployment/lib/pkgconfig"
mkdir -p "/net/eichler/vol2/home/dgordon/pitchfork/170517b/pitchfork/deployment/share"
mkdir -p "/net/eichler/vol2/home/dgordon/pitchfork/170517b/pitchfork/deployment/var/pkg"
echo "export   LD_LIBRARY_PATH=/net/eichler/vol2/home/dgordon/pitchfork/170517b/pitchfork/deployment/lib:\$LD_LIBRARY_PATH"  |sed -e 's/::*/:/g' > "/net/eichler/vol2/home/dgordon/pitchfork/170517b/pitchfork/deployment/setup-env.sh"
echo "export PATH=/net/eichler/vol2/home/dgordon/pitchfork/170517b/pitchfork/deployment/bin:\$PATH"|sed -e 's/::*/:/g' >> "/net/eichler/vol2/home/dgordon/pitchfork/170517b/pitchfork/deployment/setup-env.sh"
echo "unset PYTHONPATH"
unset PYTHONPATH
```
{dgordon}e108:~/pitchfork/170517b/pitchfork
```
> ll
total 544
drwxr-xr-x  3 dgordon eichlerlab  2048 May 17 16:31 ..
-rw-r--r--  1 dgordon eichlerlab   109 May 17 16:31 .gitignore
-rw-r--r--  1 dgordon eichlerlab   791 May 17 16:31 .travis.yml
-rw-r--r--  1 dgordon eichlerlab  1676 May 17 16:31 LICENSE
-rw-r--r--  1 dgordon eichlerlab 15013 May 17 16:31 Makefile
-rw-r--r--  1 dgordon eichlerlab  1124 May 17 16:31 README.md
drwxr-xr-x  2 dgordon eichlerlab  4096 May 17 16:31 bin
drwxr-xr-x  2 dgordon eichlerlab  2048 May 17 16:31 mk
drwxr-xr-x  6 dgordon eichlerlab  2048 May 17 16:31 ports
lrwxrwxrwx  1 dgordon eichlerlab    16 May 17 16:31 settings.mk -> .git/settings.mk
-rw-r--r--  1 dgordon eichlerlab   920 May 17 16:31 settings.mk.example
drwxr-xr-x  8 dgordon eichlerlab  2048 May 17 16:32 .git
drwxr-xr-x  2 dgordon eichlerlab  2048 May 17 16:33 workspace
drwxr-xr-x  2 dgordon eichlerlab  2048 May 17 16:33 distfiles
drwxr-xr-x  2 dgordon eichlerlab  2048 May 17 16:33 staging
drwxr-xr-x  8 dgordon eichlerlab  2048 May 17 16:33 deployment
drwxr-xr-x 10 dgordon eichlerlab  2048 May 17 16:33 .
-rw-r--r--  1 dgordon eichlerlab     0 May 17 16:33 initialized.o
{dgordon}e108:~/pitchfork/170517b/pitchfork
'''

**Comment by mhsieh** [comment]
Let me know how you set your PREFIX
please record that in settings.mk, something like:
```
PREFIX = ${HOME}/pitchfork/distribution
```

**Comment by mhsieh** [comment]
I am a little bit afraid of setting PREFIX to the same level with pitchfork.

**Comment by dgordon562** [comment]
I followed the installation instruction here:
https://github.com/PacificBiosciences/blasr/wiki/Blasr-Installation-Qs-&-As
which do not suggest specifying PREFIX in settings.mk
Perhaps that is the problem.  If those instructions are correct, perhaps delete 
them and just have a link to your correct instructions.  I'll try specifying PREFIX in 
settings.mk

**Comment by mhsieh** [comment]
Thanks for point out the old document, so now I know why people keep having that.
Basically `make init` should be `make init PREFIX=/opt/mybuild` in that document. The reason I never had any problem testing it is that `init` is a prerequisite of almost every rule of the master Makefile, so I never ran `make init` separately.
