### ISSUE TITLE
line 62: 16 Segmentation fault (core dumped)  - Issue

### ISSUE THREAD

**Issue by TRKarthikeyan** [PacificBiosciences/blasr#354]
Hello everyone,
I write a simple C program. Sorting n integers for t test cases. When I run it in my own TurboC4 compiler it works fine. when I upload in some online testing compiler, it shows the error: "line 62: 16 Segmentation fault (core dumped)"

The code:
#include <stdio.h>

int main()
{
    int i,j,k1,k2, temp;
    int t,n[20],a[20][50];
//    printf("\n Enter No. of Test Cases : ");
    scanf("%d", &t);

    for(i=0; i<t; i++)
    {
  //      printf("\n How many Numbers to Sort ?: ");
	scanf("%d", &n[i]);

//	printf("\n Enter %d integers", n[i]);
	for(j=0; j<n[i]; j++)
	{
	    scanf("%d", &a[i][j]);
	}

	// Sorting

	for(k1=0; k1<n[i]-1; k1++)
	for(k2=k1+1; k2<n[i]; k2++)
	{
	    if(a[i][k1]>a[i][k2])
	    {
		temp = a[i][k1];
		a[i][k1] = a[i][k2];
		a[i][k2] = temp;
	    }
	}
    }

    for(i=0; i<t; i++)
    {
	for(j=0; j<n[i]; j++)
	{
	    printf("%d ", a[i][j]);
	}
	printf("\n");
    }
    return 0;
}

Sample input:
2
5
6 9 -10 -7 -3
10
-3 -2 6 0 6 7 8 8 5 -7
------
The message I received when running through online compiler:
[{"score":0,"passed":false,"error":"/usercode/script.sh: line 62: 16 Segmentation fault (core dumped) $output - < \"/usercode/inputFile\"\n"},{"error":"Wrong answer","score":0,"time":0.09,"passed":false,"memory":10140}]

Can any one clarify why this is happening?

**Comment by armintoepfer** [comment]
![](https://media.giphy.com/media/LNVj6AV3FlrEs/giphy.gif)
Wrong repository? Not sure how that is related to our codebase.

**Comment by TRKarthikeyan** [comment]
This is a kind of question in a contest. Based on the code they predict whether it gives the expected result, and decide for 'passed' or not; they will give 'score' based on the running time of the program; if there are run time error, it shown as "error":".......".
Here, they tried for two sample input values; For the first set of values, it showed the "error". For the second input values, the answer was wrong, as shown in the second set result. {"error":"Wrong answer","score":0,"time":0.09,"passed":false,"memory":10140}

Now it will be clear about the error: "error":"/usercode/script.sh: line 62: 16 Segmentation fault (core dumped) $output - < "/usercode/inputFile"\n"
