### ISSUE TITLE
ERROR, can not convert non-pacbio reads to pbbam record

### ISSUE THREAD

**Issue by ressy** [PacificBiosciences/blasr#356]
For certain input sequences (but not others!) I encounter an error when trying to write sam/bam output from blasr.  For example:

    $ blasr input.fasta genome.fails.fasta --bam --out output.bam
    [INFO] 2017-06-05T09:47:25 [blasr] started.
    ERROR, can not convert non-pacbio reads to pbbam record.

If I run it with a different genome file with the same format and similar sequence data it succeeds:

    $ blasr input.fasta genome.works.fasta --bam --out output.bam
    [INFO] 2017-06-05T09:47:29 [blasr] started.
    [INFO] 2017-06-05T09:47:29 [blasr] ended.

Or, if I don't specify --sam/--bam, it also works with either file:

    $ blasr input.fasta genome.fails.fasta --out output
    [INFO] 2017-06-05T09:48:41 [blasr] started.
    [INFO] 2017-06-05T09:48:41 [blasr] ended.

This is with blasr 5.3.574e1c2 built from pitchfork (latest commit, deeefa8) on Ubuntu 16.04.1 LTS.  (Pbbam-- since I'm guessing that might be relevant here-- is also its latest, 6ae738b, from May 25.)

Attached are the three files for this case.  Any ideas?

[example_files.zip](https://github.com/PacificBiosciences/blasr/files/1052170/example_files.zip)

**Comment by ressy** [comment]
A few more details since [the wiki](https://github.com/PacificBiosciences/blasr/wiki) asks for them:

    $ uname -a
    Linux hem-shwhn-050 4.4.0-66-generic #87-Ubuntu SMP Fri Mar 3 15:29:05 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

    $ gcc --version
    gcc (Ubuntu 5.4.0-6ubuntu1~16.04.4) 5.4.0 20160609
    Copyright (C) 2015 Free Software Foundation, Inc.
    This is free software; see the source for copying conditions.  There is NO
    warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

    $ blasr --version
    blasr   5.3.574e1c2

I'll be appreciative of any thoughts or suggestions!

**Comment by mhsieh** [comment]
The reason "genome.works.fasta" works is that you don't have a hit for that query.

Currently bam output option only works if you use this form in the header of fasta file: `movie/0/0/0_0`,  see https://github.com/PacificBiosciences/blasr/wiki/BLASR-Frequently-Asked-Questions#can-blasr-produce-sambam-output-when-input-is-a-fasta-file
```
[mhsieh@pacbio tmp]$ cat input.fasta 
>reads
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
[mhsieh@pacbio tmp]$ cat > newinput.fasta << EOF
> >movie/0/0_0
> AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
> EOF
[mhsieh@pacbio tmp]$ ls
example_files.zip  genome.fails.fasta  genome.works.fasta  input.fasta  newinput.fasta
[mhsieh@pacbio tmp]$ blasr newinput.fasta genome.fails.fasta --bam --out output.bam
[INFO] 2017-06-14T10:17:47 [blasr] started.
[INFO] 2017-06-14T10:17:47 [blasr] ended.
[mhsieh@pacbio tmp]$ ls -lrt output.bam 
-rw-r--r-- 1 mhsieh Shadow Users 452 Jun 14 10:17 output.bam
[mhsieh@pacbio tmp]$ samtools view output.bam 
movie/0/0_50    0       genome  345444  254     50=     *       0       0       AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA      *       RG:Z:d9164a10   np:i:1  qe:i:50   qs:i:0  zm:i:0  AS:i:-250       NM:i:0
```

**Comment by ressy** [comment]
Thanks for the thorough explanation, Mengjuei.  We'll just make sure to use the right format for fasta input, then.
