### ISSUE TITLE
Make build-submodule error message

### ISSUE THREAD

**Issue by nataliering** [PacificBiosciences/blasr#360]
Hi, 

I'm trying to install blasr on a new ubuntu virtual machine, and am running into an error message during the "make build-submodule" step. I've glanced through the error message myself, and tried doing the process again from scratch in case there was a typo on the way through the first time, but I can't work out why it's going wrong - could you help me out please? 

Here's the error message and the last few lines of output before that:

> g++ -shared  -L../pbdata -L/usr/lib/x86_64-gnu/hdf5/serial -o libpbihdf.so -Wl,-soname,libpbihdf.so BufferedHDFArray.shared.o HDFRegionsWriter.shared.o HDFZMWMetricsWriter.shared.o HDFWriterBase.shared.o DatasetCollection.shared.o HDFRegionTableReader.shared.o HDFNewBasReader.shared.o HDFAtom.shared.o HDFCmpExperimentGroup.shared.o HDFPulseDataFile.shared.o HDFPulseCallsWriter.shared.o HDFCmpSupportedFields.shared.o HDFBaseCallsWriter.shared.o HDFZMWReader.shared.o HDFFile.shared.o HDFAlnInfoGroup.shared.o HDFPulseWriter.shared.o HDFGroup.shared.o HDFUtils.shared.o HDFZMWWriter.shared.o HDFScanDataWriter.shared.o HDFScanDataReader.shared.o HDFData.shared.o HDFBaxWriter.shared.o HDFPulseH5Writer.shared.o BufferedHDF2DArray.shared.o HDFAttributable.shared.o HDFAlnGroupGroup.shared.o -lpbdata -lhdf5 -lhdf5_cpp
> /usr/bin/ld: cannot find -lhdf5
> collect2: error: ld returned 1 exit status
> /home/ubuntu/software/blasr_install/blasr/libcpp/hdf//../rules.mk:14: recipe for target 'libpbihdf.so' failed
> make[3]: *** [libpbihdf.so] Error 1
> make[3]: Leaving directory '/home/ubuntu/software/blasr_install/blasr/libcpp/hdf'
> makefile:21: recipe for target 'libpbihdf' failed
> make[2]: *** [libpbihdf] Error 2
> make[2]: Leaving directory '/home/ubuntu/software/blasr_install/blasr/libcpp'
> makefile:8: recipe for target 'all' failed
> make[1]: *** [all] Error 2
> make[1]: Leaving directory '/home/ubuntu/software/blasr_install/blasr/libcpp'
> makefile:54: recipe for target 'build-submodule' failed
> make: *** [build-submodule] Error 

and the output from the ./configure.py command, in case that's where I've gone wrong:

> make -f /home/ubuntu/software/blasr_install/blasr//sub.mk configure-submodule
> make[1]: Entering directory '/home/ubuntu/software/blasr_install/blasr'
> cd libcpp && ./configure.py
> uname -s
> uname='Linux'
> writing to '/home/ubuntu/software/blasr_install/blasr/libcpp/pbdata/libconfig.h'
> """
> 
> """
> writing to 'defines.mk'
> """
> 
> SH_LIB_EXT           := .so
> 
> HDF5_INC:=/usr/include/hdf5/serial
> HDF5_LIB:=/usr/lib/x86_64-gnu/hdf5/serial
> LIBPBDATA_INC     ?=../pbdata
> LIBPBIHDF_INC     ?=../hdf
> LIBBLASR_INC      ?=../alignment
> LIBPBDATA_LIB     ?=../pbdata
> LIBPBIHDF_LIB     ?=../hdf
> LIBBLASR_LIB      ?=../alignment
> 
>  \#Use PREFIX dir, if available.
> INCLUDES      += ${PREFIX_INC}
> LIBS          += ${PREFIX_LIB}
> """

Thanks for your time,
Natalie

**Comment by nataliering** [comment]
...sorry, just realised the second bit was the output from "make configure-submodule", not "configure.py", here's the actual output from configure.py:

> `uname`
> Linux
> writing to '/home/ubuntu/software/blasr_install/blasr/defines.mk':
> """
> LIBPBDATA_LIB        ?= /home/ubuntu/software/blasr_install/blasr/libcpp/pbdata
> LIBBLASR_LIBFLAGS    ?= -lblasr
> HDF5_LIB             ?= /usr/lib/x86_64-gnu/hdf5/serial
> DL_LIBFLAGS          ?= -ldl
> HDF5_INC             ?= /usr/include/hdf5/serial
> LIBPBDATA_INC        ?= /home/ubuntu/software/blasr_install/blasr/libcpp/pbdata
> LIBPBIHDF_LIBFLAGS   ?= -lpbihdf
> LIBPBIHDF_INC        ?= /home/ubuntu/software/blasr_install/blasr/libcpp/hdf
> LIBBLASR_LIB         ?= /home/ubuntu/software/blasr_install/blasr/libcpp/alignment
> SHELL                ?= bash
> RT_LIBFLAGS          ?= -lrt
> HDF5_LIBFLAGS        ?= -lhdf5_cpp -lhdf5
> LIBPBDATA_LIBFLAGS   ?= -lpbdata
> ZLIB_LIBFLAGS        ?= -lz
> LIBBLASR_INC         ?= /home/ubuntu/software/blasr_install/blasr/libcpp/alignment
> PTHREAD_LIBFLAGS     ?= -lpthread
> NOPBBAM              ?= 1
> LIBPBIHDF_LIB        ?= /home/ubuntu/software/blasr_install/blasr/libcpp/hdf
> """
> ----

**Comment by nataliering** [comment]
Any ideas please?

**Comment by armintoepfer** [comment]
Why don't you download the latest and greatest official version, released
this week http://www.pacb.com/support/software-downloads/
