### ISSUE TITLE
Please help me locate blasr version 1.3.1.127046

### ISSUE THREAD

**Issue by Lahcen86** [PacificBiosciences/blasr#361]
Hi there,

This request might fall on deaf ears, but its a desperate request to obtain the version 1.3.1.127046 of blasr. I have serious issues with the compatibility with PBSuite 15.8.24. 

I am currently using the most recent version of blasr (5.3.5b30da0). Both softwares are installed and running fine....well almost. The calls to blasr from Jelly (PBsuite) are hard coded, and unfortunately are using the "-" instead of a double dash as in the version of blasr I have. 

I have issues with the mapping stage of PBSuite. I have gotten as far as calling blasr manually as it would have been with Jelly.py, and the output was produced without error or issue. Its at the following step in the Jelly protocol (m4pie.py) that refuses to work with with this version of blasr. 

So to cut a long story short, if at all possible can someone direct me to this older version (fully vetted to work with PBSuite) ? I know its a long shot, I have read multiple forums where others have had zero luck locating this older version. And sadly there is absolutely no current support from the PBSuite devs. 

Actually lastly, would you even recommend trying the legacy version of blasr ? 

Thanks a lot for your attention,
Lahcen

**Comment by alanorth** [comment]
For what it's worth I'm also looking for version 1.3.1.127046, which is [stated as a requirement of PBSuite on their wiki](https://sourceforge.net/p/pb-jelly/wiki/Home/).

**Comment by alanorth** [comment]
There is hope! I am currently using blasr from the `smrtanalysis-4.0.0` tag with PBSuite 15.8.24. You just need to manually adjust all short command line options in Assembly.py, m4pie.py, and Stages.py to long ones, ie: `-sa` → `--sa`, `-nprocs` → `--nprocs`.

See this thread: https://www.biostars.org/p/198519/

**Comment by pb-cdunn** [comment]
Note that recent smrtanalysis releases (at least for the last few months) have included a manifest of specific git commit SHA1s. E.g.
```sh
$ ls .../smrttools/5.0.0/etc
modulelist.txt  pacbio-manifest.json  pacbio-manifest.txt  version.json  versionstr.txt  version.txt
```

**Comment by conchoecia** [comment]
Just to be helpful for the next people who find this thread, here are some important notes for what to change when using a newer version of `blasr`:

- idiosyncracies with old `blasr` versions and newer ones:
  - `-nprocs` -> `--nproc`
  - `-minPctIdentity` -> `--minPctSimilarity`

I grep'd the contents of all the python scripts in PBSuite 15.8.24 and found that these cmds should be changed.

## `Assembly.py`

`Assembly.py` lines 21-22 should be changed to:

```
     c = ("blasr %s %s -m %s --bestn %d --nCandidates %d --minMatch 8 --sdpTupleSize 6 --affineAlign "
                  "--nproc %d --noSplitSubreads --out %s --minPctSimilarity 60 --minReadLength 5") % \
```

## `bampie.py`

`bampie.py` lines 14-22 should be changed to:

```
#Edit this string to set which parameters blasr will use by default
#DO NOT! Set -nproc, -bestn, -clipping, or any output (e.g. -out -m 5)
#Remove -noSpotSubreads if your inputs are bax.h5 files [i think]
BLASRPARAMS = (" --affineAlign --noSplitSubreads --nCandidates 20 "
               "--minPctSimilarity 75 --sdpTupleSize 6")
#Parameters used in the eichler experiments
EEBLASRPARAMS = (" --maxAnchorsPerPosition 100 --advanceExactMatches 10 "
               "--affineAlign --affineOpen 100 --affineExtend 0 "
               "--insertion 5 --deletion 5 --extend --maxExtendDropoff 20 "
               "--noSplitSubreads --nCandidates 20 ")
               #"-minPctIdentity 75 ") #didn't use this, but aybe should
               #have
```

`bampie.py` line 47 should be changed to:

```
     args = [" --bestn ", " --nproc ", " --clipping ", " --out ", " -m "]
```

`bampie.py` lines 64-65 should be:

```
    cmd = ("blasr %s %s %s --nproc %d --bestn 1 "
           "--sam --clipping subread --out %s ") \
```

## `HSpots.py`

Lines 203-213 in HSpots should be changed to:

```
    cmd = ("blasr %s %s %s --nproc %d --bestn 1 --out %s ") \
           % (query, target, format, nproc, outname)
    #need to figure out how to m5-pie it...maybe
    if consensus:
        r, o, e = exe(cmd + " --noSplitSubreads --minMatch 5 " + \
                     "--nCandidates 20 --sdpTupleSize 6 --insertion 1 --deletion 1 --bestn 1")
    else:
        r, o, e = exe(cmd + " --maxAnchorsPerPosition 100 "
               "--affineAlign --affineOpen 100 --affineExtend 0 "
               "--insertion 10 --deletion 10 "
               "--noSplitSubreads --nCandidates 20 ")
```

Line 1003 should be:

```
            blasr(conOut.name, refOut.name, format="--sam", outname=varSam.name,\
                consensus=False) #-- would this help?
```

## `m4pie.py`

Lines 78-79 of `m4pie.py` should be changed to:

```
     cmd = ("blasr %s %s %s --nproc %d -m 4 --bestn 1 --nCandidates 20 --out %s"
           " --minPctSimilarity 75 --sdpTupleSize 6 --noSplitSubreads") \
```

**Comment by pb-dseifert** [comment]
See also: https://github.com/PacificBiosciences/blasr/pull/399
