### ISSUE TITLE
blasr installation with ccmake does not work

### ISSUE THREAD

**Issue by samfux84** [PacificBiosciences/blasr#362]
I would like to install blasr with bam support.

After installing some requirements like CMake 3.9.0, pbbam and its dependencies (boost, google test, htslib (Pac Bio fork)), I was following the instructions provided at:

https://github.com/PacificBiosciences/blasr/blob/master/doc/INSTALL_CMAKE.md

For setting all required CMake variables, I was using the ccmake GUI. After typing "c" to configure everything I tried typing "g" to generate the Makefile and got the following error messages:

```
 CMake Error:
   Error evaluating generator expression:

     $<TARGET_FILE:pbbam>

   No target "pbbam"



 CMake Error at CMakeLists.txt:57 (target_link_libraries):
   Error evaluating generator expression:

     $<TARGET_FILE:pbbam>

   No target "pbbam"



 CMake Error at CMakeLists.txt:57 (target_link_libraries):
   Error evaluating generator expression:

     $<TARGET_FILE:hts>

   No target "hts"



 CMake Error:
   Error evaluating generator expression:

     $<TARGET_FILE:pbbam>

   No target "pbbam"
```

I don't want to build pbbam as I already have a working version. Is there any workaround ? Why is there no CMake variable to specify an existing pbbam installation ?

**Comment by nlhepler** [comment]
Hi @samfux84, many of the required dependencies are retrieved by following the guide, in particular it looks like you might have missed: `git submodule update --init --remote`.

**Comment by samfux84** [comment]
@nlhepler Thank you for your help. I actually did run the submodule update command as it is described in the installation instructions. Otherwise the pbbam directory would be empty, which is not the case:

```
[sfux@develop01 blasr]$ ls -ltr
total 108
-rw-r--r--  1 sfux T0000  1776 Jul 26 15:11 LICENSE
-rw-r--r--  1 sfux T0000  2622 Jul 26 15:11 CMakeLists.txt
-rw-r--r--  1 sfux T0000  2382 Jul 26 15:11 BlasrVersion.h.in
-rw-r--r--  1 sfux T0000 56883 Jul 26 15:11 Blasr.cpp
-rw-r--r--  1 sfux T0000   871 Jul 26 15:11 README.md
-rw-r--r--  1 sfux T0000  1549 Jul 26 15:11 cram.mk
-rwxr-xr-x  1 sfux T0000  8635 Jul 26 15:11 configure.py
drwxr-xr-x  2 sfux T0000   160 Jul 26 15:11 cmake
-rw-r--r--  1 sfux T0000  2203 Jul 26 15:11 bamboo_build.sh
drwxr-xr-x  3 sfux T0000   300 Jul 26 15:11 extrautils
drwxr-xr-x  3 sfux T0000   140 Jul 26 15:11 doc
drwxr-xr-x  2 sfux T0000   720 Jul 26 15:11 ctest
-rw-r--r--  1 sfux T0000   175 Jul 26 15:11 sub.mk
drwxr-xr-x  3 sfux T0000    60 Jul 26 15:11 scripts
-rw-r--r--  1 sfux T0000   776 Jul 26 15:11 rules.mk
-rw-r--r--  1 sfux T0000  2899 Jul 26 15:11 makefile
drwxr-xr-x  2 sfux T0000   320 Jul 26 15:11 iblasr
drwxr-xr-x  5 sfux T0000   160 Jul 26 15:11 tools
-rwxr-xr-x  1 sfux T0000   334 Jul 26 15:11 travis.sh
drwxr-xr-x  3 sfux T0000   260 Jul 26 15:11 utils
drwxr-xr-x 11 sfux T0000   500 Jul 26 15:12 libcpp
drwxr-xr-x  9 sfux T0000   340 Jul 26 15:12 pbbam
drwxr-xr-x  2 sfux T0000    40 Jul 26 15:48 build
[sfux@develop01 blasr]$ ls -ltr pbbam/
total 32
-rw-r--r-- 1 sfux T0000  1622 Jul 26 15:12 README.md
-rw-r--r-- 1 sfux T0000  1680 Jul 26 15:12 LICENSE.txt
-rw-r--r-- 1 sfux T0000   153 Jul 26 15:12 INSTALL.md
-rw-r--r-- 1 sfux T0000  3072 Jul 26 15:12 CMakeLists.txt
drwxr-xr-x 2 sfux T0000   280 Jul 26 15:12 cmake
-rw-r--r-- 1 sfux T0000 15247 Jul 26 15:12 CHANGELOG.md
drwxr-xr-x 3 sfux T0000    60 Jul 26 15:12 include
drwxr-xr-x 4 sfux T0000  2000 Jul 26 15:12 src
drwxr-xr-x 5 sfux T0000   140 Jul 26 15:12 tests
drwxr-xr-x 3 sfux T0000    60 Jul 26 15:12 third-party
drwxr-xr-x 7 sfux T0000   160 Jul 26 15:12 tools
drwxr-xr-x 5 sfux T0000   180 Jul 26 15:33 docs
[sfux@develop01 blasr]$ 
```

**Comment by samfux84** [comment]
If building blasr+bam support with CMAKE does not work, then please consider removing this paragraph from the installation instructions at

https://github.com/PacificBiosciences/blasr/blob/master/doc/INSTALL_CMAKE.md

**Comment by samfux84** [comment]
@nlhepler When specifying all CMAKE variables on the command line, compilation of the code works, whereas using the CCMAKE GUI allows to reproduce the above mentioned issue consistently.

**Comment by samfux84** [comment]
@nlhepler Specifying CMAKE variables on the command line solved part of the problem (but when using the CCMAKE GUI, the error is still reproducible). I have specified the CMAKE_INSTALL_PREFIX as described in the installation instructions. But when running "make install" only the binaries get copied into the correct location, whereas the libraries are spread all over:

```
[sfux@develop01 5.3]$ ls bin
blasr  sawriter  toAfg
[sfux@develop01 5.3]$ find . -type f -name *.so
./build/external/pbbam/build/lib/libpbbam.so
./build/external/pbbam/build/external/htslib/libhts.so
[sfux@develop01 5.3]$

```
Please add some rules to "make install" to create a "lib" directory next to the "bin" directory, where libraries are installed.

I am managing a software stack with more than 200 applications on a HPC cluster and would be very thankful if software developers would apply some "minimal standards" when developing software:

- Please implement a proper versioning with releases, because scientists need to document in their publications how they got to their results. This is difficult if you don't even now with what version of a software you were using because the only information available is the date when a git clone command was run, or a commit hash like 574e1c2ab1fadea49774c61c2c2374006e941ec1.

- Please make sure that your releases build at all, otherwise that particular version should not be called a release.

- Please list all dependencies (for blasr, CMAKE >3.7 and HDF5 are listed, but the BOOST dependency is not mentioned at all)

- Please implement a proper system wide installation (not everybody is running everything on a desktop computer). If there is a rule for "make install" implemented, then it should copy all relevant files to the location specified in -DCMAKE_INSTALL_PREFIX, not only the binaries. On a HPC cluster, software if often built in a scratch directory that is deleted after the installation is done. Therefore it would be nice to have a proper "make install", which installs all relevant files.

**Comment by armintoepfer** [comment]
Thank you for the feedback. As the readme states, please keep in mind that this is a developer version. The official version, with customer support is distributed via the SMRT Link bundle. You can get version 4.0 [here](http://www.pacb.com/support/software-downloads/) and for the latest 5.0 please contact PacBio's tech support.

**Comment by samfux84** [comment]
@armintoepfer Thank you for your reply.

I would be happy to install an official version of blasr or pbbam if they were available as standalone versions.

Is there a reason why official versions are only available as part of the SMRT Link bundle ? If users are interested just in a single tool, installing a software suite that is multiple gigabytes large feels a bit like an overkill.

**Comment by armintoepfer** [comment]
We won't support source builds from now on, but provide the latest version on bioconda:
`conda install -c bioconda blasr`
