### ISSUE TITLE
Blasr compilation error

### ISSUE THREAD

**Issue by fenderglass** [PacificBiosciences/blasr#363]
Hi,

I am compiling Blasr via make (following the guide). I am getting the compilation error below - do you have any clues how to fix this? Ubunru16.04, GCC version 5.4.0.

`g++ -O3 -g -DSHA1_7=\"574e1c2\" -std=c++0x -pedantic -Wall -Wextra -Wno-div-by-zero -Wno-overloaded-virtual -MMD -MP -fno-builtin-malloc -fno-builtin-calloc -fno-builtin-realloc -fno-builtin-free -fno-omit-frame-pointer  -I/home/mkolmogo/blasr_install/blasr/libcpp/alignment -I/home/mkolmogo/blasr_install/blasr/libcpp/hdf -I/home/mkolmogo/blasr_install/blasr/libcpp/pbdata -I/home/mkolmogo/blasr_install/hdf5/hdf5-1.8.19-linux-centos7-x86_64-gcc485-shared/include/  -c -o Blasr.o Blasr.cpp
Blasr.cpp: In function ‘int main(int, char**)’:
Blasr.cpp:1355:73: error: no matching function for call to ‘ReaderAgglomerate::Initialize(bool, bool&)’
         initReturnValue = reader->Initialize(true, params.polymeraseMode);
                                                                         ^
In file included from iblasr/BlasrHeaders.h:71:0,
                 from iblasr/BlasrMiscs.hpp:4,
                 from Blasr.cpp:3:
/home/mkolmogo/blasr_install/blasr/libcpp/alignment/files/ReaderAgglomerate.hpp:89:9: note: candidate: int ReaderAgglomerate::Initialize(std::__cxx11::string&)
     int Initialize(string &pFileName);
         ^
/home/mkolmogo/blasr_install/blasr/libcpp/alignment/files/ReaderAgglomerate.hpp:89:9: note:   candidate expects 1 argument, 2 provided
/home/mkolmogo/blasr_install/blasr/libcpp/alignment/files/ReaderAgglomerate.hpp:95:9: note: candidate: int ReaderAgglomerate::Initialize(FileType&, std::__cxx11::string&)
     int Initialize(FileType &pFileType, string &pFileName);
         ^
/home/mkolmogo/blasr_install/blasr/libcpp/alignment/files/ReaderAgglomerate.hpp:95:9: note:   no known conversion for argument 1 from ‘bool’ to ‘FileType&’
/home/mkolmogo/blasr_install/blasr/libcpp/alignment/files/ReaderAgglomerate.hpp:99:9: note: candidate: int ReaderAgglomerate::Initialize(bool)
     int Initialize(
         ^
/home/mkolmogo/blasr_install/blasr/libcpp/alignment/files/ReaderAgglomerate.hpp:99:9: note:   candidate expects 1 argument, 2 provided
<builtin>: recipe for target 'Blasr.o' failed
make: *** [Blasr.o] Error 1`

**Comment by armintoepfer** [comment]
We won't support source builds from now on, but provide the latest version on bioconda:
`conda install -c bioconda blasr`
