### ISSUE TITLE
Update libcpp submodule revision

### ISSUE THREAD

**Issue by lparsons** [PacificBiosciences/blasr#365]
The libcpp submodule revision currently pointed to by the blasr repository seems out of date. This is causing various compilation issues, including https://github.com/PacificBiosciences/blasr/issues/343 and possibly https://github.com/PacificBiosciences/blasr/issues/355.

**Comment by armintoepfer** [comment]
In the install docs, we recommend to use `git submodule update --init --remote`

**Comment by lparsons** [comment]
Yes, but git submodules are pinned to specific commit ids, in this case, `libcpp @ 37074e0` and `pbbam @ 601740f` which are a bit old, and I believe are causing issues. The update command you mentioned will only bring the submodules to the pinned revision. See attached screencap from github.

![image](https://user-images.githubusercontent.com/645128/29366970-6daa3bbe-8269-11e7-9679-7346a1671c8b.png)

**Comment by samfux84** [comment]
You can fix the problem by adding one step (5.) to the pac bio installation instructions:

1.) git clone git://github.com/PacificBiosciences/blasr.git 5.3
2.) cd 5.3
3.) git pull --rebase origin master && git submodule update --init
4.) make update-submodule
5.) cd libcpp && git pull origin master && cd ..
6.) ./configure.py --shared --sub --no-pbbam HDF5_INCLUDE=/cluster/apps/hdf5/1.8.12/x86_64/gcc_4.8.2/serial/include HDF5_LIB=/cluster/apps/hdf5/1.8.12/x86_64/gcc_4.8.2/serial/lib --submodules
7.) make configure-submodule
8.) make build-submodule
9.) make

**Comment by QiushiLi** [comment]
@samfux84 
Thank you sooooooooooo much! You saved my long weekend!

**Comment by pb-cdunn** [comment]
```ini
$ cat .gitmodules
[submodule "libcpp"]
        path = libcpp
        url = ../blasr_libcpp.git
    branch = master
[submodule "pbbam"]
        path = pbbam
        url = ../pbbam.git
        branch = master
```
