### ISSUE TITLE
ERROR, FASTA entry must begin with "+"

### ISSUE THREAD

**Issue by zijuexiansheng** [PacificBiosciences/blasr#366]
Both me and my colleague encountered this error. The version of my Blasr is 5.3.8c16f52 installed through pitchfork. The file is actually a fastq file. I converted the original fasta file to fastq file by assigning the quality score as "!", just for easier downstream analysis. So any idea of the cause of this error. Or if the issue has been fixed, could you tell me how to update the Blasr version through pitchfork? I didn't find the doc for that. Thanks.

**Comment by armintoepfer** [comment]
A minimal example file that causes the crash is necessary to debug your
issue.

**Comment by zijuexiansheng** [comment]
@armintoepfer Thanks for the help. I just found the reason. Blasr started reading the file before it was closed. So the file was incomplete. So I just flushed the data into the file before Blasr started reading the file, just in case that the file descriptor was not garbage collected in time, and it worked. Thank you very much.
