### ISSUE TITLE
How does blasr determine hard clipping length?

### ISSUE THREAD

**Issue by hisakatha** [PacificBiosciences/blasr#367]
I am analyzing PacBio Sequel data using `blasr` via `pbsmrtpipe`, and I have found that my bam files contain hard clipped regions (CIGAR `H` operations). I wonder how `blasr` determine the lengths of hard clipped regions. However, I couldn't find any documentation regarding it, so could you update the documents?
It seems to me that a hard clipped region ranges from each end of a subread to the left(right)-most end of the subreads in the same polymerase read, but I came up with a possibility that a hard clipped region ranges from each end of a subread to the end of the polymerase read. Which one (or neither) is correct?

**Comment by ylipacbio** [comment]
BLASR v5.0+ SAM/BAM output should never have hard clipping ‘H’ in CIGAR, the query sequence reported in SAM/BAM is the subread sequence. 
And CIGAR will report not aligned subread bases in the ends as soft clipping.  
sum of ‘X=IS’ computed from CIGAR must equal subread length (subread_end - subread_start)

**Comment by hisakatha** [comment]
Thank you for your reply.
Actually, my outputs from BLASR have hard clipping, though the version of BLASR is 5.0+.
I used `samtools` version 1.7 to convert bam files (BLASR outputs) into sam files, and checked the version of BLASR from the header lines in the sam files. I used BLASR in two environments:

1. The sam header contains `@HD     VN:1.5  SO:coordinate   pb:3.0.1` and `@PG     ID:1    PN:BLASR        VN:5.3. CL:...`; the version of smrtlink is 5.0.1; the samples I used were sequenced with PacBio RS II
2. The sam header contains `@HD     VN:1.5  SO:coordinate   pb:3.0.1` and `@PG     ID:1    PN:BLASR        VN:5.3.5b30da0  CL:...`; the version of smrtlink is 4.0.0; the samples I used were sequenced with PacBio Sequel

(I have omitted the content of CL tag.)
In both environments, my bam outputs from BLASR have hard clipping. For example, my bam output in the first environment have the following line (when I used `samtools` version 1.7):
```
m131114_030416_42177R_c100595942550000001823093405201475_s1_p0/14581/7918_8053  0       NZ_CP011330.1   40576   254     7918H2S7=1D2=3I8=1I4=1I1X8=2X2=1X1=1I3=1D2=1D1=1I1X18=1I1=1X3=1I3=1D3=1I1=1X15=1D6=1I3=1I7=1X4=2I6=3S5822H   ...
```

Do you mean this is a bug?
