### ISSUE TITLE
Samtools error "CIGAR and query sequence are of different length"

### ISSUE THREAD

**Issue by a-velt** [PacificBiosciences/blasr#373]
Dear PacBio team,

I used blasr (version 5.3.f24b84f) installed from Pitchfork to align some sequences (haplotigs) on my new genome assembly generated with FALCON. I used the following command : 

```
blasr --cigarUseSeqMatch --unaligned "unmapped_haplotigs.txt" --bestn 1 --bam --nproc 8 --out alignment_of_haplotigs_against_primary_contigs_corrected_assembly.bam \
corrected_assembly_haplotigs.for_blasr.fasta \
corrected_assembly.fasta
```

To make blasr work, I added "/0/0_10" after each haplotig's sequence name in order to have a "pacbio read" format, else blasr generates an error.

I have sorted the BAM file generated by blasr with samtools without error. Then, I have selected certains alignments in the BAM file, so I returned to a SAM file, I selected my alignements and then, I wanted to returned to a BAM file. I typed the following command : 

`samtools view -bS alignment_of_haplotigs_against_primary_contigs_corrected_assembly.to_keep.sam > alignment_of_haplotigs_against_primary_contigs_corrected_assembly.to_keep.bam`

> [E::sam_parse1] CIGAR and query sequence are of different length
> [W::sam_read1] parse error at line 1922
> [main_samview] truncated file.

I don't understand this error because I used the option "--cigarUseSeqMatch" in blasr, as you said in a other post in this forum (https://github.com/PacificBiosciences/blasr/issues/50). Without this option, I have the same error. Have you an idea about this error ?

Thank you.
Best,
Amandine

EDIT : 
One of the lines posing problems for the conversion of sam to bam is : 

`000032F_012/0/0_580703	0	000032F	808803	254	10S313=1X1198=1X1167=1X85=1X137=1X1209=1X60=1X65=1X1461=1X346=1I220=8I2=1I1=1I36=2I340=1X193=1X47=2X179=1X51=1X23=1X7=1X164=1X90=1X39=1D11=1X45=1X62=1X18=2X11=1X25=1X211=1D7=1D278=1X766=1X316=1X367=3D1=1D1=1D1=9D9=1X2=1X233=1X53=1X31=1X83=3D1.....	*	0	0	MA======AV======MA======CV======RA======GV======AA======CV======GA======AV======MA======AV======AA======AV======AA======MV======TA======RV======AA======AV======RA======CV======WA======AV======MA======MV======WA=A====AV======AC======AT======RV======CA======AT======AV======CA======AV======AC======AV======AA======AV======AA======CV======CT......N====TTTGTTTCATAAATCACGTGAGGTTGTTTTTGCTGTGAAAAGAATACAATAATAGACGAGTTCTAAGAAACATTAGTACTCGTGAAAATAAAAGATATCCAATATAGATGAGTACTAAGAAATGCTAATTCTCATGAAATCAAAGATATTCAATTTTGTTGATTAAAACTAGGGAAGAAACTTTGTGAGTAGGTTACTTCAGAAGATGCTTTCATACTCCCTTTGCAGTCATTCAAGGCATAATATTTTTACTATGAGCCACTATCATTCAAGCACATTTATATAGTTCTAATTATTTAAATATATAGTTACAATTATAAAATATATGAAATTATGAGGATATCTTTTGTATTTTGTTTTTCCCTTTACTAAGATTGTATTTTCATTTTATGCAGTTTGAAAAGATGAATGGTGGGAAATTCATTAGAAATCTGTTTGACATTCAAGTTCCAATTATAAGCAGCCAAGAGTTAGTTGCTAAAGTTGGGAAATTAAAGTTGAAAGAAAAACCAGGAACATCAGATTCTTTATCAAATCGGGGGCCCTAGATATAGGGCAGATTTGTTGCAGATAATCAGATGGTGGGGAAAACATGTGGGGATGAGTTAGCATCAATAAGTACTCACTGAAATGCATTGCTAACAGAAAAGGCAAAGCCCTTTTATATCTGAATTAAGCTAGGAAATCCTAAACAACTAAAAAC......	*	RG:Z:5cc74ca9	np:i:1	qe:i:580703	qs:i:0	zm:i:0	AS:i:-1127693	NM:i:259497`

And if I type : 

> samtools view alignment_of_haplotigs_against_primary_contigs_corrected_assembly.bam | grep "000032F_012"

I have the same result, so I think it's a problem from blasr not from the steps I've done after.

**Comment by armintoepfer** [comment]
Please try the latest version.
