### ISSUE TITLE
LibBlasrConfig.h missing when `make blasr`

### ISSUE THREAD

**Issue by lufuhao** [PacificBiosciences/blasr#375]
**uname -a**
Linux v0267 2.6.32-431.el6.x86_64 #1 SMP Fri Nov 22 03:15:09 UTC 2013 x86_64 x86_64 x86_64 GNU/Linux

 **gcc --version**
gcc (GCC) 5.2.0
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

**git describe --always --dirty='*'**
f72428d

**$ make blasr**
g++ -O3 -g -DSHA1_7=\"f72428d\" -std=c++14 -pedantic -Wall -Wextra -Wno-div-by-zero -Wno-overloaded-virtual -MMD -MP -fno-builtin-malloc -fno-builtin-calloc -fno-builtin-realloc -fno-builtin-free -fno-omit-frame-pointer -I/nbi/software/production/bin/core/../..//hpccore/5/x86_64/include -I/nbi/software/production/bin/core/../..//R/3.1.0/x86_64/include  -I/usr/users/celldev/luf/local/blasr/ver/blasr/libcpp/alignment -I/usr/users/celldev/luf/local/blasr/ver/blasr/libcpp/hdf -I/usr/users/celldev/luf/local/blasr/ver/blasr/libcpp/pbdata -I/usr/users/celldev/luf/local/GNU/hdf5/v1.8.19/x86_64/include  -c -o Blasr.o Blasr.cpp
In file included from iblasr/BlasrMiscs.hpp:4:0,
                 from Blasr.cpp:3:
iblasr/BlasrHeaders.h:22:28: fatal error: LibBlasrConfig.h: No such file or directory
compilation terminated.
make: *** [Blasr.o] Error 1

**Comment by rubyg0229** [comment]
I have been working on this installation for the past several days and am having this same issue.

**Comment by tumpa** [comment]
me as well facing the same problem.

**Comment by ebioman** [comment]
Here similar problem as well

**Comment by dunn0404** [comment]
ebioman: Where did you pull the new version of blasr_libcpp? I don't see any newer than two months ago, e.g. https://github.com/PacificBiosciences/blasr_libcpp

**Comment by ebioman** [comment]
@dunn0404 that one is fine, just verify that the makefile contains the section:

    libpbdata:
	${MAKE} -C ${THISDIR}/pbdata LibBlasrConfig.h
    ${MAKE} -C ${THISDIR}/pbdata all

I compiled it using:

    ./configure.py --enable-cxx HDF5_INC=/software/include/ HDF5_LIB=/software/lib/ HTSLIB_LIB=$HTSLIB_ROOT/lib/ HTSLIB_INC=$HTSLIB_ROOT/include/

    make all

Replacing the variables with your setup.

**Comment by jazberna1** [comment]
same error following instructions here:
[](https://github.com/PacificBiosciences/blasr/wiki/Step-by-step-blasr-installation-example)

In file included from iblasr/BlasrMiscs.hpp:4:0,
                 from Blasr.cpp:3:
iblasr/BlasrHeaders.h:22:28: fatal error: LibBlasrConfig.h: No such file or directory
 #include <LibBlasrConfig.h>
                            ^
compilation terminated.
make: *** [Blasr.o] Error 1

**Comment by armintoepfer** [comment]
We won't support source builds from now on, but provide the latest version on bioconda:
`conda -c bioconda install blasr`
