### ISSUE TITLE
How to avoid compiling pbbam using cmake

### ISSUE THREAD

**Issue by lufuhao** [PacificBiosciences/blasr#376]
How to avoid compiling pbbam using cmake?

make blasr reported error. so I would like to try cmake

pbbam needs lots of dependencies. so need to ignore that

Is there any parameter to pass to cmake to ignore pbbam compilation?

**Comment by armintoepfer** [comment]
We won't support source builds from now on, but provide the latest version on bioconda:
`conda -c bioconda install blasr`
