### ISSUE TITLE
BLASR Runing Problem：symbol lookup error

### ISSUE THREAD

**Issue by LotusWang0723** [PacificBiosciences/blasr#377]
I met a symbol lookup error when I ran BLASR.

My workstation system is  Ubuntu 16.04.1 LTS (GNU/Linux 3.13.0-105-generic x86_64) and my BLASR version is V5.1. By the way, my HDF5 version is 1.8.17-11

My command is :
`$ blasr E_R73_nomal_reads.fasta Ref.fa --header -m 5 --out E_R73_N_out`

and the error report is :
`[INFO] 2017-11-07T17:38:15 [blasr] started.
blasr: symbol lookup error: blasr: undefined symbol: _ZN15FileOfFileNames18ExpandFileNameListERSt6vectorISsSaISsEE`

My input querry data (E_R73_nomal_reads.fasta) is like this :
>ENA|U00096|read1
AGGCAAA.....
>ENA|U00096|read2
GCGTCGGC.....
.....

And reference file is like this:
>ENA|U00096|U00096.3_Escherichia_coli_str._K-12_substr._MG1655,_complete_genome. 
AGCTTTTCATTCTGACTGCAACGGGCAATATGTCTCTGTGTGGATT.....

Is there anything I can do to solve this problem?

**Comment by VanceEver** [comment]
Hello,did you solve this problem?It seems that I met the same problem.

**Comment by lijingbu** [comment]
Same problem here. I installed blasr with miniconda. Some posts say that it's caused by using different hdf5 library. 
I used command `conda install blasr` to install blasr, which seems fine. 
`conda list hdf5`

> Name                    Version                   Build  Channel
>hdf5                      1.10.2               hba1933b_1

But runing `blasr` gives error 
> cannot find libhdf5_cpp.so.12 

Then, I created link with `ln -s ~/miniconda2/lib/libhdf5_cpp.so.102.0.0 ~/miniconda2/lib/libhdf5_cpp.so.12`
Then 
> cannot find libhdf5.so.10

add
`ln -s ~/miniconda2/lib/libhdf5_cpp.so.102.0.0 ~/miniconda2/lib/libhdf5_cpp.so.12`

Then blasr seems to be working. But when give it real sequences, it says
>blasr: symbol lookup error: blasr: undefined symbol: _ZN15FileOfFileNames18ExpandFileNameListERSt6vectorISsSaISsEE

Any idea where I did wrong?

**Comment by lijingbu** [comment]
This works, thanks to zachcp's comment at https://github.com/bioconda/bioconda-recipes/issues/4004

`conda create -n blasr blasr=5.2p1 hdf5=1.8.17`

**Comment by VanceEver** [comment]
I also had the same problem before.I found that it seems to be version incompatibility, you can install blasr 5.1 with anaconda.And it will be work.
code:
conda install -c samesense blasr

**Comment by LotusWang0723** [comment]
Yes, I used command $ conda install blasr to install BLASTR, but you need to make sure you install Anaconda first.

在 2018-04-23 16:51:50，"曹磊" <notifications@github.com> 写道：


Hello,did you solve this problem?It seems that I met the same problem.

**Comment by armintoepfer** [comment]
We won't support source builds from now on, but provide the latest version on bioconda:
`conda -c bioconda install blasr`
