### ISSUE TITLE
What is the right package to build if I want a stable blasr, and ...

### ISSUE THREAD

**Issue by rsharris** [PacificBiosciences/blasr#381]
... and how do I build it?

(1) My guess is that it should be the one found in https://github.com/PacificBiosciences/blasr/archive/smrtanalysis-4.0.0.tar.gz .  But README.ISNTALL.md in that tarball tells me to clone the source code, then do a "git pull", then "make update-submodule" and so on.  What's the purpose of the tarball if I'm supposed to fetch the whole mess from github?

(2) So I went ahead and followed all those instructions (NOT using the contents of the tarball), including (I believe) properly pointing it at my 1.10.1 hdf install.  Which then fails to compile as described in issue 355.

(3) I can't tell what the solution to issue 355 is.  It ends with sjackman asking lparsons if he's using the 4.0.0 release of blasr.  But does 4.0.0 *solve* the problem or does 4.0.0 *cause* the problem?

(4) my best guess is that 4.0.0 is what I'm supposed to use.  But where should I hop into the installation instructions there?  i.e. which steps should I skip?

**Comment by rsharris** [comment]
While I never figured out the answer to the question above, I did find some other installation instructions in issue 365.  Following those instructions I don't the same issue 355 failure.  But I get a new failure involving PacBio namespace, which I'm opening as a new issue.

**Comment by armintoepfer** [comment]
Why don't you download the official binary smrtanalysis build, provided by
pacbio?

**Comment by rsharris** [comment]
Thanks Armin.  Sounds like a great idea. Didn't know that existed until you mentioned it.  I was waylaid by the first two lines of the readme in the repo -- "Wiki: all you need to know" and "build from source", and followed those instead of reading down to discover the link to "official and stable SMRT Analysis builds provided by PacBio."

That said, it's not clear to me that there's an official binary that will run on a mac.  Am I correct?

The only reason I'm trying to get blasr is that I want to evaluate PacmonSTR, which claims blasr as a dependency.  Ummat, Ajay, and Ali Bashir. "Resolving complex tandem repeats with long
reads." Bioinformatics 30.24 (2014): 3491-3498. https://github.com/alibashir/pacmonstr

It's not clear whether I would need anything else from the SMRT Analysis package.  My expectation was all I needed to be able to do was take pacbio reads (which I have) and a reference, align them using blasr and feed results to PacmonSTR.  I don't expect my data to be large enough to benefit from a cluster (though I do have access to one), and thus figured I should be able to run all this on my desktop mac.  I'm not familiar enough with blasr (having never used it) to know if it requires other parts of the SMRT Analysis package

Am I off in the woods?

Thanks for your help.

**Comment by mchaisso** [comment]
I've actually had decent success compiling pacbio's blasr with the most
recent pitchfork: https://github.com/PacificBiosciences/pitchfork , and
difficulty otherwise.

FWIW, my repo (github.com/mchaisso/blasr) just requires hdf compiled with
c++ (./configure --enable-cxx=true when building hdf), and works with Ali's
code.

best,
-mark

**Comment by mchaisso** [comment]
P.S. I'm a big lastz fan.

**Comment by rsharris** [comment]
Cool, Mark, thanks.  I'll take a look at those avenues today.

Thanks for the compliment as well!

**Comment by armintoepfer** [comment]
We won't support source builds from now on, but provide the latest version on bioconda:
`conda -c bioconda install blasr`
