### ISSUE TITLE
Error in SMRTSequence.hpp -- no member named 'BAM' in namespace 'PacBio'

### ISSUE THREAD

**Issue by rsharris** [PacificBiosciences/blasr#385]
I'm following the special build instructions given in issue 365 (posted on Aug/29).  This fails at the make build-submodule step, with the compiler complaining that there is "no member named 'BAM' in namespace 'PacBio'" while attempting to parse SMRTSequence.hpp.

My ./configure.py step was `./configure.py --shared --sub --no-pbbam HDF5_INCLUDE=/Users/grandpoobah/include HDF5_LIB=/Users/grandpoobah/lib --submodules`

Wild guess: does this relate to the issue of compiling without pbbam, mentioned in issue 376?  If so, this suggests SMRTSequence.hpp shouldn't be using BAM from that namespace.

Any thoughts on how to get around this?  I.e. what have I done wrong?

Also, if anyone could try to answer the question I raised in issue 381, that might REALLY be helpful.

Thanks.

**Comment by armintoepfer** [comment]
We won't support source builds from now on, but provide the latest version on bioconda:
`conda -c bioconda install blasr`
