### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by huangnengCSU** [PacificBiosciences/blasr#388]
when i step by step install blasr and run "make build-submodule", then an issue happens like:
In file included from FASTQSequence.hpp:4:0,
                 from SMRTSequence.hpp:11,
                 from CCSSequence.hpp:5,
                 from CCSSequence.cpp:1:
DNASequence.hpp:11:23: fatal error: libconfig.h: No such file or directory
compilation terminated.
can you help me?

**Comment by pb-cdunn** [comment]
Use [pitchfork](https://github.com/PacificBiosciences/pitchfork), or try to build using [Meson](https://github.com/PacificBiosciences/blasr/blob/master/meson.build) (which we use, but we cannot help you with right now).
