### ISSUE TITLE
Installimg blaser with cmake fail

### ISSUE THREAD

**Issue by Lcornet** [PacificBiosciences/blasr#390]
Hello i try to install blaser (in order to install pbalign and quiver0 but i have some problem
I run the following command to install blaser :
 git clone git://github.com/PacificBiosciences/blasr.git && cd blasr
    git submodule update --init --remote
    mkdir build && cd build
    cmake .. && make

and i get this error :  
-- The CXX compiler identification is GNU 7.2.0
-- The C compiler identification is GNU 7.2.0
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
CMake Error at /usr/share/cmake-3.9/Modules/FindBoost.cmake:1898 (message):
  Unable to find the requested Boost libraries.

  Unable to find the Boost header files.  Please set BOOST_ROOT to the root
  directory containing Boost or BOOST_INCLUDEDIR to the directory containing
  Boost's headers.
Call Stack (most recent call first):
  cmake/blasr-dependencies.cmake:6 (find_package)
  CMakeLists.txt:30 (include)

-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.1") 
-- Checking for module 'zlib'
--   No package 'zlib' found
-- Checking for module 'hdf5'
--   No package 'hdf5' found
--    HTSlib include dirs: 
--    HTSlib libraries: 
-- Performing Test HAS_NO_UNUSED_LOCAL_TYPEDEFS
-- Performing Test HAS_NO_UNUSED_LOCAL_TYPEDEFS - Success
-- Performing Test HAS_NO_SIGN_COMPARE
-- Performing Test HAS_NO_SIGN_COMPARE - Success
CMake Error at /usr/share/cmake-3.9/Modules/FindBoost.cmake:1898 (message):
  Unable to find the requested Boost libraries.

  Unable to find the Boost header files.  Please set BOOST_ROOT to the root
  directory containing Boost or BOOST_INCLUDEDIR to the directory containing
  Boost's headers.
Call Stack (most recent call first):
  pbbam/cmake/pbbam-dependencies.cmake:7 (find_package)
  pbbam/CMakeLists.txt:55 (include)

-- Checking for module 'zlib'
--   No package 'zlib' found
--    HTSlib include dirs: 
--    HTSlib libraries: 
-- Could NOT find Doxygen (missing: DOXYGEN_EXECUTABLE) 
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
/home/lcornet/Documents/Program/blasr/pbbam/src/Boost_INCLUDE_DIR
   used as include directory in directory /home/lcornet/Documents/Program/blasr/pbbam/src
Boost_INCLUDE_DIR (ADVANCED)
   used as include directory in directory /home/lcornet/Documents/Program/blasr
   used as include directory in directory /home/lcornet/Documents/Program/blasr
   used as include directory in directory /home/lcornet/Documents/Program/blasr
   used as include directory in directory /home/lcornet/Documents/Program/blasr
   used as include directory in directory /home/lcornet/Documents/Program/blasr
   used as include directory in directory /home/lcornet/Documents/Program/blasr
   used as include directory in directory /home/lcornet/Documents/Program/blasr
   used as include directory in directory /home/lcornet/Documents/Program/blasr
   used as include directory in directory /home/lcornet/Documents/Program/blasr
   used as include directory in directory /home/lcornet/Documents/Program/blasr
   used as include directory in directory /home/lcornet/Documents/Program/blasr
   used as include directory in directory /home/lcornet/Documents/Program/blasr
   used as include directory in directory /home/lcornet/Documents/Program/blasr
   used as include directory in directory /home/lcornet/Documents/Program/blasr
   used as include directory in directory /home/lcornet/Documents/Program/blasr
   used as include directory in directory /home/lcornet/Documents/Program/blasr
   used as include directory in directory /home/lcornet/Documents/Program/blasr
   used as include directory in directory /home/lcornet/Documents/Program/blasr
   used as include directory in directory /home/lcornet/Documents/Program/blasr
   used as include directory in directory /home/lcornet/Documents/Program/blasr

-- Configuring incomplete, errors occurred!
See also "/home/lcornet/Documents/Program/blasr/build/CMakeFiles/CMakeOutput.log".
See also "/home/lcornet/Documents/Program/blasr/build/CMakeFiles/CMakeError.log".

Could you help me ?

**Comment by armintoepfer** [comment]
You have not specified BOOST. Why are you trying to compile it manually, instead of downloading the official version from https://www.pacb.com/support/software-downloads/?

**Comment by Lcornet** [comment]
Thanks for your answer.  I don't download the SMRT link since i just need specific programs (blasr-pbaliign-quiver) to run in routine and not the whole package (which is just graphical interface, right ?).

I now specify BOOST but is still have some problems : 
[ 64%] Built target deps
Scanning dependencies of target sawriter
[ 64%] Building CXX object CMakeFiles/sawriter.dir/utils/SAWriter.cpp.o
make[2]: *** No rule to make target 'external/pbbam/build/lib/libpbbam.a', needed by 'sawriter'.  Stop.
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/sawriter.dir/all' failed
make[1]: *** [CMakeFiles/sawriter.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2

This correspond to this issue https://github.com/PacificBiosciences/blasr/issues/330  but make -j and ninja didn't solve it.  I also try the step by step installation https://github.com/PacificBiosciences/blasr/wiki/Step-by-step-blasr-installation-example but i face this issue https://github.com/PacificBiosciences/blasr/issues/375 that i don't manage to solve. 

Thanks for help.

**Comment by armintoepfer** [comment]
The official package has a command-line only install option that I really recommend you. What's the point of fighting a build system, if there is a build ready to download?

**Comment by Lcornet** [comment]
Yes you right thanks. I don't figured that the SMRT has a command line option.
Unfortunately, i also have a problem with the SMRT analysis : https://github.com/PacificBiosciences/SMRT-Analysis/issues/347 .
