### ISSUE TITLE
error: ‘class H5::H5Location’ has no member named ‘iterateAttrs’

### ISSUE THREAD

**Issue by yangxiaofeill** [PacificBiosciences/blasr#391]
I want to install blasr software.
I run configure.py as `./configure.py --shared --sub --no-pbbam HDF5_LIB=/opt/software/hdf5_1.8.6/hdf5-1.8.16/lib/ HDF5_INCLUDE=/opt/software/hdf5_1.8.6/hdf5-1.8.16/include/,` where /opt/software/hdf5_1.8.6/hdf5_1.8.16/ is the path of HDF5 includes and library (downloaded from https://support.hdfgroup.org/ftp/HDF5/releases/hdf5-1.8/hdf5-1.8.16/bin/linux-centos7-x86_64-gcc483/ ).

When I run the make build-submodule command, the error message as:
`make -C libcpp
make[1]: Entering directory `/opt/software/blasr/libcpp'
make libpbdata
make[2]: Entering directory `/opt/software/blasr/libcpp'
make -C /opt/software/blasr/libcpp//pbdata libconfig.h
make[3]: Entering directory `/opt/software/blasr/libcpp/pbdata'
make[3]: `libconfig.h' is up to date.
make[3]: Leaving directory `/opt/software/blasr/libcpp/pbdata'
make -C /opt/software/blasr/libcpp//pbdata all
make[3]: Entering directory `/opt/software/blasr/libcpp/pbdata'
make[3]: Nothing to be done for `all'.
make[3]: Leaving directory `/opt/software/blasr/libcpp/pbdata'
make[2]: Leaving directory `/opt/software/blasr/libcpp'
make libpbihdf
make[2]: Entering directory `/opt/software/blasr/libcpp'
make -C /opt/software/blasr/libcpp//hdf all
make[3]: Entering directory `/opt/software/blasr/libcpp/hdf'
g++ -std=c++11 -pedantic -Wall -Wextra -Wno-overloaded-virtual   -I/opt/software/hdf5/include/  -c HDFAttributable.cpp -o HDFAttributable.o
HDFAttributable.cpp: In member function ‘void HDFAttributable::StoreAttributeNames(H5::H5Location&, const std::vector<std::basic_string<char> >&)’:
HDFAttributable.cpp:21:16: error: ‘class H5::H5Location’ has no member named ‘iterateAttrs’
     thisobject.iterateAttrs(&CallStoreAttributeName, bounds, (void *)&attributeNames);
                ^
make[3]: *** [HDFAttributable.o] Error 1
make[3]: Leaving directory `/opt/software/blasr/libcpp/hdf'
make[2]: *** [libpbihdf] Error 2
make[2]: Leaving directory `/opt/software/blasr/libcpp'
make[1]: *** [all] Error 2
make[1]: Leaving directory `/opt/software/blasr/libcpp'
make: *** [build-submodule] Error 2`

I don't know why and how to solve this problem, please help me?

**Comment by pb-cdunn** [comment]
`hdf5_1.8.6/hdf5-1.8.16`

How can you have both `1.8.6` and `1.8.16`? You might be mixing libraries and headers. I have seen missing symbol errors for ‘iterateAttrs’ at link-time, but not at compile-time. E.g.
* https://github.com/PacificBiosciences/blasr/issues/189
* https://github.com/PacificBiosciences/blasr/issues/116
* https://github.com/PacificBiosciences/blasr/issues/266
* https://github.com/PacificBiosciences/blasr/issues/125

Those might not help. But as #266 says, you can try
*  https://dl.dropboxusercontent.com/u/70124057/hdf5-1.8.16_centos5_gcc5.3.0_noszip.tar.gz

> ‘class H5::H5Location’ has no member named ‘iterateAttrs’

I noticed from a web-search that `iterateAttrs` is gone in HDF5 1.10.1, so maybe your version is too *recent*. But I see it on `H5Object`:
* https://support.hdfgroup.org/HDF5/doc/cpplus_RM/class_h5_1_1_h5_location.html
* https://support.hdfgroup.org/HDF5/doc/cpplus_RM/class_h5_1_1_h5_object.html#a06836076a40d8677256dbd89563e7578

But at a different site, I *do* see it:
* http://transit.iut2.upmf-grenoble.fr/cgi-bin/dwww/usr/share/doc/libhdf5-doc/html/cpplus_RM/class_h5_1_1_h5_location.html#aad71c39cd20e8539891766571174d12a (`1.10.0-patch1 currently under development`)

So I'm quite confused by HDF5 docs.

There is only so much support we can offer on integration problems. Good luck!
