### ISSUE TITLE
Does blasr output hard clipping?

### ISSUE THREAD

**Issue by hisakatha** [PacificBiosciences/blasr#392]
According to #367 

> BLASR v5.0+ SAM/BAM output should never have hard clipping ‘H’ in CIGAR, the query sequence reported in SAM/BAM is the subread sequence.

However, my outputs from BLASR have hard clipping, though the version of BLASR is 5.0+.
I used `samtools` version 1.7 to convert bam files (BLASR outputs) into sam files, and checked the version of BLASR from the header lines in the sam files. I used BLASR in two environments:

1. The sam header contains `@HD     VN:1.5  SO:coordinate   pb:3.0.1` and `@PG     ID:1    PN:BLASR        VN:5.3. CL:...`; the version of smrtlink is 5.0.1; the samples I used were sequenced with PacBio RS II
2. The sam header contains `@HD     VN:1.5  SO:coordinate   pb:3.0.1` and `@PG     ID:1    PN:BLASR        VN:5.3.5b30da0  CL:...`; the version of smrtlink is 4.0.0; the samples I used were sequenced with PacBio Sequel

(I have omitted the content of CL tag.)
In both environments, my bam outputs from BLASR have hard clipping. For example, my bam output in the first environment have the following line (when I used `samtools` version 1.7):
```
m131114_030416_42177R_c100595942550000001823093405201475_s1_p0/14581/7918_8053  0       NZ_CP011330.1   40576   254     7918H2S7=1D2=3I8=1I4=1I1X8=2X2=1X1=1I3=1D2=1D1=1I1X18=1I1=1X3=1I3=1D3=1I1=1X15=1D6=1I3=1I7=1X4=2I6=3S5822H   ...
```

Do you mean this is a bug? If not, I would like your team to update the document of BLASR and to tell me how the length of hard clipping is determined.

**Comment by armintoepfer** [comment]
Hard clipping is with respect to the polymerase coordinate system. A subread can be a region of a longer read, we call polymerase read that can contain multiple subreads and adapters. The hard clips are equal to the length of the preceding and succeeding bases not included in the subread of interest. Bases of the subread not aligned, are marked with soft clipping.
