### ISSUE TITLE
Conda Install Fails

### ISSUE THREAD

**Issue by charliecurnin** [PacificBiosciences/blasr#395]
Installing blasr with conda doesn't seem to work. 

```
[ccurnin@sh-ln03 login! /scratch/PI/euan/projects/scotch]$ conda install -c bioconda blasr
...
[ccurnin@sh-ln03 login! /scratch/PI/euan/projects/scotch]$ blasr -h
blasr: error while loading shared libraries: libhdf5_cpp.so.12: cannot open shared object file: No such file or directory
```

**Comment by charliecurnin** [comment]
I fixed this by creating these symlinks
```
ln -s libhdf5.so.101 libhdf5.so.10   
ln -s libhdf5_cpp.so.101 libhdf5_cpp.so.12
```

**Comment by pb-dseifert** [comment]
1) creating those symlinks is extremely dangerous, as they indicate an ABI break
2) please retry `conda install -c bioconda blasr`, I fixed the version mix in the Anaconda cloud, it should pull in 5.3.2 now

**Comment by bbalog87** [comment]
Unfurtunately `even ``conda install -c bioconda blasr``` did not solve the problem.
 I still get the same error ```blasr: error while loading shared libraries: libpbihdf.so: cannot open shared object file: No such file or directory```

**Comment by pb-dseifert** [comment]
You likely have a stale repository - `libpbihdf.so` does not exist anymore in the latest build of blasr/blasr_libcpp on Bioconda.
