### ISSUE TITLE
--bestn definition

### ISSUE THREAD

**Issue by imneuro** [PacificBiosciences/blasr#397]
We notice pbalign used the blasr without (--bestn n). We could like to know how the bestn is defined. If a 5k read can be aligned to 2 different locations with different alignment length and different deletion sizes, how to choose the best one?  The version we used for pbalign is 0.3.1, blasr 5.3.

**Comment by ylipacbio** [comment]
blasr `--bestn` specifies the maximum number of alignments per query read which will be evaluated. It is equivalent to pbalign `--maxHit` option.

blasr `--hitPolicy` specifies among all evaluated alignments which alignments will be reported to output. 

The default value is `pbalign --maxHit 10 --hitPolicy randombest` (which is equivalent to `blasr --bestn 10 --hitPolicy randombest`) , meaning:
- at most 10 alignments per query read will be evaluated
- out of all evaluated alignments, only one alignment will be reported, and the reported alignment must have the best score, if multiple evaluated alignments have the same best score, an arbitrary one will be reported.

To specify blasr --bestn, for example 20, either one of the following should work:
- `pbalign input reference output --maxHits  20`
- `pbalign input reference output --algorithmOptions "--bestn 20"`

If you want pbalign to report all evaluated alignments, please use `--hitPolicy all`. For other hit policy please see pbalign help below.

Below is a brief pbalign help with irrelevant information removed:
```
usage: pbalign

positional arguments:
  inputFileName         SubreadSet or unaligned .bam
  referencePath         Reference DataSet or FASTA file
  outputFileName        Alignment results dataset

Alignment options:
  --maxHits MAXHITS     The maximum number of matches of each read to the
                        reference sequence that will be evaluated. (default:
                        None)
  --algorithmOptions ALGORITHMOPTIONS
                        Pass alignment options through. (default: None)

Filter criteria options:
   --hitPolicy {randombest,allbest,random,all,leftmost}
                        Specify a policy for how to treat multiple hit random
                        : selects a random hit. all : selects all hits.
                        allbest : selects all the best score hits. randombest:
                        selects a random hit from all best score hits.
                        leftmost : selects a hit which has the best score and
                        the smallest mapping coordinate in any reference.
                        (default: randombest)
```
