### ISSUE TITLE
blasr --help does not give full help that -h does

### ISSUE THREAD

**Issue by peterjc** [PacificBiosciences/blasr#398]
It is a very widely used command line convention that ``binary_name -h`` and ``binary_help --help`` are how to get a tool's command line help, and that ``-h`` and ``--help`` are aliases and act the same.

While ``pbalign`` does this, ``blasr`` does not:

```
$ blasr --version
blasr	5.3.
$ blasr -h | wc
    250    1774   14234
$ blasr --help | wc
     64     406    2838
```

Actual Result

Using ``blasr --help`` gives a short summary with no indication that it is not the full help available via ``blasr -h``

Expected Result

Using ``blasr --help`` and ``blasr -h`` give the same full help text listing all command line options.

**Comment by mhsieh** [comment]
```
$ blasr
blasr - a program to map reads to a genome
 usage: blasr reads genome 
 Run with -h for a list of commands 
          --help for verbose discussion of how to run blasr.

In release v5.1 of BLASR, command-line options will use the 
single dash/double dash convention: 
Character options are preceded by a single dash. (Example: -v) 
Word options are preceded by a double dash. (Example: --verbose) 
Please modify your scripts accordingly when BLASR v5.1 is released. 
```
This seems to be the place that tells the differences. We will see what we can do to improve the UX.

**Comment by mhsieh** [comment]
(I meant to tag https://github.com/PacificBiosciences/blasr/commit/b3c3156519c9e83d49b95a5504f7ee1c213a1ed3 )

**Comment by peterjc** [comment]
Thank you - unifying ``-h`` and ``--help`` will hopefully save future users some confusion.
