### ISSUE TITLE
*** recipe commences before first target. Stop.

### ISSUE THREAD

**Issue by AlexWanghaoming** [PacificBiosciences/blasr#400]
Dear author,
I git clone your package---blasr tools. But I can not compile the .cpp files. Maybe there are some errors in Makefile?
Thanks

**Comment by armintoepfer** [comment]
Please study the README!
https://github.com/PacificBiosciences/blasr#availability

**Comment by AlexWanghaoming** [comment]
OK!
Thanks for your reply!

**Comment by AlexWanghaoming** [comment]
Dear Armin Töpfer,
Sorry, I did not expressed my question clearly. In this page https://github.com/PacificBiosciences/blasr_tools, for example I want to use the LoadPulses tools(Also there is a copy in https://github.com/PacificBiosciences/blasr/tree/develop/utils) if I use conda to install blasr, there is not a executable file for LoadPulses. I tried 'meson + ninja', but an error came up: Dependency "boost" not found!
Thanks for you attention
Alex
