### ISSUE TITLE
pls2fasta error: could not get the minimum and maximum hole numbers from ZMW HoleNumbers.

### ISSUE THREAD

**Issue by aechchiki** [PacificBiosciences/blasr#401]
Hi, I was trying extraction to fasta using utility`pls2fasta` - and I get an error:

`ERROR, could not get the minimum and maximum hole numbers from ZMW HoleNumbers`

Here is the detailed command-line that I run (following steps from [here](https://github.com/PacificBiosciences/pbh5tools/issues/24)): 

```
pls2fasta ZAsfUfaG_m150315_071532_42182_c100790302550000001823178109091543_s1_p0.bas.h5 test.fasta
```

And here is the full log:

```
[INFO] 2018-07-23T17:39:20 [pls2fasta] started.
ERROR, could not get the minimum and maximum hole numbers from ZMW HoleNumbers.
```

Of course I [tried to google the error](https://www.biostars.org/p/314299/), but the only hit I got was not helpful at all (see the very last comment to the reply).

Any input on what might be happening here?

Thanks 
Amina 

----

PS: 

Here are my BLASR version: 

```
5.3
```

Here are the OS details: 

```
$uname -a
Linux dee-serv07.vital-it.ch 3.10.0-693.17.1.el7.x86_64 #1 SMP Thu Jan 25 20:13:58 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```
```
$ cat /etc/*-release
CentOS Linux release 7.4.1708 (Core)
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

CentOS Linux release 7.4.1708 (Core)
CentOS Linux release 7.4.1708 (Core)

```

**Comment by aechchiki** [comment]
oh yes, definitely it *does* help a lot! just tried it on a sample *bax.h5. thanks @jkaralius !

giving that I have more than 1 flowcell to process, do you suggest:
1) creating a fofn list with all the *bax.h5 for each flowcell; or just
2) list all the *bax.h5 in the same fofn and just run the program?

best 
Amina

**Comment by pb-dseifert** [comment]
In general we do not support any input other than (un)aligned BAM in BLASR. Convert bax.h5 to BAM using [bax2bam](https://bioconda.github.io/recipes/bax2bam/README.html).

**Comment by aechchiki** [comment]
however, @pb-dseifert @jkaralius I still get some bax.h5 failing (and some are not) - do you have explanation for this? 

example for failing (for which I get an empty fasta file): 
```
m150427_084201_42182_c100810932550000001823181110291544_s1_p0.3.bax.h5
[INFO] 2018-07-24T12:40:21 [pls2fasta] started.
ERROR, could not get the minimum and maximum hole numbers from ZMW HoleNumbers.
```

example for successful:
```
maXheKIj_m150402_080121_42182_c100790382550000001823178109091563_s1_p0.1.bax.h5
[INFO] 2018-07-24T12:40:21 [pls2fasta] started.
[INFO] 2018-07-24T12:41:06 [pls2fasta] ended.
```

**Comment by pb-dseifert** [comment]
`pls2fasta` is not supported anymore, and I have no clue what could have lead to that failure.

**Comment by aechchiki** [comment]
ok, then I guess my only option to get the fasta out is bax2bam & then samtools bam2fq to get the reads out?

**Comment by pb-dseifert** [comment]
1. `bax2bam`
2. `bam2fastq`

Also remember, any alignment you do on your own will lead to an invalid PB BAM file, so if you wish to use PB utilities downstream, those will all fail.

**Comment by aechchiki** [comment]
ok - I just need to extract the reads & feed them to falcon. used to use pbh5tools for this, but having issues too atm - this is why I was trying `pls2fasta`.

**Comment by pb-dseifert** [comment]
FALCON can handle unaligned BAM files just fine. @pb-cdunn @isovic Right?

**Comment by isovic** [comment]
FALCON at the moment supports FASTA (as well as gzipped version of it) and Dexta formats, while BAM is not natively read at the moment. Conversion will be required for input.
