### ISSUE TITLE
mmap failure is not checked

### ISSUE THREAD

**Issue by mkasa** [PacificBiosciences/blasr#41]
at blasr/blob/master/common/FASTAReader.h:103, we see the code below::

    filePtr = (char*) mmap(0, fileSize, PROT_READ, MAP_PRIVATE, fileDes, 0);

but it seems that filePtr is not compared with NULL so it assumes that mmap
always succeeds, which is not true. When mmap fails, it causes segmentation
fault without showing an error message. I believe that we must show an error
message here.

One of Linux clusters I am using sets a policy in which the maximum amount of
virtual memory is limited to the amount of the physical memory allocated by a
job scheduler (presumably for limiting the amount of physical memory being used).
Alignment tools such as BLAST often uses mmap for reading input files, but
falls back to normal file I/O (w/o mmap) when it fails, so I hope BLASR will
implement this in the near future.

**Comment by ylipacbio** [comment]
The proposed fix has been reflected to the refactored blasr. Thank you very much for contributing to the blasr code base.
