### ISSUE TITLE
Could not read quality metrics

### ISSUE THREAD

**Issue by bdeonovic** [PacificBiosciences/blasr#45]
I tried to align pacbio long reads using:

```bash
blasr reads.bax.h5 genome.fa -nproc 16 -sam -out out.sam
```

but I got the following error:

```
[INFO] 2014-11-17T13:02:49 [blasr] started.
ERROR, could not read quality metrics for FASTQ Sequence 
```

**Comment by ylipacbio** [comment]
"ERROR, could not read quality metrics for FASTQ Sequence" means that the input bax.h5 is either corrupted or lack of some critical QV values, such that blasr could not read sequence with QVs. Please repair the bax.h5 file or use another file instead.
