### ISSUE TITLE
output qualities

### ISSUE THREAD

**Issue by map2085** [PacificBiosciences/blasr#47]
How can I make BLASR output the sequence's base-qualities in the unaligned file (and also in the SAM output) ?    (e.g. make an "unaligned.fq" instead of "unaligned.fa")

Thank you

**Comment by mchaisso** [comment]
This version of blasr outputs quality values and unmapped reads (with sam
unmapped reads flag)
https://github.com/mchaisso/blasr/

This version is not officially supported.

-mark

**Comment by ylipacbio** [comment]
Officially supported blasr can output quality values of `aligned` reads in SAM format with '-printSAMQV' tag, but does NOT print 'unaligned' reads with QVs.

To get QVs of `unaligned` reads, you may call pls2fasta to generate a fastq file from SMRTCells. The fastq file should contain QVs of all reads, aligned or unaligned.

**Comment by ylipacbio** [comment]
Mark, thanks for providing this function in blasr. We will integrate this change as needed.
