### ISSUE TITLE
Is it possible to have sam 1.4 format for the sam output?

### ISSUE THREAD

**Issue by chaij** [PacificBiosciences/blasr#50]
Hi,

I think it'll be great if the sam output could use the newer format where the CIGAR string is more explanative (match and mismatch will be = and X instead of both being M). Equivalently, if MD tag can be provided, it'll be nice too!

This way one doesn't have to refer back to the reference sequences to find the positions of matches and mismatches.

**Comment by ylipacbio** [comment]
I think it is a good idea. We will make CIGAR string more explanative.

**Comment by chaij** [comment]
Great, I look forward to the update!

**Comment by ylipacbio** [comment]
SAM 1.4 format is now online. In order to turn it on, please use tag **-cigarUseSeqMatch**.
