### ISSUE TITLE
arbitrary clipping despite no clipping flag

### ISSUE THREAD

**Issue by map2085** [PacificBiosciences/blasr#51]
I gave BLASR a fastq file and used these flags 

   "-clipping  none    -noSplitSubreads"

Yet hundreds of my reads were still "clipped", i.e. there are length discrepancies between the reads output in the SAM alignment and the reads input as FASTQ.  These length discrepancies range from 1 to 20,000+.  The portions of the reads clipped are NOT just "N"s

I would like BLASR to leave my reads alone and just attempt to map them as they are.  Is there some other flag that I need?

**Comment by mchaisso** [comment]
The alignments are local, and so it will report from the beginning to the
end of the local alignment, which may not include the entire read if there
are gaps in the reference, or the regions of the read are of sufficiently
low quality that there is no anchoring allowing them to be aligned.  The
20kbp+ regions likely do not map.

Please define what you mean by "leave reads alone".  Additionally, can you
specify how you generated the FASTQ files?

thanks,
-mark

**Comment by map2085** [comment]
Thank you for the fast response, Mark!

The FASTQs come from the PacBio 54x:  http://datasets.pacb.com/2014/Human54x/fastq.html

By "leave reads alone", I wanted the entire read aligned in the way that, say, Illumina short-reads are fully aligned by standard programs (e.g. BWA).  

But now I understand that the long reads are not clipped, adaptor-trimmed, or subread-split, but rather only a local alignment is given.  That is fine, thank you.
