### ISSUE TITLE
Save insertion and deletion qualities read from bax.h5 as BAM fields

### ISSUE THREAD

**Issue by andreas-wilm** [PacificBiosciences/blasr#52]
Since Blasr already interprets insertion and deletion qualities stored in the bax.h5 files, it would be helpful if they were stored in the SAM output as well. GATK's BQSR uses BI and BD tags for this (see e.g. http://gatkforums.broadinstitute.org/discussion/1619/baserecalibratorprintreads-bd-and-bi-flags)

**Comment by mchaisso** [comment]
use -printSAMQV

**Comment by andreas-wilm** [comment]
Thanks. Starting from which version/commit is this available?

**Comment by mchaisso** [comment]
I believe it is in the latest.  I'm not sure which commit it started in
though.

**Comment by andreas-wilm** [comment]
Okay great. Giving f7bf1e5 a try.

**Comment by andreas-wilm** [comment]
I think this worked. f7bf1e5 produces many private tags. I assume qi:Z and qd:Z are insertion and deletion qualities, respectively? Are these and others documented somewhere?

**Comment by andreas-wilm** [comment]
For the sake of completeness: from ./common/datastructures/alignmentset/SAMAlignment.h I would infer:
- InsertionQV: qi
- DeletionQV: qd
- SubstitutionQV: qs
- MergeQV: qm
- SubstitutionTag: ts
- DeletionTag: td
