### ISSUE TITLE
SAM ts tag written twice when using -printSAMQV

### ISSUE THREAD

**Issue by andreas-wilm** [PacificBiosciences/blasr#53]
Hi there,

I'm using f7bf1e5 with -printSAMQV to align bax files of the public ecoli-k12-P4C2-20KSS data set. For each read the "ts" tag is written twice (all other tags only once) to the SAM output. This not only blows the output up unnecessarily but it's invalid according to the SAM specification.

Thanks

**Comment by ylipacbio** [comment]
Hi Andreas, 

We have refactored the blasr code base, created libraries for processing pacbio data, handling hdf files and making alignments, and linked all executables such as blasr against these libraries. Therefore, this code base has been deprecated. Let me update the new libblasr code base to github and point you to it. 

In the new code base, many SAM specific issues have been fixed (e.g., QV tags are renamed, QV tags are documented in SAM header, and etc), and some new features are underdevelopment.

Sincerely,
Yuan

**Comment by dalexander** [comment]
yuan, let us discuss internally if there is a plan to eliminate this repo and replace with the refactored codebase at some point

**Comment by ylipacbio** [comment]
Hi Andreas,

The refactored blasr code base is available at

    https://github.com/ylipacbio/refactored_blasr_II

Please try it out. We will put this under PacBio repo soon. 

Sincerely,
Yuan

**Comment by andreas-wilm** [comment]
Thank you

Andreas
