### ISSUE TITLE
samtoh5 error

### ISSUE THREAD

**Issue by lennythomas** [PacificBiosciences/blasr#54]
When running pealing I am getting the following error. The input is just an E. coli demo dataset from the community page.

pbalign /data/Analysis_Results/1.bax.h5 /data/sequence.fasta /data/results.cmp.h5
2015-03-04 23:55:54,245 [ERROR] samtoh5 returned a non-zero exit status.[INFO] 2015-03-04T23:55:34 [samtoh5] started.
[INFO] 2015-03-04T23:55:53 [samtoh5] ended.
*** Error in `samtoh5': double free or corruption (!prev): 0x0000000000a0a710 ***
Aborted

**Comment by ylipacbio** [comment]
I am wondering which blasr code base did you use? From SMRTAnalysis or git hub and please let me know the commit number, thanks

**Comment by dyermd** [comment]
From GitHub. I don't have the specific commit because it is on a computer that I don't have with me at the moment, but I pulled it down last Tuesday / Wednesday if that helps.

**Comment by fbemm** [comment]
commit 28154b9337a636ef11edb0dc5664332e301ee42b

**Comment by ylipacbio** [comment]
Close this issue for now, will reopen it if needed.
