### ISSUE TITLE
alchemy

### ISSUE THREAD

**Issue by dawnGH** [PacificBiosciences/blasr#55]
I tried running alchemy with -posMap option, but in BasH5Simulator.cpp, usePosMap flag seems to be always set to false so posMap file is not generated.
movieName and baseFileName from input options are also never used in the code.

I ran alchemy with E. coli genome as reference and then  bash5tools.py on simulated bas.h5 file but it always generates an empty fasta file without any warning/error message.

**Comment by mchaisso** [comment]
I haven't touched the alchemy code in years, but have an interest in seeing
it work, so will take a look at it.

**Comment by pb-cdunn** [comment]
@mchaisso, Any luck?

By the way, we plan to help you merge your extensive improvements soon. (Or hopefully, to *rebase* them.)

**Comment by mchaisso** [comment]
This is really, really far down on my list.

**Comment by ylipacbio** [comment]
Closing inactive issues.
