### ISSUE TITLE
how to choose best alignment for ouput M4 format of BLASR

### ISSUE THREAD

**Issue by orangeSi** [PacificBiosciences/blasr#56]
hi,
   After self-correct with BLASR,I want to change the parameter of "-bestn " of BLASR. I don't want to rerun 
 self-correct with changed "-bestn " , because overlap is very slow , so I am finding a way that rechoose the bestn alingment from M4 output format of BLASR, That mean I must  know the M4 format very much , I found MHAP output format :[A ID] [B ID] [Jaccard score] [# shared min-mers] [0=A fwd, 1=A rc] [A start] [A end] [A length] [0=B fwd, 1=B rc] [B start] [B end] [B length], that is similar to M4 format of BLASR. But I still don't know the definition of every column much and how to choose the bestn alingnment ?

Thanks!
Si from BGI.

**Comment by mchaisso** [comment]
Hi orangeSi, see the readme at : https://github.com/mchaisso/blasr
-mark

**Comment by orangeSi** [comment]
mchaisso,Thanks！But it  don't  say how to choose the best .

**Comment by mchaisso** [comment]
The alignments are sorted by score.  The lower the number (more negative),
the better the alignment.

-mark

**Comment by orangeSi** [comment]
I check that just now , you are right, thanks！
