### ISSUE TITLE
common.mk:8: blasr/libcpp/common.mk: No such file or directory

### ISSUE THREAD

**Issue by TakashiKoyama** [PacificBiosciences/blasr#59]
Hello.
I am having a problem in installing blasr.
According to the instruction,  I tried the commands as follows;

```
$ git clone https://github.com/PacificBiosciences/blasr
$ cd blasr
$ export HDF5_INC=/usr/local/include
$ export HDF5_LIB=/usr/local/lib
$ echo $HDF5_INC
/usr/local/include
$ echo $HDF5_LIB
/usr/local/lib
$ make
```

and got an error;

```
common.mk:8: /home/samba/public/software/blasr/libcpp/common.mk: No such file or directory
make: *** No rule to make target `/home/samba/public/software/blasr/libcpp/common.mk'.  Stop.
```

So, I tried to make symbolic link of common.mk in libcpp but got error;

```
$ ln -s /home/samba/public/software/blasr/common.mk /home/samba/public/software/blasr/libcpp/
$ make
make: /home/samba/public/software/blasr/libcpp/common.mk:1: pipe: Too many open files
make: /home/samba/public/software/blasr/libcpp/common.mk:8: pipe: Too many open files
/home/samba/public/software/blasr/libcpp/common.mk:8: /common.mk: No such file or directory
make: /home/samba/public/software/blasr/libcpp/common.mk:10: pipe: Too many open files
make: /home/samba/public/software/blasr/libcpp/common.mk:11: pipe: Too many open files
make: /home/samba/public/software/blasr/libcpp/common.mk:12: pipe: Too many open files
make: /home/samba/public/software/blasr/libcpp/common.mk:16: pipe: Too many open files
make: /home/samba/public/software/blasr/libcpp/common.mk:17: pipe: Too many open files
make: /home/samba/public/software/blasr/libcpp/common.mk:18: pipe: Too many open files
lmake: *** No rule to make target `/common.mk'.  Stop.
```

How can I solve this issue?

Thanks,
Takashi

**Comment by ylipacbio** [comment]
Hi Takashi,

The blasr souce code has to be downloaded with '--recursive', e.g.,

- git clone git@github.com:PacificBiosciences/blasr.git blasr **--recursive**

Would you please `ls` the libcpp directory to check whether the following files/directories exist:

- common.mk   
- Makefile 
- pbdata   
- hdf   
- alignment 


Thank you!
Yuan

**Comment by TakashiKoyama** [comment]
Thank you for your response.
Since I am not familiar with github, I have not done setting as seen in [Generating SSH keys](https://help.github.com/articles/generating-ssh-keys/#platform-linux"Generating SSH keys") but I finally did it!

Thank you for your kind support!
