### ISSUE TITLE
Please tag a new stable release

### ISSUE THREAD

**Issue by sjackman** [PacificBiosciences/blasr#60]
The last stable release smrtanalysis-2.1 was tagged a long time ago on 2013-10-11.

**Comment by ylipacbio** [comment]
Hi Shaun,

smrtanalysis-2.2, which is the last stable release before the refactoring of blasr code base begun, has been tagged.

smrtanalysis-3.0-dev, which is reasonably stable on Centos-6 and Ubuntu 12.04 using gcc, and still under-development, has also been tagged. This version uses the refactored blasr library, does not support performing IO on BAM files, and could not compile on iOS at this point.

Yuan

**Comment by sjackman** [comment]
Thanks, Yuan! Is 2.2 expected to build on Mac OS?

**Comment by ylipacbio** [comment]
No. We will continue to work on the blasr code base to make it happen.

**Comment by ylipacbio** [comment]
The latest commit 50a9a804fb should be able to compile and run on iOS.
Note that the multipl-threading tag ```-nproc``` is disabled for iOS.
