### ISSUE TITLE
make install does not install bin/blasr

### ISSUE THREAD

**Issue by sjackman** [PacificBiosciences/blasr#61]
That's so weird. Why is that? `alignment/Makefile` installs [`DISTRIB_SET `](https://github.com/PacificBiosciences/blasr/blob/smrtanalysis-2.2/alignment/Makefile#L30), a set of executables that excludes `blasr wordCounter printReadWordCount`. Why?

**Comment by ylipacbio** [comment]
The alignment/Makefile has been fixed in version smrtanalysis-2.2, commit b0dd562bd0

blasr was removed from alignment/Makefile when blasr has been migrated from the 'legacy' code base to the refactored code base, while other executables haven't.

**Comment by sjackman** [comment]
Thanks!
