### ISSUE TITLE
missing LICENSE or COPYING file

### ISSUE THREAD

**Issue by wookietreiber** [PacificBiosciences/blasr#63]
The blasr git repository does include neither a `LICENSE` or `COPYING` file. Also, the `README.md` does not indicate under which license blasr is released.

**Comment by wookietreiber** [comment]
I see now that you have a license file in the other *legacy* branches, just not in master. Now, which one of the branches should I clone from? ... because the instruction in `README.md` tell me to pull from master ...

**Comment by pb-cdunn** [comment]
Back to older `master` now. And yes, we should copy the PacBio open-source LICENSE file. Will do. Soon.
