### ISSUE TITLE
ssh gitmodules URL requires GitHub account with ssh keys

### ISSUE THREAD

**Issue by wookietreiber** [PacificBiosciences/blasr#64]
Having an ssh URL in `.gitmodules` (`url = git@github.com:Pac...`) requires you to have a GitHub account that is set up with ssh or cloning will fail:

```
$ git clone --recursive git://github.com/PacificBiosciences/blasr.git
Cloning into 'blasr'...
remote: Counting objects: 2355, done.
remote: Compressing objects: 100% (4/4), done.
remote: Total 2355 (delta 0), reused 0 (delta 0), pack-reused 2351
Receiving objects: 100% (2355/2355), 2.36 MiB | 683.00 KiB/s, done.
Resolving deltas: 100% (1182/1182), done.
Checking connectivity... done.
Submodule 'libcpp' (git@github.com:PacificBiosciences/blasr_libcpp.git) registered for path 'libcpp'
Cloning into 'libcpp'...
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
Clone of 'git@github.com:PacificBiosciences/blasr_libcpp.git' into submodule path 'libcpp' failed
```

Not all users have this set up. Although I have a GitHub account and set it up with ssh I also ran into this issue on a machine where I didn't set up GitHub with ssh keys but wanted to recursively clone the repository anyway.

I worked around the issue by changing the URL to `url = https://github.com/Pac...`, however, this can only be done after the repository has been cloned non-recursively, i.e.:

```
git clone https://github.com/Pac...
sed -e 's|git@github.com:|https://github.com/|' -i .gitmodules
git submodule init
git submodule update
```

It would be nice, in respect to your installation instruction all pointoing to cloning the git repository, if this would not be an ssh URL, but either `git://...` or `https://...` URL so the above workaround wouldn't be necessary.

**Comment by pb-cdunn** [comment]
Yes, thank you. We'll definitely make that change.

I've force-pushed master back to its version before June 29, since our changes are not quite ready yet.  We'll have this working by Monday. Until then, hopefully the previous version will suffice.
