### ISSUE TITLE
impossible to use make jobs

### ISSUE THREAD

**Issue by wookietreiber** [PacificBiosciences/blasr#67]
It is impossible to use make jobs with GNU Make 4.1, as I get these jobserver warnings:

```
$ make -j4 HDF5_LIB=/usr/lib HDF5_INC=/usr/include ZLIB_ROOT=/usr 
export PBINCROOT=/home/wookietreiber/src/idiv/blasr/libcpp && export HDF5_LIB=/usr/lib && export HDF5_INC=/usr/include && export nopbbam=true  && make -C /home/wookietreiber/src/idiv/blasr/libcpp all 
export PBINCROOT=/home/wookietreiber/src/idiv/blasr/libcpp && export HDF5_LIB=/usr/lib && export HDF5_INC=/usr/include && export nopbbam=true  && make -C utils  
make[1]: warning: jobserver unavailable: using -j1.  Add '+' to parent make rule.
make[1]: Entering directory '/home/wookietreiber/src/idiv/blasr/libcpp'
make -C pbdata all
make[1]: warning: jobserver unavailable: using -j1.  Add '+' to parent make rule.
...
```

Thus, all compilation is sequential instead of the speedy parallel version.

I searched a bit and it seems that this is due to the Makefile structure, using PHONY targets and using make -C instead of subdirs that make can't properly figure out how to parallelize.

**Comment by pb-cdunn** [comment]
Yes, but there are parts of the wider project which have race conditions. I hadn't found time to address those yet.

In general, your changes look good and are appreciated. However, we are still hosting in Perforce and mirroring to GitHub. Let me see how quickly we can make GitHub the actual repo, as we've done for blasr_libcpp already. Then we might be able to merge your changes.

**Comment by pb-cdunn** [comment]
`--jobs` should now work in both **blasr** and **blasr_libcpp**. See [travis.sh](../blob/master/travis.sh).
