### ISSUE TITLE
git clone doesnt work.

### ISSUE THREAD

**Issue by ascendo** [PacificBiosciences/blasr#69]
wyim~/Downloads $ git clone git@github.com:PacificBiosciences/blasr.git blasr --recursive
Cloning into 'blasr'...
The authenticity of host 'github.com (192.30.252.131)' can't be established.
RSA key fingerprint is 16:27:ac:a5:76:28:2d:36:63:1b:56:4d:eb:df:a6:48.
Are you sure you want to continue connecting (yes/no)? yes
Warning: Permanently added 'github.com,192.30.252.131' (RSA) to the list of known hosts.
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

I think there's some problem to read repository.

**Comment by pbjd** [comment]
Try git clone https://github.com/PacificBiosciences/blasr.git.  The URL you're using is reserved for people from pacbio.

**Comment by wookietreiber** [comment]
See also #64.

**Comment by pb-cdunn** [comment]
I updated the submodule to use `git:`. (`https:` would also work.) However, `git@` will work best for you if you configure **ssh** for yourself. Here is how, if you want:
* https://help.github.com/categories/ssh/

**PacificBiosciences/blasr** is a public repo, so you can clone it even via `git@` if you set up **ssh**.

> The authenticity of host 'github.com (192.30.252.131)' can't be established.

Via `git@`, you would see that message for *any* GitHub repo.
