### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by ascendo** [PacificBiosciences/blasr#70]
I've got this error during compile.

cc1plus: error: unrecognized command line option "-std=c++11"

Do I need to update my compiler or is there any easy way to resolve it?

Version G++
g++ (GCC) 4.4.7 20120313 (Red Hat 4.4.7-11)

Thanks.

**Comment by pb-cdunn** [comment]
You need a more recent version of **g++**. Or try **clang++**.

Worst case, change that to `-std=c++0x`, which *might* work. Not sure.

**Comment by pbjd** [comment]
gcc 4.8 or higher

**Comment by ascendo** [comment]
Thanks
