### ISSUE TITLE
common.mk:8: .../libcpp/common.mk: No such file or directory

### ISSUE THREAD

**Issue by tomoakin** [PacificBiosciences/blasr#71]
Similar to issue #59, but this time, the common.mk seems to have been deleted from
libcpp by the commit: 
https://github.com/PacificBiosciences/blasr_libcpp/commit/7f5a34d37554e19956c6ee7440b05f77182e8bd0

So, --recursive does not help.

**Comment by pb-cdunn** [comment]
Try to reset back to whatever version of blasr you used last. We will fix the tip soon, but we are in the middle of something.

**Comment by pb-cdunn** [comment]
This should work now. See [travis.sh](../blob/master/travis.sh) for an example. Or see [FAQ](../wiki/Blasr-Installation-Qs-&-As).
