### ISSUE TITLE
Exception: 32512

### ISSUE THREAD

**Issue by cancan101** [PacificBiosciences/blasr#73]
I am getting the following exception when I try to run configure.
```
bash -c 'set -e; set -o pipefail; id=$(lsb_release -si | tr "[:upper:]" "[:lower:]"); rel=$(lsb_release -sr); case $id in ubuntu) printf "$id-%04d
" ${rel/./};; centos) echo "$id-${rel%%.*}";; *) echo "$id-$rel";; esac' 2>/dev/null
Traceback (most recent call last):
  File "./configure.py", line 194, in <module>
    main(*sys.argv)
  File "./configure.py", line 189, in main
    set_defs_defaults(envin, conf.no_pbbam)
  File "./configure.py", line 140, in set_defs_defaults
    setifenvf(defaults, env, 'OS_STRING', get_OS_STRING)
  File "./configure.py", line 65, in setifenvf
    envout[key] = ifenvf(envin, key, func)
  File "./configure.py", line 63, in ifenvf
    return func()
  File "./configure.py", line 55, in get_OS_STRING
    return shell(G_BUILDOS_CMD)
  File "./configure.py", line 27, in shell
    raise Exception('%d <- %r' %(status, cmd))
Exception: 32512 <- 'bash -c \'set -e; set -o pipefail; id=$(lsb_release -si | tr "[:upper:]" "[:lower:]"); rel=$(lsb_release -sr); case $id in ubuntu) printf "$id-%04d\n" ${rel/./};; centos) echo "$id-${rel%%.*}";; *) echo "$id-$rel";; esac\' 2>/dev/null'
```

**Comment by cancan101** [comment]
The reason is that `lsb_release` is not available in newer versions of ubuntu.

**Comment by cancan101** [comment]
Solved by installing `lsb-release`.

**Comment by pb-cdunn** [comment]
Glad you got it working.

We no longer need `OS_STRING`. Just forgot to delete it. If you don't have pbbam, see [travis.sh](https://github.com/PacificBiosciences/blasr/blob/master/travis.sh). (We will run Travis Continuous Integration as soon as we produce a prebuilt HDF5 library.)

I'm curious: What were your arguments to `configure.py`?

**Comment by cancan101** [comment]
@pb-cdunn Why is travis not set up to run? Ubuntu should have hdf5 libs that can be installed as part of the build.

**Comment by pb-cdunn** [comment]
For speed, we use [*Dockerized* builds](http://blog.travis-ci.com/2014-12-17-faster-builds-with-container-based-infrastructure/), so we are restricted to the [Travis *whitelist*](https://github.com/travis-ci/apt-package-whitelist/blob/master/ubuntu-precise) for [**APT**](http://docs.travis-ci.com/user/apt/). See
* https://github.com/PacificBiosciences/pbdagcon/pull/9
* https://github.com/PacificBiosciences/pbdagcon/pull/7

We plan instead to use a tarball for HDF5. Eventually, we also want a tarball for pbbam, which would give us much higher test coverage.

**Comment by cancan101** [comment]
Yeah, figured as I much. I filed: https://github.com/travis-ci/travis-ci/issues/4480 but I think the version they will get is older.

**Comment by pb-cdunn** [comment]
(We also simply haven't gotten around to it. Your way would be better than nothing. Soon! Unless you submit a pull-request with `.travis.yml`.)

**Comment by cancan101** [comment]
Though you can always run with `sudo: true` it just starts up a little slower.

**Comment by pb-cdunn** [comment]
Thanks for the Travis request. Subscribed.

**Comment by pb-cdunn** [comment]
That doesn't seem to help for APT packages. We'll probably have to get tarballs anyway.

Just curious: Using ubuntu-precise and the whitelisted libhdf5-dev, where do you find the header files?

**Comment by cancan101** [comment]
Here is what this lib installs: http://packages.ubuntu.com/precise/amd64/libhdf5-serial-dev/filelist. What are you looking for?

**Comment by pb-cdunn** [comment]
Interesting. So if I could use `precise`, then I'd have it. But I really, really want the Docker container.

**Comment by cancan101** [comment]
I'm not sure what you mean about using precise.

Also why the strong feelings about the docker container? It speeds up the builds slightly.

**Comment by pb-cdunn** [comment]
> I'm not sure what you mean about using precise.

APT is a weird system. It's not simply apt-get. I use `ubuntu-toolchain-r/test` from [the whitelist](https://github.com/travis-ci/apt-source-whitelist/blob/master/ubuntu.json).

> Also why the strong feelings about the docker container? It speeds up the builds slightly.

The docker-builds acquire a machine *much* faster. I've spent minutes waiting for machines on slow days, but with docker it's nearly instantaneous. This matters most *when I am debugging the configuration*. I make a tiny change in `.travis.yml`, push, and watch the result. I have to do that many times. E.g. we are testing with **g++** *and* **clang++** using C++11, which can be [tricky to set up in Travis](http://stackoverflow.com/a/30925448).

The other advantages are less important, depending on the speed of the rest of the build.

Anyway, switching off docker for this package is certainly on the table.

**Comment by cancan101** [comment]
I would say slightly slower CI tests are better than no CI tests as well.

**Comment by pb-cdunn** [comment]
Fair enough.
