### ISSUE TITLE
cannot find -lblasr

### ISSUE THREAD

**Issue by cancan101** [PacificBiosciences/blasr#74]
```
g++ -O3 -g -std=c++0x -pedantic -Wall -Wuninitialized -Wno-div-by-zero -MMD -MP -w -fpermissive -fno-builtin-malloc -fno-builtin-calloc -fno-builtin-realloc -fno-builtin-free -fno-omit-frame-pointer  -I./libcpp/alignment -I./libcpp/pbdata -I./libcpp/hdf -I/usr/lib/x86_64-linux-gnu/hdf5/serial/include  -c -o Blasr.o Blasr.cpp
g++ -o blasr -O3 -g -std=c++0x -pedantic -Wall -Wuninitialized -Wno-div-by-zero -MMD -MP -w -fpermissive -fno-builtin-malloc -fno-builtin-calloc -fno-builtin-realloc -fno-builtin-free -fno-omit-frame-pointer  -I./libcpp/alignment -I./libcpp/pbdata -I./libcpp/hdf -I/usr/lib/x86_64-linux-gnu/hdf5/serial/include -MF"blasr.d" Blasr.o -static -L./libcpp/alignment -L./libcpp/pbdata -L./libcpp/hdf -L/usr/lib/x86_64-linux-gnu/hdf5/serial/lib -lblasr -lpbdata -lpbihdf  -lhdf5_cpp -lhdf5  -lz -lpthread -ldl
/usr/bin/ld: cannot find -lblasr
/usr/bin/ld: cannot find -lpbdata
/usr/bin/ld: cannot find -lpbihdf
/usr/lib/gcc/x86_64-linux-gnu/4.9/../../../x86_64-linux-gnu/libhdf5.a(H5PL.o): In function `H5PL__open':
/build/buildd/hdf5-1.8.12+docs/debian/build/src/../../../src/H5PL.c:535: warning: Using 'dlopen' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
collect2: error: ld returned 1 exit status
make: *** [blasr] Error 1
```

**Comment by wookietreiber** [comment]
I have had the same problem. See this [Arch Linux PKGBUILD for blasr](https://aur4.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=blasr-git), especially the `prepare` function, which contains all of my mini sed patches to get it to compile. IIRC the important patches were the `PBINCROOT` fixes.

**Comment by pb-cdunn** [comment]
You need to run `./configure.py` first. Look at [travis.sh](https://github.com/PacificBiosciences/blasr/blob/master/travis.sh).

The problem today is this:
```
In file included from MappingIPC.h:14:0,
                 from Blasr.cpp:15:
./libcpp/alignment/files/ReaderAgglomerate.hpp:16:28: fatal error: HDFBasReader.hpp: No such file or directory
```
That file is excluded from the build for `nopbbam`, but it is still included by Blasr.cpp. I need to contact a colleague about that.

However, if you drop `--sub --no-pbbam`, and if you specify *all* these flags in your environment (or pass them as make-flags to configure.py), then `./configure.py` will work for you:
```
    PBBAM_INCLUDE=
    HTSLIB_INCLUDE=
    HDF5_INCLUDE=
    BOOST_INCLUDE=
    PBBAM_LIB=
    HTSLIB_LIB=
    HDF5_LIB=
    ZLIB_LIB=

    PBBAM_LIBFLAGS=-lpbbam
    HTSLIB_LIBFLAGS=-lhts
```
We want to make this simpler. Could you tell me what you *want* to specify for configuration?

**Comment by landstr0m** [comment]
Hello, I'm having a similar problem using the make.

I've followed all the instructions on the manual (I think...) but I'm hitting an issue:

andrew@Kevin:~/helloJoe/blasr$ ./configure.py --no-pbbam
writing to '/home/andrew/helloJoe/blasr/defines.mk'
"""
LIBBLASR_LIBFLAGS    ?= -lblasr
SHELL                ?= bash
LIBPBIHDF_INCLUDE    ?= ${ROOT}/libcpp/hdf
DL_LIBFLAGS          ?= -ldl
LIBPBDATA_INCLUDE    ?= ${ROOT}/libcpp/pbdata
LIBPBIHDF_LIBFLAGS   ?= -lpbihdf
LIBPBDATA_LIB        ?= ${ROOT}/libcpp/pbdata
LIBBLASR_INCLUDE     ?= ${ROOT}/libcpp/alignment
LIBBLASR_LIB         ?= ${ROOT}/libcpp/alignment
HDF5_LIB             ?= /usr/local/hdf5/lib
HDF5_LIBFLAGS        ?= -lhdf5_cpp -lhdf5
LIBPBDATA_LIBFLAGS   ?= -lpbdata
ZLIB_LIBFLAGS        ?= -lz
HDF5_INCLUDE         ?= /usr/local/hdf5/include
PTHREAD_LIBFLAGS     ?= -lpthread
LIBPBIHDF_LIB        ?= ${ROOT}/libcpp/hdf
LDFLAGS+=-static
SUB_CONF_FLAGS+=--shared
"""
andrew@Kevin:~/helloJoe/blasr$ make blasr
g++ -O3 -g -std=c++0x -pedantic -Wall -Wuninitialized -Wno-div-by-zero -MMD -MP -w -fpermissive -fno-builtin-malloc -fno-builtin-calloc -fno-builtin-realloc -fno-builtin-free -fno-omit-frame-pointer  -I./libcpp/alignment -I./libcpp/pbdata -I./libcpp/hdf -I/usr/local/hdf5/include  -c -o Blasr.o Blasr.cpp
In file included from ./libcpp/alignment/datastructures/anchoring/AnchorParameters.hpp:7:0,
                 from MappingParameters.h:13,
                 from MappingIPC.h:6,
                 from Blasr.cpp:15:
./libcpp/pbdata/DNASequence.hpp:11:23: fatal error: libconfig.h: No such file or directory
 #include "libconfig.h"
                       ^
compilation terminated.
make: *** [Blasr.o] Error 1
andrew@Kevin:~/helloJoe/blasr$

**Comment by pb-cdunn** [comment]
```
make init-submodule
make blasr
```
I'll add that to the README.

**Comment by landstr0m** [comment]
Cheers, that worked and moved me along a bit! I'm now getting a new error, although it looks like something to do with my dependencies. Any pointers you could give I would be grateful!

andrew@Kevin:~/helloJoe/blasr$ make blasr
g++ -O3 -g -std=c++0x -pedantic -Wall -Wuninitialized -Wno-div-by-zero -MMD -MP -w -fpermissive -fno-builtin-malloc -fno-builtin-calloc -fno-builtin-realloc -fno-builtin-free -fno-omit-frame-pointer  -I./libcpp/alignment -I./libcpp/pbdata -I./libcpp/hdf -I/usr/local/hdf5/include  -c -o Blasr.o Blasr.cpp
g++ -o blasr -O3 -g -std=c++0x -pedantic -Wall -Wuninitialized -Wno-div-by-zero -MMD -MP -w -fpermissive -fno-builtin-malloc -fno-builtin-calloc -fno-builtin-realloc -fno-builtin-free -fno-omit-frame-pointer  -I./libcpp/alignment -I./libcpp/pbdata -I./libcpp/hdf -I/usr/local/hdf5/include -MF"blasr.d" Blasr.o -static -L./libcpp/alignment -L./libcpp/pbdata -L./libcpp/hdf -L/usr/local/hdf5/lib -lpbihdf -lblasr -lpbdata -lpbihdf  -lhdf5_cpp -lhdf5  -lz -lpthread -ldl
/usr/bin/ld: cannot find -lz
/usr/local/hdf5/lib/libhdf5.a(H5PL.o): In function `H5PL__open':
/home/andrew/helloJoe/hdf5-1.9.225/src/H5PL.c:597: warning: Using 'dlopen' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
collect2: error: ld returned 1 exit status
make: *** [blasr] Error 1

**Comment by pb-cdunn** [comment]
You need to specify `ZLIB_LIB` (a directory) when you configure the build:
```
./configure.py --no-pbbam ZLIB_LIB=path
```
Let's see if that works.

**Comment by landstr0m** [comment]
Sorry - I'm not sure which directory I should be pathing to - I've tried searching my system with:
sudo find / -iname "*ZLIB*"
but it doesn't return anything with hcf5 or any of the blasr folders.

**Comment by pb-cdunn** [comment]
You need a file called `libz.a` or `libz.so` or `libz.so.*`. It's almost certainly on your system somewhere. But if not, contact your sysadmin for help installing it.

**Comment by landstr0m** [comment]
Thanks so much for your help! 

I managed to get it to work now, in case anyone following has the same problem, the commands I used were:
`sudo apt-get install zlib1g-dev`
`sudo find / -iname "libz*"`
`ZLIB_LIB=/lib/x86_64-linux-gnu`

Cheers,
Andrew
