### ISSUE TITLE
compilation error

### ISSUE THREAD

**Issue by kemin711** [PacificBiosciences/blasr#81]
make
g++ -O3 -g -std=c++0x -pedantic -Wall -Wuninitialized -Wno-div-by-zero -MMD -MP -w -fpermissive -fno-builtin-malloc -fno-builtin-calloc -fno-builtin-realloc -fno-builtin-free -fno-omit-frame-pointer  -I./libcpp/alignment -I./libcpp/pbdata -I./libcpp/hdf  -c -o Blasr.o Blasr.cpp
In file included from MappingIPC.h:6:0,
                 from Blasr.cpp:15:
MappingParameters.h:9:30: fatal error: reads/ReadType.hpp: No such file or directory
 #include "reads/ReadType.hpp"
                              ^
compilation terminated.
make: *** [Blasr.o] Error 1

**Comment by kemin711** [comment]
This problem is resolved by adding the --recursive to the gig clone "https://...." command
But you will get another compiling error: 
make
g++ -O3 -g -std=c++0x -pedantic -Wall -Wuninitialized -Wno-div-by-zero -MMD -MP -w -fpermissive -fno-builtin-malloc -fno-builtin-calloc -fno-builtin-realloc -fno-builtin-free -fno-omit-frame-pointer  -I./libcpp/alignment -I./libcpp/pbdata -I./libcpp/hdf  -c -o Blasr.o Blasr.cpp
In file included from ./libcpp/alignment/datastructures/anchoring/AnchorParameters.hpp:7:0,
                 from MappingParameters.h:13,
                 from MappingIPC.h:6,
                 from Blasr.cpp:15:
./libcpp/pbdata/DNASequence.hpp:11:23: fatal error: libconfig.h: No such file or directory
 #include "libconfig.h"
                       ^
compilation terminated.
make: *** [Blasr.o] Error 1

I will see that I can resolve this one.

**Comment by pb-cdunn** [comment]
Yes, `git clone --recursive` is one way. Another is to run `make update-submodule` after checkout.

Then, to build the submodule, `make build-submodule`.
