### ISSUE TITLE
pbbam compiler error

### ISSUE THREAD

**Issue by kemin711** [PacificBiosciences/blasr#82]
I am seeing a whole bunch of compiling errors.  Any one know where is the dependency for pbbam?  I could not seem to be able to locate this on the internet.
Even I disable the pbbam with --no-pbbam flag, the lower makefiles are still looking for it.
```
In file included from ../libcpp/hdf/BufferedHDFArray.hpp:19:0,
                 from ../libcpp/hdf/HDFArray.hpp:11,
                 from ../libcpp/hdf/HDFCmpFile.hpp:12,
                 from LoadPulses.cpp:3:
../libcpp/pbdata/DNASequence.hpp:14:29: fatal error: pbbam/BamRecord.h: No such file or directory
 #include "pbbam/BamRecord.h"
```

**Comment by pb-cdunn** [comment]
We need the following info to help you debug this:
* SHA1 commit for blasr (`git rev-parse --short HEAD`)
* SHA1 commit for libcpp (`cd libcpp; git rev-parse --short HEAD`)
* The exact arguments you passed to configure.py
* The contents of the generated `defines.mk`.

**Comment by kemin711** [comment]
Christopher,
Thanks for the help.  Generally, I could not find the pbbam dependency on the internet.I was able to compile after editing a few source files where pbbam is mentioned, and change the make file on all lines involving the pbbam variable.
Am I supposed to use the pbbam module or not? Kemin Zhou
858 771-3269

**Comment by pb-cdunn** [comment]
No. We plan to **pbbam** in GitHub, but it's not there yet.

You need `configure.py --no-pbbam`. See the file `travis.sh` to see how we build it externally.

**Comment by kemin711** [comment]
Christopher,
the configure flag --no-pbbam is not sufficient, make file and the source codes are not completely in sync.Anyway, I got this revolved.  Just letting you know that just a little touch up is needed; otherwise the code itself is good. Kemin Zhou
858 771-3269

**Comment by pb-cdunn** [comment]
```
export HDF5_INCLUDE=whatever
export HDF5_LIB=whatever
git clone git://github.com/PacificBiosciences/blasr.git
cd blasr
./travis.sh
```
Works for me. I suspect that you're doing something wrong, but I cannot tell you what without the details that I requested.
