### ISSUE TITLE
Documentation typo

### ISSUE THREAD

**Issue by esolares** [PacificBiosciences/blasr#85]
Hi there is a problem with the documentation (readme) where it states to perform:

git clone git@github.com:PacificBiosciences/blasr.git --recursive

but instead should be:

git clone https://github.com/PacificBiosciences/blasr.git --recursive

**Comment by pb-cdunn** [comment]
Thanks you! We'll update that right away. (It's a typo only for users who don't have ssh configured, but that's probably most users.)

**Comment by esolares** [comment]
no problem. thank you for your quick response.

Thank you,

Edwin Solares, B.S.
Computational Biology
Department of Ecology and Evolutionary Biology
413 Steinhaus Hall
University of California, Irvine
Irvine, CA 92697
USA

On Mon, Jul 27, 2015 at 12:26 PM, Christopher Dunn <notifications@github.com

**Comment by pb-cdunn** [comment]
Thanks for leaving your personal info. We love to know who is using our tools!
