### ISSUE TITLE
cloning failed

### ISSUE THREAD

**Issue by kemin711** [PacificBiosciences/blasr#86]
I have tried twice and getting the same results:
Not sure what went wrong.  I was able to clone this from a different IP, using the https interface.

git clone git@github.com:PacificBiosciences/blasr.git blasr --recursive
Initialized empty Git repository in /remote/RSU/home/zhouk15/src/blasr/.git/
Enter passphrase for key '/home/users/zhouk15/.ssh/id_rsa':
remote: Counting objects: 2727, done.
remote: Compressing objects: 100% (7/7), done.
remote: Total 2727 (delta 2), reused 0 (delta 0), pack-reused 2720
Receiving objects: 100% (2727/2727), 2.57 MiB | 110 KiB/s, done.
Resolving deltas: 100% (1384/1384), done.
Submodule 'libcpp' (git://github.com/PacificBiosciences/blasr_libcpp.git) registered for path 'libcpp'
Initialized empty Git repository in /remote/RSU/home/zhouk15/src/blasr/libcpp/.git/
fatal: read error: Connection timed out
Clone of 'git://github.com/PacificBiosciences/blasr_libcpp.git' into submodule path 'libcpp' failed

**Comment by pb-cdunn** [comment]
Ok. I'll try to help you debug this. Try just the blasr_libcpp link:
```
mkdir foo
cd foo
git clone git://github.com/PacificBiosciences/blasr_libcpp.git
```
And tell me your version of **git**:

    git --version

(And yeah, I noticed it was actually blasr. Not a big deal.)

**Comment by kemin711** [comment]
I see.  I failed both the https and ssh with  git --version
git version 1.7.1
================
 git clone https://github.com/PacificBiosciences/blasr.git --recursive
Initialized empty Git repository in /remote/RSU/home/zhouk15/src/blasr/.git/
remote: Counting objects: 2746, done.
remote: Compressing objects: 100% (26/26), done.
remote: Total 2746 (delta 13), reused 0 (delta 0), pack-reused 2720
Receiving objects: 100% (2746/2746), 2.58 MiB | 182 KiB/s, done.
Resolving deltas: 100% (1395/1395), done.
Submodule 'libcpp' (git://github.com/PacificBiosciences/blasr_libcpp.git) registered for path 'libcpp'
Initialized empty Git repository in /remote/RSU/home/zhouk15/src/blasr/libcpp/.git/
fatal: read error: Connection timed out
Clone of 'git://github.com/PacificBiosciences/blasr_libcpp.git' into submodule path 'libcpp' failed
====================

And was successful with the newer version 1.9.1 to do the recursive pull over the weekend from a different machine.

 mkdir libcpp
 cd libcpp
git version 1.7.1
git clone git://github.com/PacificBiosciences/blasr_libcpp.git
Initialized empty Git repository in /remote/RSU/home/zhouk15/src/blasr/libcpp/blasr_libcpp/.git/
------ waiting for a long time, no action, nothing is happening

On my machine of git version 1.9
git clone git://github.com/PacificBiosciences/blasr_libcpp.git
Cloning into 'blasr_libcpp'...
remote: Counting objects: 2016, done.
remote: Total 2016 (delta 0), reused 0 (delta 0), pack-reused 2016
Receiving objects: 100% (2016/2016), 1.69 MiB | 1.55 MiB/s, done.
Resolving deltas: 100% (1281/1281), done.
Checking connectivity... done.

This can be done very quickly, so it is definitely my old git version.

**Comment by pb-cdunn** [comment]
Interesting. Good to know, actually.

**Comment by kemin711** [comment]
It is kind of strange that I can clone almost every other pacbio projects.  It must be some trivial mismatch between the server and the client program for git.  And the error message is not helpful in identifying what went wrong.  "fatal: read error: Connection timed out"
