### ISSUE TITLE
fail to compile

### ISSUE THREAD

**Issue by arkyl** [PacificBiosciences/blasr#88]
Hi,
I tried to compile the new blasr but had the following error:
```
g++ -o blasr -O3 -g -std=c++0x -pedantic -Wall -Wuninitialized -Wno-div-by-zero -MMD -MP -w -fpermissive -fno-builtin-malloc -fno-builtin-calloc -fno-builtin-realloc -fno-builtin-free -fno-omit-frame-pointer  -I/stornext/snfs4/gen-asm/local-bin/blasr/libcpp/alignment -I/stornext/snfs4/gen-asm/local-bin/blasr/libcpp/pbdata -I/stornext/snfs4/gen-asm/local-bin/blasr/libcpp/hdf -I/stornext/snfs4/gen-asm/local-bin/hdf5-1.8.15-patch1/hdf5/include/ -MF"blasr.d" Blasr.o -static -L/stornext/snfs4/gen-asm/local-bin/blasr/libcpp/alignment -L/stornext/snfs4/gen-asm/local-bin/blasr/libcpp/pbdata -L/stornext/snfs4/gen-asm/local-bin/blasr/libcpp/hdf -L/stornext/snfs4/gen-asm/local-bin/hdf5-1.8.15-patch1/hdf5/lib/ -L/hgsc_software/zlib/latest/lib/ -lpbihdf -lblasr -lpbdata -lpbihdf  -lhdf5_cpp -lhdf5  -lz -lpthread -ldl
/stornext/snfs4/gen-asm/local-bin/hdf5-1.8.15-patch1/hdf5/lib//libhdf5.a(H5PL.o): In function `H5PL_load':
H5PL.c:(.text+0x5ae): warning: Using 'dlopen' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
/usr/lib/../lib64/libpthread.a(libpthread.o): In function `sem_open':
(.text+0x764d): warning: the use of `mktemp' is dangerous, better use `mkstemp'
/stornext/snfs4/gen-asm/local-bin/blasr/libcpp/alignment/libblasr.a(MappingMetrics.o): In function `Timer::Tick()':
MappingMetrics.cpp:(.text+0x1d3): undefined reference to `clock_gettime'
/stornext/snfs4/gen-asm/local-bin/blasr/libcpp/alignment/libblasr.a(MappingMetrics.o): In function `Timer::Tock()':
MappingMetrics.cpp:(.text+0x22b): undefined reference to `clock_gettime'
collect2: error: ld returned 1 exit status
make: *** [blasr] Error 1
```
Everything seems ok until final step compiling for blasr. Any advice? Thanks a lot.

Yue

**Comment by pb-cdunn** [comment]
What were the arguments you used to run `./configure.py`? (For example, see [travis.sh](../blob/master/travis.sh).) Also, what commit are you using?

**Comment by arkyl** [comment]
git clone git://github.com/PacificBiosciences/blasr.git blasr --recursive

I export the hdf5 lib/ and include/ path. Then
./configure.py --no-pbbam

Later I also export the ZLIB_INCLUDE and ZLIB_LIB path as it complained about -lz.

**Comment by arkyl** [comment]
I tried your example travis.sh. with ./configure.py --shared --sub --no-pbbam. And the compile is successful with perhaps a minor bug.

When it compile libcpp/hdf/libpbihdf.so and libcpp/alignment/libblasr.so, it didn't use the $ZLIB_PATH/libz.so; rather it used only $ZLIB_PATH.

g++ -shared -fPIC -o libpbihdf.so  ....... /libhdf5.so /hgsc_software/zlib/latest/lib/
/hgsc_software/zlib/latest/lib/: file not recognized: Is a directory
collect2: error: ld returned 1 exit status

g++ -shared -fPIC -o libblasr.so   ....... /libhdf5.so /hgsc_software/zlib/latest/lib/
/hgsc_software/zlib/latest/lib/: file not recognized: Is a directory
collect2: error: ld returned 1 exit status

I manually rerun the command with /hgsc_software/zlib/latest/lib/libz.so. And everything is ok. 

Thanks a lot for your example. Maybe it can be put on web.

Yue

**Comment by pb-cdunn** [comment]
I see what you mean. ZLIB_LIB is directory in blasr, but a file in libcpp. (Long story. We'll change that soon.) But the filename is not passed along. We'll address that. Thanks for pointing it out.
