### ISSUE TITLE
blasr: error while loading shared libraries: libpbihdf.so

### ISSUE THREAD

**Issue by SethM55** [PacificBiosciences/blasr#90]
Seems I spoke too soon.  I now have blasr compiled, but when I try to run it I get the error:
<code>blasr: error while loading shared libraries: libpbihdf.so: cannot open shared object file: No such file or directory</code>

However I do find that file in <code>blasr/libcpp/hdf/</code>  Is there a PATH export I'm missing?

**Comment by pb-cdunn** [comment]
Drop `--shared` from `./configure.py`, or add the directories to your `LD_LIBRARY_PATH`.

**Comment by SethM55** [comment]
I dropped <code>--shared</code> from the <code>./configure.py</code> but <code>defines.mk</code> still shows <code>SUB_CONF_FLAGS+=--shared</code>.  I manually removed it and finished compiling.  <code>blasr</code> compiled and I can see the help menu.

Thanks once more for all your help, I really appreciate it
