### ISSUE TITLE
runtime error

### ISSUE THREAD

**Issue by kemin711** [PacificBiosciences/blasr#95]
I made blasr before successfully:

 which blasr
/usr/local/metag/bin/blasr
kzhou@jinshou:~/work/metag$ blasr -bestn 1 -m 5 cluster1.fasta cluster1_ref.fasta -out xx.m5
[INFO] 2015-08-10T13:48:13 [blasr] started.
[INFO] 2015-08-10T13:48:13 [blasr] ended.

Now I am getting the latest version:
running travis.sh generated the blasr binary

 ~/src/metag/blasr/blasr -bestn 1 -m 5 cluster1.fasta cluster1_ref.fasta -out test.m5
[INFO] 2015-08-10T13:49:17 [blasr] started.
/home/kzhou/src/metag/blasr/blasr: symbol lookup error: /home/kzhou/src/metag/blasr/blasr: undefined symbol: _ZN15FileOfFileNames18ExpandFileNameListERSt6vectorISsSaISsEE

I am not sure this is a linking error or some other kind of error.

**Comment by kemin711** [comment]
After manually copying the *.so to a runtime environment, this problem got solved. You can close this problem.

**Comment by pb-cdunn** [comment]
Glad you got this working. Note: It's possible to build blasr statically. Just don't pass `--shared` to **configure.py**.
