### ISSUE TITLE
no 'qs' tag in SAM output

### ISSUE THREAD

**Issue by yunfeiguo** [PacificBiosciences/blasr#99]
Dear BLASR developers,

I aligned some raw reads with blasr but failed to get 'qs' tags in SAM output. These tags are required by quiver. How to get them? I am using 4462e98264a02cc5eb021ff1224f11b660060ac8. Thanks!

```
blasr E03_1/Analysis_Results/m150125_120636_42199_c100722292550000001823147304301504_s1_p0.2.bax.h5 hg38/db/GCA_000001405.15_GRCh38_no_alt_analysis_set.fa -clipping soft -sam -out m150125_120636_42199_c100722292550000001823147304301504_s1_p0.2_alignments.sam -nproc 12 -printSAMQV
```

**Comment by ylipacbio** [comment]
Hi Yufei,

In order to align reads and produce alignments for quiver, please use PacBio tool [pbalign](https://github.com/PacificBiosciences/pbalign) instead of using blasr directly. 

Sincerely,
Yuan
